### ISSUE TITLE
Revisit blocksize optimisation

### ISSUE THREAD

**Issue by esinyavuz** [genn-team/genn#1]
investigate instruction level parallelism.
performance gap between small models and larger models
revisit optimization goal (currently device occupancy only), e.g. memory bandwidth, memory sizes, etc.

**Comment by tnowotny** [comment]
When running a systematic test of performance for different block sizes, the chosen model size (``x`` in the figures), is almost always near-optimal. (Figure caption denotes the model's size) the axes are neuron kernel block sizes and synapse kernel block sizes.

![blocksize200](https://user-images.githubusercontent.com/5477463/49458164-3050b580-f7e4-11e8-9feb-e0e86b0cf254.png)
![blocksize400](https://user-images.githubusercontent.com/5477463/49458166-3050b580-f7e4-11e8-95a8-cc92af0d1836.png)
![blocksize1000](https://user-images.githubusercontent.com/5477463/49458167-30e94c00-f7e4-11e8-80da-8041a675b3c5.png)
![blocksize2000](https://user-images.githubusercontent.com/5477463/49458169-30e94c00-f7e4-11e8-8aa5-6a0c7ef0f118.png)
![blocksize4000](https://user-images.githubusercontent.com/5477463/49458171-30e94c00-f7e4-11e8-8786-127be79db950.png)
![blocksize8000](https://user-images.githubusercontent.com/5477463/49458172-30e94c00-f7e4-11e8-9e08-78149e94561f.png)
![blocksize16000](https://user-images.githubusercontent.com/5477463/49458173-30e94c00-f7e4-11e8-95ec-42f5ed45fc79.png)
![blocksize32000](https://user-images.githubusercontent.com/5477463/49458174-3181e280-f7e4-11e8-8b33-6ebb446be6dc.png)
![blocksize64000](https://user-images.githubusercontent.com/5477463/49458175-3181e280-f7e4-11e8-9fe0-76a29d139cef.png)
![blocksize128000](https://user-images.githubusercontent.com/5477463/49458176-3181e280-f7e4-11e8-98cd-0d0fb7b079c2.png)
![blocksize256000](https://user-images.githubusercontent.com/5477463/49458177-321a7900-f7e4-11e8-9922-e69f23c07e99.png)
![blocksize512000](https://user-images.githubusercontent.com/5477463/49458178-321a7900-f7e4-11e8-9903-cb892d7e9978.png)
