### ISSUE TITLE
weigh of synapse

### ISSUE THREAD

**Issue by fereshtehvosta** [genn-team/genn#100]
Hi
I want to make a neuronal network of 100 neuron and find the Critical point.
So,for this,i assign a weight for all Synapse which are in network(read from a file) and increase their weight by a epsilon in a for loop in order to detect firing rate for all neuron. and I can not see a regular pattern, in other word,

 why when we add more synaptic weigh we didn't see more spike??
Maybe my steps were wrong??
 my model is:
# include "hunderedHHModel.cc"
#include "hunderedHHModel_CODE/runner.cc"
#include <stdlib.h>
#include <iostream>
#include <iomanip>
#include <fstream>

using namespace std;
float* readFromFile(char* fileName, int numberOfNodes);

int main(){
allocateMem();
initialize();
int nodesCount = 100;
float stepTime =1;

float* pop1Self = readFromFile("data.txt", nodesCount);

float* input= new float[nodesCount];
float* d_input;
cudaMalloc((void **) &d_input, nodesCount*sizeof(float));
	
//float epsilon=0.;
for(int k=1;k<=20;k++){//for 1
    for(int i=0;i<nodesCount*nodesCount;i++){//f2
		gPop1self[i]=pop1Self[i]+0.0005;
     }//ef2
    pushPop1selfStateToDevice();
// for giving external input to 10 neuron
     int* randNodes = new int[10];
     for(int i=0; i<10;i++){//f3
		int r = rand() %nodesCount;
		randNodes[i] = r;
	}//ef3

for(int i=0; i<nodesCount; i++){//f4
		input[i] =0;
}//ef4

for(float j=0;j<500;j+=4){//f5
	
	for(int i=0; i<10; i++){//f6
		input[randNodes[i]] = 1.5*(rand()*1.0/RAND_MAX + 0.0001) ;
	}//ef6
	
	cudaMemcpy(d_input, input,nodesCount * sizeof(float), cudaMemcpyHostToDevice);
	stepTimeGPU(d_input, stepTime);

	//stepTimeGPU(1000.0);
	pullPop1StateFromDevice();
	if(j<100) continue;

	for( int i=0; i< nodesCount;i++){//f7
			cout << VPop1[i] <<endl; 
        }//ef7

    }//ef5
}//end for 1
return 0;
}

float* readFromFile(char* fileName, int numberOfNodes){
	ifstream file;
	file.open(fileName);
	float* pop1Self = new float[numberOfNodes*numberOfNodes];
	
	for(int i=0; i<numberOfNodes; i++){
		for(int j=0;j<numberOfNodes; j++){
			float f;
			file >> f;
			pop1Self[i*numberOfNodes + j] = f;
		}
	}
	return pop1Self;
}

**Comment by esinyavuz** [comment]
I assume that you are using an older version of GeNN. In the versions earlier than the current stable branch, `stepTimeGPU` takes as argument the absolute time in ms, not the time step. Therefore you are not incrementing time, it is only running for t=1 ms. In the latest stable version we got rid of this time step ambiguity by incrementing it implicitly, without passing any time-related parameter to `stepTimeGPU()`.

**Comment by tnowotny** [comment]
I also notice that unless I am mistaken you are not incrementing gPop1self repeatedly as in the line
gPop1self[i]=pop1Self[i]+0.0005;
the right hand side has pop1Self (your own array with the values from file).

If in doubt what's happening, saving gPop1self values to file and inspecting them should help.

Further to Esin's point, inspecting the globally available variable "t" will tell you whether time is progressing or not.

**Comment by fereshtehvosta** [comment]
Really thanks....
در تاریخ ۸ اوت ۲۰۱۶ ۱۴:۱۰، "Thomas Nowotny" <notifications@github.com> نوشت:

**Comment by jamesturner246** [comment]
Closing this (appears to be resolved?)
