### ISSUE TITLE
Values inside generated header files in user projects are not accessed properly in the simulation code

### ISSUE THREAD

**Issue by esinyavuz** [genn-team/genn#101]
I'm not sure whether the title is explicative enough, but here are the details:

Let's consider `sizes.h` created by `generate_run.cc` in the `MBody1_project`. The first time we run it it runs properly. If we run it again using different parameters, let's say a different number of KC's or double precision instead of single, sometimes the new parameters are not taken into account and the model runs using the previous configuration. There are no errors if the values are not causing trouble.  Moreover, it looks like during code generation new values are read properly but during simulation,  values from the previous run are used. It is not happening all the time, it looks like a memory problem. The header file is generated properly and includes correct values. Any ideas?

**Comment by jamesturner246** [comment]
Fixed.

It was caused by missing `make clean` commands, so the old objects and binaries were being used.
