### ISSUE TITLE
Synaptic weights randomly distributed

### ISSUE THREAD

**Issue by spinang** [genn-team/genn#102]
Good evening,
I'd propose you another doubt I had some days ago. Let us suppose to have a population of neurons, B, that is connected to populations A and C (A is located "before" B and C is located "after" B) and among these neurons I'd like to define some connections in which:
1. synaptic weights are randomly distributed between -0.5 and 0.5
2. input weights are fixed to 1
3. output weights undergo learning mechanism
Moreover, the interlayer synaptic connections should be based on the probability that is function of the distance between pre-synaptic neuron (i-th neuron) and post-synaptic neuron (j-th neuron), in this way:

P(i,j) = K * C(i,j)

where

k = 1 if d(i,j) <= 1
k = 0.5 if 1 < d(i,j) <= 2
k = 0 if d(i,j) > 2

and C(i,j) changes dependently on the nature of i-th and j-th neurons (inhibitory-inhibitory, inhibitory-excitatory, excitatory-inhibitory and excitatory-excitatory). Finally, the time constant of the synaptic model is considered fixed (for example, 5 ms).

Is already available a project/example that could explain me how to solve the problem?

**Comment by jamesturner246** [comment]
While they do not do exactly the above, the examples in 'genn/userproject/tools', e.g. 'gen_kcdn_syns.cc', give a basic example of making custom connectivity matrices.

1. If you want weights (uniformly or normally?) distributed in [-0.5, 0.5], then the C++11 standard header \<random\> (see http://www.cplusplus.com/reference/random/) includes the structures and functions to create these.

2. If you want fixed weights, then just use `GLOBALG` with `addSynapsePopulation`, and pass the global g value in the initial values array, e.g. 
```C++
double MySyn_ini [1] = { gValue };

model.addSynapsePopulation("MySyn", NSYNAPSE, ALLTOALL, GLOBALG, NO_DELAY, EXPDECAY, "In", "Out", MySyn_ini, MySyn_p, MySynPost_ini, MySynPost_p);
```

3. There is an example of learning synapses in the MBody1 project. Refer to the documentation (http://genn-team.github.io/genn/documentation/html/d5/d24/sectSynapseModels.html#sect33) for more information on the built-in `LEARN1SYNAPSE` learning synapse type. 

Regarding the distance-based connection probability, it would depend on how your distance function _d(i, j)_ is defined, and how the neurons are physically structured. You could structure the neurons, such that the presynaptic neurons and postsynaptic neurons are co-mingled in a three-dimensional matrix, and then use an L1 or L2 norm to determine distance. 

I believe the folks over at the NEST simulator team do a similar interesting thing for connectivity using 'masks' (see http://www.nest-simulator.org/wp-content/uploads/2015/04/Topology_UserManual.pdf). You might look there for some inspiration. 

Hope that helps,
James.

**Comment by spinang** [comment]
Ok, I'm very sorry if I can't give you other details because I'm currently unable to follow your suggestions. Anyway, the only thing I can say is surely regarding the distance function I'd to implement for my project.

d(i,j) is a euclidean norm calculated by evaluating the positions of two neurons; you can imagine that these neurons should be arranged in order to constitute a grid of n rows and m columns. I've read the NEST manual you cited but I'd to ask you if GeNN can provide similar instructions, for example to create a circular grid or, in the simplest case, a square grid. I think rectangular grids are not so complicated at all once you know that your neurons vector is a 1D n-by-m array... Maybe I should start from here and implement a function that "distributes" all these neurons in a fictitious lattice and therefore evaluating the requested norm.

I'll keep you up-to-date.

**Comment by esinyavuz** [comment]
We do not have any particular guideline on creating this type of connectivity. If you do not want to deal with generating this in C, it may be easier to use an external tool such as NEST which would allow you to create your synapses and then save the values into a file, which you can then feed into GeNN.

**Comment by esinyavuz** [comment]
Actually it may be easier to generate your network using Brian 2 simulator and then use the Brian2GeNN interface which would generate the connectivity arrays for GeNN. The interface is still at beta stage but it will be released very soon. You can take a look at it at: https://github.com/brian-team/brian2genn

More details on generating the network connectivity using Brian 2 can be found here: http://brian2.readthedocs.io/en/2.0b4/resources/tutorials/2-intro-to-brian-synapses.html
