### ISSUE TITLE
Neuron group names and number of neurons of a group

### ISSUE THREAD

**Issue by spinang** [genn-team/genn#103]
Good evening,
I have a new (simple?) question for you. Is there a way to retrieve the name of the neuron population in which a given neuron belongs to and the overall number of neurons of this population, during the execution of the simulation file? I've found a findNeuronGrp function but I'm not sure how to use it.
(I think there's a similar way to do the same also for synapse group, isn't it?)

**Comment by esinyavuz** [comment]
It depends on what information you have related to the neuron/synapse group. If you have the group ID (the order in which you add your neuron group in the model), then you can access it by `NNmodel.neuronName[groupID]`, and then you can access the number of neurons by `NNmodel.neuronN[groupID]`.

**Comment by spinang** [comment]
Ok, then if two groups are declared with the following order: `model.addNeuronPopulation(P1,...)` and `model.addNeuronPopulation(P2,...)`, P1 has ID = 0 and P2 has ID = 1, right?

**Comment by jamesturner246** [comment]
That's correct.
