### ISSUE TITLE
LEARN1SYNAPSE

### ISSUE THREAD

**Issue by fereshtehvosta** [genn-team/genn#104]
Hi..
i want to creat a network with Synapses which update according to LEARN1SYNAPSE rule.
for this i define initial value for 2variable and value for parameters 
    double s_ini[1]={
        0.0,                 // g:the synaptic conductance value
        0.125,                //gRaw  
    };
    double s_p={
    3,                        //Epre
    25,                       //tLrn
    ??,                        //tchange
   100000 ,                      //tDecay
   -12.5006,                      //tPunish10
    15.6250,                       //tPunish01
    3.75,                           //gmax
    1.8750,                         //gmid  
    1.8750,                          //gSlope
         10                                  //taueShift
    0.125,                           //gSyn0
    }; 
but i don't Know what i set value for tChang????
and unfortunately there isn't any example of this model to set these value according to this..
could you tell me about value of these  parameters???
thanks alot...

**Comment by esinyavuz** [comment]
Hi,

`$(tChng)` is the width of the learning window. You can find more information on this synapse type in the user manual: http://genn-team.github.io/genn/documentation/html/d5/d24/sectSynapseModels.html#sect33
MBody1 (and other mushroom body examples) in the `$GENN_PATH\userproject` has a synapse group [KCDN](https://github.com/genn-team/genn/blob/master/userproject/MBody1_project/model/MBody1.cc#L95) which uses this type of synapse. You can find an example set of parameters there.

**Comment by fereshtehvosta** [comment]
Hi
I saw that model and make my model but unfortunately my program has error and run just portion of my time.
my model is:
#define DT 0.1
#include "modelSpec.h"
#include "modelSpec.cc"
void modelDefinition(NNmodel &model){
	initGeNN();
	model.setName("thousandHHHir2Model");
	double p_Exc[7]={
		7.15,           //gNa: Na conductance in muS
		50.0,           //ENa: Na equi potential in mV
		1.43,            //gK: K conductance in muS
		-95.0,           //EK: K equi potential in mV
		0.02672,         //gl: l conductance in muS
		-63.563,          //El: l equi potential in mV
		0.143              // Cmem: member capacity density in nF
	};

	double ini_Exc[4]={
		-60.0,             // member potential V
		0.0529324,         // prob for Na channel activation m
		0.3176767,          // prob for not Na channel bloccking h
		0.5961207,          // prob for K channel activation n
	};
	model.addNeuronPopulation("Pop1Exc",1000,TRAUBMILES,p_Exc,ini_Exc);
	model.activateDirectInput("Pop1Exc",MATINP);
	double s_ini[2]={
		0.01,  // g:the synaptic conductance value
		0.01,   //gRaw
	};
	double s_p[11]={
	 4.0,          // 0 - Epre: Presynaptic threshold potential
	 50.0,               // 0 - TLRN: time scale of learning changes
     50.0,               // 1 - TCHNG: width of learning window
     50000.0,            // 2 - TDECAY: time scale of synaptic strength decay
     100000.0,           // 3 - TPUNISH10: Time window of suppression in response to 1/0
     200.0,              // 4 - TPUNISH01: Time window of suppression in response to 0/1
     0.015,              // 5 - GMAX: Maximal conductance achievable
     0.0075,             // 6 - GMID: Midpoint of sigmoid g filter curve
     33.33,              // 7 - GSLOPE: slope of sigmoid g filter curve
     10.0,               // 8 - TAUSHIFT: shift of learning curve
	 0.00006             // 9 - GSYN0: value of syn conductance g decays to
 
	};
	double *ps_ini=NULL;
	double pEs_p[2]={
		1.0,                   // tau_S: decay time constant for S
		0.0                   //Erev : reversal potential
	};
	double pIn_p[2]={
		1.0,                   // tau_S: decay time constant for S
		-80.0                   //Erev : reversal potential
	};

	model.addSynapsePopulation("Exc_Exc",LEARN1SYNAPSE,SPARSE,INDIVIDUALG,NO_DELAY,EXPDECAY,"Pop1Exc","Pop1Exc",s_ini,s_p,ps_ini,pEs_p);
	model.addSynapsePopulation("Inh_Inh",LEARN1SYNAPSE,SPARSE,INDIVIDUALG,NO_DELAY,EXPDECAY,"Pop1Exc","Pop1Exc",s_ini,s_p,ps_ini,pIn_p);
	 model.setMaxConn("Exc_Exc",42721);
     model.setMaxConn("Inh_Inh",387134);
   
	model.finalize();
}
i want to stimulate my network for 5000ms so:
#include "thousandHHHir2Model.cc"
#include "thousandHHHir2Model_CODE/runner.cc"
float* readFromFile11(char* fileName, int num1);
float* readFromFile12(char* fileName, int num21);
float* readFromFile13(char* fileName, int num1);
float* readFromFile41(char* fileName, int num5);
float* readFromFile42(char* fileName, int num24);
float* readFromFile43(char* fileName, int num5);
int*   readFromFile66(char* fileName, int num6);

int main(){
	allocateMem();
	initialize();
	int nodesCount =1000;
	float stepTime =5;
	int num1=42721;
	int num21=1001;
	int num24=1001;
	int num5=387134;
	float* IndExc_Exc = readFromFile11("ind1.txt",num1);
	float* IndGExc_Exc = readFromFile12("indG1.txt",num21);
	float* input= new float[nodesCount];
    float* d_input;
    cudaMalloc((void **) &d_input, nodesCount*sizeof(float));
	allocateExc_Exc(num1);
	for(int i=0;i<num1;i++){//forind1
	 CExc_Exc.ind[i] = IndExc_Exc[i];
	}//endfor ind1
	 for(int i=0;i<1001;i++){//forindG1
	 CExc_Exc.indInG[i] = IndGExc_Exc[i];
	}//endfor indG1
	 for(int i=0;i<num1;i++){//forg1
	 gExc_Exc[i] =  0.0001;
	}//endfor g1
   float* IndInh_Inh = readFromFile41("ind2.txt",num5);
	float* IndGInh_Inh = readFromFile42("indG2.txt",num24);
	allocateInh_Inh(num5);
	for(int i=0;i<num5;i++){//forind4
	 CInh_Inh.ind[i] = IndInh_Inh[i];
	}//endfor ind4
	 for(int i=0;i<1001;i++){//forindG4
	 CInh_Inh.indInG[i] = IndGInh_Inh[i];
	}//endfor indG4
	 for(int i=0;i<num5;i++){//forG4
	 gInh_Inh[i] = 0.0001;
	}//endfor G4
  initializeAllSparseArrays();
   pushExc_ExcStateToDevice();
   pushInh_InhStateToDevice();
    int* randNodes = new int[50];
     for(int i=0; i<50;i++){//f3
		int r = rand() %nodesCount;
		randNodes[i] = r;
	}//ef3
	 for(int i=0; i<nodesCount; i++){//f4
		input[i] =0;
	}//ef4

	for(int i=0; i<50; i++){//f5
		input[randNodes[i]] =1;
	}//ef5
			int t = 5;
   cudaMemcpy(d_input, input,nodesCount * sizeof(float), cudaMemcpyHostToDevice);
	for(float j=0;j<2500;j+=stepTime){
		stepTimeGPU(d_input, t + j);
		pullPop1ExcStateFromDevice();
		for( int i=0; i<1000;i++){
			cout << VPop1Exc[i] << endl; 
		}
      }
	 for(int i=0; i<nodesCount; i++){//f4
		input[i] =0;
	}//ef4
   cudaMemcpy(d_input, input,nodesCount * sizeof(float), cudaMemcpyHostToDevice);
for(float jj=2500;jj<5000;jj+=stepTime){
		//t += jj;
		stepTimeGPU(d_input,t + jj);
		pullPop1ExcStateFromDevice();
		for( int i=0; i<1000;i++){
			cout << VPop1Exc[i] << endl; 
		}
         
      }

	return 0;
}
but when i run an error occure:
cuda error 77: an illegal memory access was encounterd
what i sould to do????

**Comment by tnowotny** [comment]
I am not sure whether this is your main problem but I notice that your cudaMalloc line reads
`cudaMalloc((void *) &d_input, nodesCountsizeof(float));`
which casts the reference to a `float *` to a `void *`. This should be `void **`, i.e.
`cudaMalloc((void **) &d_input, nodesCountsizeof(float));`

**Comment by jamesturner246** [comment]
Where abouts / what line is the error occurring? Can you ran the simulation through cuda-memcheck?

Also, what version of GeNN are you using?

**Comment by fereshtehvosta** [comment]
Hi.
i don't understand what i should to do in order to correct my progrm??
error occur in line 70 in GPUrunner:
 CHECK_CUDA_ERRORS(cudaMemcpy(VPop1Exc, d_VPop1Exc, 1000 *
sizeof(float), cudaMemcpyDeviceToHost));
i don't know cuda-memchek!!!!
i use version 2.

**Comment by tnowotny** [comment]
Have you fixed the error in your code that I pointed out above?
Have you checked other user-side cudaMalloc calls for similar problems?

**Comment by fereshtehvosta** [comment]
yes i fixed but nothing is changed!!!
yes i run many of program with this cudaMalloc but there isn't any
error and when i just changed NSYNAPSE to LEARN1SYNAPSE and i run
program this error occur!!!
i don't know what i do and this program is really important for me...

**Comment by tnowotny** [comment]
Ok, don't panic.
I notice another oddity you may want to work on: Your lines
`model.setMaxConn("Exc_Exc",42721);`
`model.setMaxConn("Inh_Inh",387134);`
suggest that a pre-synaptic neuron of the `Exc_Exc` synapse population could have 42721 target post-synaptic neurons; worse, for the `Inh-Inh` you indicate 387134 possible targets per neuron. Note that the numbers in setMaxConn are not the total number of connections but the total number of connections per pre-synaptic neuron (!)
So, it is well possible that with your settings, and depending on the GPU you have, you are running out of global GPU memory. That would explain why it's worse for the LEARN1SYNAPSE as it needs quite a few more variables.
So, try,
`model.setMaxConn("Exc_Exc",1000);`
`model.setMaxConn("Inh_Inh",1000);`
(in both instances the post-synaptic population is Pop1Exc, which has 1000 neurons). Probably you can get away with even smaller numbers as you appear not to use all-to-all connections.

**Comment by fereshtehvosta** [comment]
Hi...
Really thanks for your regard ...
i want to make an hirarchy network with 1000 neuron,so i make adjency
matrix of an hirarchy network which have 900inhibitory neurons and
100excitatory neurons and these numbers extract from adjency matrix.....if
i underestand correctly you say me,i should decrease number of synaptic
connection in the network in order to work my program!?????
در تاریخ ۶ سپتامبر ۲۰۱۶ ۲۳:۲۰، "Thomas Nowotny" <notifications@github.com>
نوشت:

**Comment by tnowotny** [comment]
Hi. That is not what I said 
You just need to correct how you set the maxConn

**Comment by jamesturner246** [comment]
When you added the neuron population, you pass 1000 as the number of neurons in it. You then add SPARSE synapse groups with maximum connections (per presyn neuron) of 42721 and 387134, which doesn't make any sense, since there are only 1000 postsynaptic neurons. 

What Thomas is saying is that you should set the maxConn of the synapse groups to 1000 or less, since setting them to more than the postsynaptic neuron count is a pointless waste of memory (which is possibly the source of your error). 

Since you're setting the number of connections so high, you might as well just use DENSE connectivity.

To use cuda-memcheck, just call the main executable with cuda-memcheck before it:

```
cuda-memcheck <executable> [arguments ... ]
```

**Comment by jamesturner246** [comment]
To clarify, `model.setMaxConn("Exc_Exc",1000);` is setting the maximum number of connections *per presynaptic neuron*, not the total number of connections in the group. 

Refer to the documentation of `void NNmodel::setMaxConn`: http://genn-team.github.io/genn/documentation/html/dc/de5/classNNmodel.html#abcd74b0eb3c2696069320bd929070d4b.

**Comment by fereshtehvosta** [comment]
Oh yes.... i understand what is your mean......
I implement this change in my code and again, it has same error
در تاریخ ۷ سپتامبر ۲۰۱۶ ۱۱:۰۴، "Thomas Nowotny" <notifications@github.com>
نوشت:

**Comment by jamesturner246** [comment]
Please run your executable with cuda-memcheck:

```
cuda-memcheck <executable> [arguments ... ]
```

**Comment by fereshtehvosta** [comment]
Excuse me....but i don't work with cuda-memcheck..and can i ask you to
explain how i should rum this program whit cuda-memcheck
Really thanks
در تاریخ ۷ سپتامبر ۲۰۱۶ ۱۵:۴۲، "James Turner" <notifications@github.com>
نوشت:

**Comment by jamesturner246** [comment]
The above command is all there is to it. If your executable is called myProgram, and is located in directory /path/to/myProgram, with arguments arg1 and arg2, then do:

```
cuda-memcheck /path/to/myProgram arg1 arg2
```

**Comment by fereshtehvosta** [comment]
I ran cuda-memcheck command and this is the output:
```
d:\projects-genn\withstdprule\12\thousandhhhir2model_code\runnerGPU.cc: 70: cuda
 error 4: unspecified launch failure
========= Invalid __global__ read of size 4
=========     at 0x00000ae8 in d:\\projects-genn\\withstdprule\\12\\thousandhhhi
r2model_code\/synapseKrnl.cc:148:learnSynapsesPost(float)
=========     by thread (103,0,0) in block (7,0,0)
=========     Address 0x60052b338 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch tim
e
=========     Host Frame:C:\Windows\system32\nvcuda.dll (cuLaunchKernel + 0x19b)
 [0x8beb]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (_cudaInitManagedRuntime + 0x3ae2) [0x51c2]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (cudaLaunch + 0x105) [0x2d7b5]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (cudaLaunch<char> + 0x13) [0x15ae3]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__device_stub__Z17learnSynapsesPostf + 0x3c) [0x1535c]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (learnSynapsesPost + 0x15) [0x10b75]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (stepTimeGPU + 0x190) [0x11e00]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (main + 0x490) [0x15080]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__tmainCRTStartup + 0x136) [0x7a096]
=========     Host Frame:C:\Windows\system32\KERNEL32.DLL (BaseThreadInitThunk +
 0xd) [0x1611]
=========     Host Frame:C:\Windows\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x1
d) [0x764ad]
=========
========= Invalid __global__ read of size 4
=========     at 0x00000ae8 in d:\\projects-genn\\withstdprule\\12\\thousandhhhi
r2model_code\/synapseKrnl.cc:148:learnSynapsesPost(float)
=========     by thread (102,0,0) in block (7,0,0)
=========     Address 0x60052b334 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch tim
e
=========     Host Frame:C:\Windows\system32\nvcuda.dll (cuLaunchKernel + 0x19b)
 [0x8beb]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (_cudaInitManagedRuntime + 0x3ae2) [0x51c2]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (cudaLaunch + 0x105) [0x2d7b5]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (cudaLaunch<char> + 0x13) [0x15ae3]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__device_stub__Z17learnSynapsesPostf + 0x3c) [0x1535c]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (learnSynapsesPost + 0x15) [0x10b75]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (stepTimeGPU + 0x190) [0x11e00]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (main + 0x490) [0x15080]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__tmainCRTStartup + 0x136) [0x7a096]
=========     Host Frame:C:\Windows\system32\KERNEL32.DLL (BaseThreadInitThunk +
 0xd) [0x1611]
=========     Host Frame:C:\Windows\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x1
d) [0x764ad]
=========
========= Invalid __global__ read of size 4
=========     at 0x00000ae8 in d:\\projects-genn\\withstdprule\\12\\thousandhhhi
r2model_code\/synapseKrnl.cc:148:learnSynapsesPost(float)
=========     by thread (101,0,0) in block (7,0,0)
=========     Address 0x60052b330 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch tim
e
=========     Host Frame:C:\Windows\system32\nvcuda.dll (cuLaunchKernel + 0x19b)
 [0x8beb]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (_cudaInitManagedRuntime + 0x3ae2) [0x51c2]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (cudaLaunch + 0x105) [0x2d7b5]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (cudaLaunch<char> + 0x13) [0x15ae3]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__device_stub__Z17learnSynapsesPostf + 0x3c) [0x1535c]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (learnSynapsesPost + 0x15) [0x10b75]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (stepTimeGPU + 0x190) [0x11e00]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (main + 0x490) [0x15080]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__tmainCRTStartup + 0x136) [0x7a096]
=========     Host Frame:C:\Windows\system32\KERNEL32.DLL (BaseThreadInitThunk +
 0xd) [0x1611]
=========     Host Frame:C:\Windows\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x1
d) [0x764ad]
=========
========= Invalid __global__ read of size 4
=========     at 0x00000ae8 in d:\\projects-genn\\withstdprule\\12\\thousandhhhi
r2model_code\/synapseKrnl.cc:148:learnSynapsesPost(float)
=========     by thread (100,0,0) in block (7,0,0)
=========     Address 0x60052b32c is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch tim
e
=========     Host Frame:C:\Windows\system32\nvcuda.dll (cuLaunchKernel + 0x19b)
 [0x8beb]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (_cudaInitManagedRuntime + 0x3ae2) [0x51c2]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (cudaLaunch + 0x105) [0x2d7b5]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (cudaLaunch<char> + 0x13) [0x15ae3]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__device_stub__Z17learnSynapsesPostf + 0x3c) [0x1535c]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (learnSynapsesPost + 0x15) [0x10b75]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (stepTimeGPU + 0x190) [0x11e00]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (main + 0x490) [0x15080]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__tmainCRTStartup + 0x136) [0x7a096]
=========     Host Frame:C:\Windows\system32\KERNEL32.DLL (BaseThreadInitThunk +
 0xd) [0x1611]
=========     Host Frame:C:\Windows\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x1
d) [0x764ad]
=========
========= Invalid __global__ read of size 4
=========     at 0x00000ae8 in d:\\projects-genn\\withstdprule\\12\\thousandhhhi
r2model_code\/synapseKrnl.cc:148:learnSynapsesPost(float)
=========     by thread (99,0,0) in block (7,0,0)
=========     Address 0x60052b328 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch tim
e
=========     Host Frame:C:\Windows\system32\nvcuda.dll (cuLaunchKernel + 0x19b)
 [0x8beb]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (_cudaInitManagedRuntime + 0x3ae2) [0x51c2]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (cudaLaunch + 0x105) [0x2d7b5]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (cudaLaunch<char> + 0x13) [0x15ae3]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__device_stub__Z17learnSynapsesPostf + 0x3c) [0x1535c]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (learnSynapsesPost + 0x15) [0x10b75]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (stepTimeGPU + 0x190) [0x11e00]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (main + 0x490) [0x15080]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__tmainCRTStartup + 0x136) [0x7a096]
=========     Host Frame:C:\Windows\system32\KERNEL32.DLL (BaseThreadInitThunk +
 0xd) [0x1611]
=========     Host Frame:C:\Windows\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x1
d) [0x764ad]
=========
========= Invalid __global__ read of size 4
=========     at 0x00000ae8 in d:\\projects-genn\\withstdprule\\12\\thousandhhhi
r2model_code\/synapseKrnl.cc:148:learnSynapsesPost(float)
=========     by thread (98,0,0) in block (7,0,0)
=========     Address 0x60052b324 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch tim
e
=========     Host Frame:C:\Windows\system32\nvcuda.dll (cuLaunchKernel + 0x19b)
 [0x8beb]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (_cudaInitManagedRuntime + 0x3ae2) [0x51c2]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (cudaLaunch + 0x105) [0x2d7b5]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (cudaLaunch<char> + 0x13) [0x15ae3]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__device_stub__Z17learnSynapsesPostf + 0x3c) [0x1535c]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (learnSynapsesPost + 0x15) [0x10b75]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (stepTimeGPU + 0x190) [0x11e00]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (main + 0x490) [0x15080]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__tmainCRTStartup + 0x136) [0x7a096]
=========     Host Frame:C:\Windows\system32\KERNEL32.DLL (BaseThreadInitThunk +
 0xd) [0x1611]
=========     Host Frame:C:\Windows\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x1
d) [0x764ad]
=========
========= Invalid __global__ read of size 4
=========     at 0x00000ae8 in d:\\projects-genn\\withstdprule\\12\\thousandhhhi
r2model_code\/synapseKrnl.cc:148:learnSynapsesPost(float)
=========     by thread (97,0,0) in block (7,0,0)
=========     Address 0x60052b320 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch tim
e
=========     Host Frame:C:\Windows\system32\nvcuda.dll (cuLaunchKernel + 0x19b)
 [0x8beb]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (_cudaInitManagedRuntime + 0x3ae2) [0x51c2]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (cudaLaunch + 0x105) [0x2d7b5]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (cudaLaunch<char> + 0x13) [0x15ae3]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__device_stub__Z17learnSynapsesPostf + 0x3c) [0x1535c]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (learnSynapsesPost + 0x15) [0x10b75]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (stepTimeGPU + 0x190) [0x11e00]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (main + 0x490) [0x15080]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__tmainCRTStartup + 0x136) [0x7a096]
=========     Host Frame:C:\Windows\system32\KERNEL32.DLL (BaseThreadInitThunk +
 0xd) [0x1611]
=========     Host Frame:C:\Windows\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x1
d) [0x764ad]
=========
========= Invalid __global__ read of size 4
=========     at 0x00000ae8 in d:\\projects-genn\\withstdprule\\12\\thousandhhhi
r2model_code\/synapseKrnl.cc:148:learnSynapsesPost(float)
=========     by thread (96,0,0) in block (7,0,0)
=========     Address 0x60052b31c is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch tim
e
=========     Host Frame:C:\Windows\system32\nvcuda.dll (cuLaunchKernel + 0x19b)
 [0x8beb]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (_cudaInitManagedRuntime + 0x3ae2) [0x51c2]
=========     Host Frame:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
\bin\cudart64_75.dll (cudaLaunch + 0x105) [0x2d7b5]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (cudaLaunch<char> + 0x13) [0x15ae3]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__device_stub__Z17learnSynapsesPostf + 0x3c) [0x1535c]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (learnSynapsesPost + 0x15) [0x10b75]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (stepTimeGPU + 0x190) [0x11e00]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (main + 0x490) [0x15080]
=========     Host Frame:D:\Projects-genn\withSTDPRule\12\thousandHHHir2Simulati
on.exe (__tmainCRTStartup + 0x136) [0x7a096]
=========     Host Frame:C:\Windows\system32\KERNEL32.DLL (BaseThreadInitThunk +
 0xd) [0x1611]
=========     Host Frame:C:\Windows\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x1
d) [0x764ad]
=========
========= ERROR SUMMARY: 8 errors```

**Comment by tnowotny** [comment]
I am not sure what is going on here and it's hard to debug this without access to the full code. @jamesturner246 , unless you have other ideas, maybe @fereshtehvosta can share his entire code/data and we can have a quick look at it on our own systems?

**Comment by jamesturner246** [comment]
Sure. I'm on a plane tomorrow 10:00 AM (GMT), but I'll check on the way
if you submit your code before then.

James.

**Comment by jamesturner246** [comment]
Hi again.

I was unable to test on my flight yesterday, due to an unknown identifier `MATINP`. I assume it's a macro, as it's in caps, but what is it defined as? Preferably give all source files, so everything is defined as it is in your source tree.

Thanks,
James.

**Comment by jamesturner246** [comment]
OK, I jury-rigged those small errors, but am getting more serious ones, since it's apparent that you're using a quite old version of GeNN, which I don't have set up on this rig. It would be helpful if you updated to the newest version of GeNN, so we're both on the same page.

**Comment by jamesturner246** [comment]
Hi. I will look again tomorrow when I fly back home. If you give me the value of `MATINP`, as well as any other source files you haven't already given, I will update your code to work on the latest GeNN version. Please respond with any remaining source files and macro definitions by about 15 hours time...

I strongly encourage you to update to the latest version of GeNN, via the 'releases' page, since quite a lot has changed since the version which you are apparently using.

**Comment by fereshtehvosta** [comment]
Hi
i receive your mail recently..
"i want to give external noise to some of neurons in my network and
for this i used MATINP and in the .cu file i choose 50 random neurons
and give External noise with specific amount to them."
i attach all of data and file. I run my program just with this file
and there isn't any other file which i forget this to give you.
Thank for your regard
