### ISSUE TITLE
atomicAdd is causing problems in CUDA 8

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#107]
There is an issue with our user-defined atomicAdd for double precision and the NVIDIA provided atomicAdd for double precision in CUDA 8. 
This is the same as http://stackoverflow.com/questions/37566987/cuda-atomicadd-for-doubles-definition-error
I have now implemented the NVIDIA - recommended workaround in the branch fixAtomicAdd. @jamesturner246 can you please test this on your machine and on Windows?
On my sm30 GPU on Mac it seems to work but that is CUDA 7.5, which is non-indicative.

**Comment by mstimberg** [comment]
The changes in `fixAtomicAdd` indeed make it work for me (Linux with sm50 on CUDA 8.0).

**Comment by tnowotny** [comment]
Great. I made one more tweak for the case CUDA version < 8 but sm version > sm60 ... but this should do it now for all cases.

**Comment by mstimberg** [comment]
> I made one more tweak for the case CUDA version < 8 but sm version > sm60 ... but this should do it now for all cases.

Isn't CUDA 8 the first CUDA version that supports sm60? Either way, it's still working for me :)

**Comment by tnowotny** [comment]
possibly you are right but I didn't want to take any chances.
thanks for confirming.

**Comment by jamesturner246** [comment]
This is related to the previous issue #93. 

I have tested on my Linux box, and will test on Windows soon, but the more important machines to test will likely be those owned by @esinyavuz and @hdinkelbach (see #93), since those were the machines that were experiencing the issue previously.

It's confirmed working on my box, meanwhile.

**Comment by esinyavuz** [comment]
The fix on the development branch related to #93 works on my machine, but I am using an older CUDA version. Do we now have double solutions for this issue on two branches then? I can install v.8 next week and test the new branch if you want.

**Comment by jamesturner246** [comment]
Thomas made a fix in a new branch called fixAtomicAdd. Could you give that a go? Doesn't have to be the newest CUDA, but can't hurt testing both. Long aas it's the fixAtomicAdd branch. 

Cheers!

**Comment by esinyavuz** [comment]
No problem! I have pulled fixAtomicAdd branch and ran MBody1 example in double precision and the resulting spike counts are as expected, so it looks like it works.

**Comment by tnowotny** [comment]
I have now merged the solution into master. I will delete the fixAtomicAdd branch in a couple of days time.
