### ISSUE TITLE
Additional include arguments for Windows

### ISSUE THREAD

**Issue by mstimberg** [genn-team/genn#110]
For Brian2GeNN, we need to pass additional include directories to the compiler call.

For Linux/OS-X, we set `INCLUDE_FLAGS` and `makefile_common_gnu.mk` then uses `+=` to append to this variable.

On Windows, we were setting an `EXTRA_INCLUDES` variable but it seems that @jamesturner246 's commit 7be0298 removed its use in `makefile_common_win.mk` (not sure whether intentional or by accident) and since the Windows makefile defines `INCLUDE_FLAGS` from scratch, I don't see how we can pass additional arguments.

Any suggestions? Thanks!

**Comment by jamesturner246** [comment]
My mistake. In the latest dev commit, makefile_common_win.mk now appends to INCLUDE_FLAGS and LINK_FLAGS, rather than overwriting them completely. Should work now.

**Comment by mstimberg** [comment]
Many thanks, works like a charm!
