### ISSUE TITLE
Synaptic delays

### ISSUE THREAD

**Issue by PabloGN** [genn-team/genn#111]
The ways I have found to implement synaptic delays are:

1. Add a new synapse population with each delay: model.addSynapsePopulation
2. Define a postSynModel to create a model of the synaptic dynamics.

I would like to define a network with a spatial structure through the delays. The first one multiplies the number of layers and the other increases the complexity. Which should I choose?

Thank you.

**Comment by PabloGN** [comment]
OK, I should RTFM, #9 suggests the option 1. Do you have any new opinion about it?

**Comment by jamesturner246** [comment]
Option one is the way to go, for now. Having heterogeneous delay times within the same group means individual neurons' spikes are each saved in different and non-contiguous delay slots (bad for memory bandwidth).

In principle, this latency could be reduced by sorting the group by delay time, such that data destined for the same queue slot in memory form small but contiguous chunks. Perhaps we will look into this is future. But yes, option one for now!

**Comment by PabloGN** [comment]
Ok, thank you again!
