### ISSUE TITLE
Question: multi-GPU support timeline

### ISSUE THREAD

**Issue by Vafa-Andalibi** [genn-team/genn#112]
Hello, 

Do you have any timeline for Multi-GPU support? 

Thank you,

**Comment by tnowotny** [comment]
Hi - to be honest at the moment we are focusing on the release of brian2genn, which is imminent, and an OpenCL version is in development. Until we get additional personnel on the ground (anticipated for early in the new year) we will not be able to advance multi-GPU support. Realistically it will be later next year.
