### ISSUE TITLE
Izhikevich model integration and precision

### ISSUE THREAD

**Issue by spinang** [genn-team/genn#114]
Good morning,
I was working on a project which involved several neurons grouped in two populations. Both groups comprise a different number of neurons based on the Izhikevich model. During my tests, I noticed a mismatch between the way in which Izhikevich model is integrated and the way in which the same model is integrated by MATLAB.

For example, I have a model described by the following code:
```
#define DT 0.1
#include "C:\genn-team-genn-8cacb78\lib\include\modelSpec.cc"
#include "C:\genn-team-genn-8cacb78\lib\include\modelSpec.h"

void modelDefinition(NNmodel &model){
	initGeNN();
	
	// IZHIKEVICH MODEL WITH VARIABLE INPUT CURRENT
	neuronModel n;
	n.varNames.clear();
	n.varTypes.clear();
	n.varNames.push_back(tS("V"));
	n.varTypes.push_back(tS("scalar"));  
	n.varNames.push_back(tS("U"));
	n.varTypes.push_back(tS("scalar"));
	n.varNames.push_back(tS("Iext"));
	n.varTypes.push_back(tS("scalar"));
	n.varNames.push_back(tS("y"));
	n.varTypes.push_back(tS("scalar"));

	n.pNames.clear();
	//n.pNames.push_back(tS("Vspike"));
	n.pNames.push_back(tS("a")); // time scale of U
	n.pNames.push_back(tS("b")); // sensitivity of U
	n.pNames.push_back(tS("c")); // after-spike reset value of V
	n.pNames.push_back(tS("d")); // after-spike reset value of U
	n.dpNames.clear(); 
	//TODO: replace the resetting in the following with BRIAN-like threshold and resetting 
	n.simCode= tS("    if ($(V) >= 30.0){\n\
	  $(V)=$(c);\n\
		  $(U)+=$(d);\n\
	} \n\
	$(V)+=0.5*(0.04*$(V)*$(V)+5.0*$(V)+140.0-$(U)+$(Iext) + $(Isyn))*DT; //at two times for numerical stability\n\
	$(V)+=0.5*(0.04*$(V)*$(V)+5.0*$(V)+140.0-$(U)+$(Iext) + $(Isyn))*DT;\n\
	$(U)+=$(a)*($(b)*$(V)-$(U))*DT;\n\
	$(y)=$(Isyn); \n\
	//if ($(V) > 30.0){   //keep this only for visualisation -- not really necessaary otherwise \n	\
	//  $(V)=30.0; \n\
	//}\n\
	");
	n.thresholdConditionCode = tS("$(V) >= 29.99");
	nModels.push_back(n);
	unsigned int IZHIKEVICH_VAR_INPUT = nModels.size() - 1;
	
	model.setName("IZHMODEL");
	
	double Params_Neuron[4]{
		0.02,					// 0 - a
		-0.1,					// 1 - b
		-55,					// 2 - c
		6						// 3 - d
	};
	
	double Init_Neuron[4]{
		-65,					// 0 - Membrane potential V
		-20,					// 1 - Recovery variable U
		0,						// 2 - External current Iext
		0						// 3 - Debug variable
	};
	
	model.addNeuronPopulation("Pop1",1,IZHIKEVICH_VAR_INPUT,Params_Neuron,Init_Neuron);
	model.finalize();
}
```
I tried to execute the same simCode in MATLAB, obtaining the function below:
```
function [] = IzhikevichModel(V0,U0,a,b,c,d,Iext,DT,SIM_TIME)
    for j = 1:size(Iext,2)
        V = V0;
        U = U0;
        Vt = V0;
        for time = DT:DT:SIM_TIME
            if (V >= 30.0)
                  V = c;
                  U = U + d;
            end
            V = V + (0.04*V*V+5.0*V+140.0-U+Iext(1,j))*DT;
            U = U +(a*b*V-U)*DT;
%             if (V > 30.0)
%                 V =30.0;
%             end
            Vt = [Vt;V];
        end
        plot(0:DT:SIM_TIME,Vt,'LineWidth',1)
        hold on
        title('MATLAB')
    end
end
```
Moreover, .cu file is:
```
#define SIMULATION_TIME 500

#include "izh.cc"
#include "IZHMODEL_CODE/runner.cc"
#include "C:\genn-team-genn-8cacb78\lib\include\hr_time.cpp"

int main(int argc, char ** argv)
{
	FILE *osf = fopen("output.txt","w");
	CStopWatch timer;
	
	timer.startTimer();
	allocateMem();
	initialize();
	
	IextPop1[0] = (argc >= 2) ? atof(argv[1]) : 10;
	pushPop1StateToDevice();
	
	for(double t = 0.0; t < SIMULATION_TIME; t+=DT){
		stepTimeGPU(DT);
		pullPop1StateFromDevice();
		
		fprintf(osf,"%f\t",t);
		fprintf(osf,"%f\t",IextPop1[0]);
		fprintf(osf,"%f\t",VPop1[0]);
		fprintf(osf,"%f\t\n",UPop1[0]);
	}
	fclose(osf);
	timer.stopTimer();
	
	cout << "The simulation time is: " << timer.getElapsedTime() << " seconds." << endl;
	
	return 0;
}
```
but even if they should be behaviorally equivalent, results are completely different. In particular, because I want to simulate a single Class 1 excitable neuron, its firing rate should be constant when it undergoes a constant external current... but results are far from being right.

[Neuron simulated in MATLAB](https://postimg.org/image/hyqkkkitr/)
[Neuron simulated in GeNN](https://postimg.org/image/bwixu2udr/)

**Comment by kernfel** [comment]
GeNN instruction: `$(U)+=$(a)*($(b)*$(V)-$(U))*DT;\n\`
Matlab instruction: `U = U +(a*b*V-U)*DT;`
Subtle bracket difference. :)

**Comment by jamesturner246** [comment]
As @kernfel points out, your Izhikevich code is incorrect. See the MATLAB program on http://www.izhikevich.org/publications/spikes.htm for the original code.

Also, when i pass the same parameters to MATLAB as you pass to the GeNN model, I get something completely different, resembling the GeNN result. Check the parameters you are passing to MATLAB are the same as the parameters you are passing to GeNN.

Also, I seriously recommend updating to the latest GeNN version 2.2.2, if you aren't already, since a number of important bugfixes have been applied recently.

**Comment by esinyavuz** [comment]
Another problem, as you have mentioned, is the precision. As far as I know, the behaviour of an Izhikevich neuron can be different when the precision is changed. If you want to reproduce published results, it is safer to stick to DT=1 ms or to check carefully what is the time step used in a particular model. You haven't mentioned the DT in your Matlab implementation, is it DT= 0.1 ms as it is in your GeNN implementation?

**Comment by spinang** [comment]
@kernfel you saved all my work, thanks a lot. Unfortunately, I'm very good in making stupid errors.
@esinyavuz Of course, DT is exactly equal in both files.
