### ISSUE TITLE
Second-order reaction-diffusion dynamical system

### ISSUE THREAD

**Issue by spinang** [genn-team/genn#117]
I'm very sorry to reopen again a closed issue, but I've noticed an error in the solution adopted in #115 .
If I consider only two coupled neurons like the model shows, I expect that phase shift between x_1 of neuron A and x_1 of neuron B is equal to 180°, but actually the proposed model behaves differently.

I report a plot obtained by using MATLAB which depicts how the trends should be: https://s30.postimg.org/4rydjit25/MATLAB.jpg
and another plot that shows what GeNN produces:
https://s30.postimg.org/t76lkkrz1/GENN.jpg

**Comment by tnowotny** [comment]
On this one we dropped the ball at the time and it is now out of date.
