### ISSUE TITLE
Support for -std=c++14 and later

### ISSUE THREAD

**Issue by whenov** [genn-team/genn#149]

**Comment by jamesturner246** [comment]
are you referring to C++14 features?

**Comment by whenov** [comment]
Yes. I was trying to use `make_unique`. It would be nice if user can use the full power of their compiler if they use a newer version of gcc.

**Comment by jamesturner246** [comment]
I know it's been a while, but, just in case you're still wondering, you can manually hack GeNN in the meantime. All you need to do is replace all occurrences of `-std=c++11` to `-std=c++14` to get what you want.

**Comment by neworderofjamie** [comment]
@whenov - not sure if you're still interested but #192 means that you can use whatever C++ standard you would like to build your simulator by setting ``CPP_STANDARD=c++14`` before you include makefile_common_gnu.mk - it's still not possible to use newer C++ features in models so I'm leaving this open

**Comment by whenov** [comment]
@neworderofjamie Thanks for your information!

**Comment by neworderofjamie** [comment]
Plan for final part of this:
1. Don't ``#include`` model (that was gross anyway), build it separately and link it (add an extern declaration somewhere)
2. Add a std parameter to genn-buildmodel.sh which gets passed through to make which uses it as C++ standard for building model

**NOTE** this doesn't effect Windows as VC++ just builds using whatever C++ standard it supports

**Comment by neworderofjamie** [comment]
Sadly 1. is not quite that simple - if you build model separately there's no easy way of accessing GENN_PREFERENCES global. For GeNN 4 will allow the standard which ``genn_generator`` (which is only one, small file to be built with a user-specified standard)
