### ISSUE TITLE
Testing script to see if everything works alright after a modification

### ISSUE THREAD

**Issue by esinyavuz** [genn-team/genn#17]

**Comment by esinyavuz** [comment]
There is now a bash script under userprojects, which test if the examples work on the CPU and the GPU , with new configuration or old configuration for comparison purposes. 

To run it, navigate to $GENN_PATH/userprojects, and call testprojects.sh as
`bash testprojects.sh "what is new in this run" 2>&1 |tee outputtestscript`

This works under Linux and MAC.

**Comment by tnowotny** [comment]
... and we have feature tests.
