### ISSUE TITLE
Any update about multi-gpu GeNN? 

### ISSUE THREAD

**Issue by Vafa-Andalibi** [genn-team/genn#210]

**Comment by neworderofjamie** [comment]
First of all, apologies for the delay in responding to this, I have been on holiday. 

I'm afraid we haven't done any work in this direction as most of the models we work with can be easily simulated on a single GPU. What exactly are you trying to achieve?

**Comment by Vafa-Andalibi** [comment]
I'm one of the authors of [CxSystem](https://cxsystem.readthedocs.io/en/master/) which is implemented on top of brian2 and therefore can be run using GeNN via Brian2GeNN. The simulations could have (at least) tens of thousand neurons with several million synapses. We have a beta cluster support in CxSystem but as you know since Brian2 doesn't support parallelism using MPI, so the best we can achieve is to run a batch of simulations on cluster. However, if GeNN could support multi-GPU, we could run the simulations on nodes that have several GPUs installed on them and improve the runtime of a single simulation as well.

**Comment by neworderofjamie** [comment]
Nice - that looks like a cool project! On a HPC GPU GeNN can simulate 10^8 of millions of synapses and 10^6 neurons so you still have quite a bit of headroom although, as you say, multiple GPUs could improve runtime.

Multi-GPU support is definitely on our wish-list so I'll leave this open as a feature request.

**Comment by Vafa-Andalibi** [comment]
Could you please elaborate on HPC GPU GeNN? I couldn't find anything in the documentation.
