### ISSUE TITLE
Numerous warnings for variables declared but never referenced when running testprojects.sh

### ISSUE THREAD

**Issue by amwhatley** [genn-team/genn#220]
...for example as follows:

"/usr/local/cuda/bin/nvcc" -cubin -x cu -arch sm_52  -O3 -use_fast_math -std=c++11 -I"$GENN_PATH/lib/include" -o "/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/runner.cubin" "/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/runner.cc"
/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/neuronKrnl.cc(46): warning: variable "lsT" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/neuronKrnl.cc(147): warning: variable "lsT" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseKrnl.cc(18): warning: variable "addtoinSyn" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/neuronFnct.cc(27): warning: variable "lsT" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/neuronFnct.cc(103): warning: variable "lsT" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseFnct.cc(22): warning: variable "addtoinSyn" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseFnct.cc(36): warning: variable "addtoinSyn" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseFnct.cc(61): warning: variable "addtoinSyn" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseFnct.cc(75): warning: variable "addtoinSyn" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseFnct.cc(88): warning: variable "addtoinSyn" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/neuronKrnl.cc(46): warning: variable "lsT" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/neuronKrnl.cc(147): warning: variable "lsT" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseKrnl.cc(18): warning: variable "addtoinSyn" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/neuronFnct.cc(27): warning: variable "lsT" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/neuronFnct.cc(103): warning: variable "lsT" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseFnct.cc(22): warning: variable "addtoinSyn" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseFnct.cc(36): warning: variable "addtoinSyn" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseFnct.cc(61): warning: variable "addtoinSyn" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseFnct.cc(75): warning: variable "addtoinSyn" was declared but never referenced

/home/amw/GeNN/userproject/MBody1_project/model/MBody1_CODE/synapseFnct.cc(88): warning: variable "addtoinSyn" was declared but never referenced

**Comment by neworderofjamie** [comment]
Yep! Sadly the code GeNN generates does still include a fair number of unused variables - this is something that we intend to improve in our upcoming code-generator refactor #47

**Comment by neworderofjamie** [comment]
Closing as an example of #47
