### ISSUE TITLE
testprojects.sh fails on first run due to absence of MBody1/testing_output directory

### ISSUE THREAD

**Issue by amwhatley** [genn-team/genn#222]
cp: cannot create regular file '/home/amw/GeNN/userproject/refProjFiles/MBody1/testing_output/testing.time': No such file or directory

**Comment by neworderofjamie** [comment]
This works for me (after deleting ``userproject/refProjFiles`` and ``userproject/MBody1/testing_output``) - can you attach the standard out when it failed?

**Comment by amwhatley** [comment]
[genn-bug222.txt](https://github.com/genn-team/genn/files/2779801/genn-bug222.txt)

**Comment by neworderofjamie** [comment]
@tnowotny - this script is somewhat before my time - any thoughts on what it's **supposed** to do?

**Comment by tnowotny** [comment]
It is supposed to run the userprojects and if they'd been run before do some basic comparisons to the previous runs. It was designed by @esinyavuz . Not quite sure what has changed that it is now failing at such a basic step. I can have a look.
As we have a completely separate testing suite in place now, I wonder whether we need to either update this to pull it into that testing framework or deprecate it in a future version.

**Comment by neworderofjamie** [comment]
I was thinking it could be worth running the userprojects from Jenkins and deprecating this - my only concern is that the automatic tests already take an eternity and this probably wouldn't help :smile:

**Comment by tnowotny** [comment]
Ah - I see from the posted cerr output shows that it fails when trying to compare to the previous run (refProjFiles).

I think running a few userprojects from jenkins is a good idea. We could keep it fairly minimal in terms of simulated time etc in order not to end up with day long test runs. The we can deprecate this.

**Comment by neworderofjamie** [comment]
:+1: I have raised a new issue #226 laying out the way forward

**Comment by amwhatley** [comment]
So that's very nice for the future, but what should be changed now to prevent users from tripping over this in the meantime?

**Comment by esinyavuz** [comment]
Meanwhile you can set `firstrun=true` at line 22, and it would create the directories and run the rest of the code (assuming the rest of the code is not deprecated).

**Comment by amwhatley** [comment]
So isn't that how testprojects.sh should be delivered fresh out of the zip file or out of the repository? With `firstrun=true`?

I guess it doesn't matter so much now the whole script is being deprecated and mention of it removed from the 'Installation' instructions.

**Comment by esinyavuz** [comment]
Actually it should create the necessary directories the first time you run it even though this flag is not changed. If the script didn't run properly the first time, the directories are not deleted though (as mentioned in #77). This may be the reason. 
It is quite an old script and looks mostly deprecated anyway. It was first designed as an internal tool to check that all the example projects run without a problem, and that changes to code doesn't change results or slow down execution. We didn't have jenkins tests by then. Now that there are other tools available, the whole thing can be deprecated and removed from installation instructions.

**Comment by amwhatley** [comment]
Well, I'm happy now anyway. Thanks for your very prompt help.
