### ISSUE TITLE
No proper install

### ISSUE THREAD

**Issue by amwhatley** [genn-team/genn#225]
The installation instructions do not really describe an 'installation' in the usual sense of the word, merely an unpacking into 'a convenient location', but then goes on to talk about the software being 'installed' into /usr/local/GeNN. I tried reading between the lines and installing it as root under /usr/local, which of course assumes the ability to install as root, but running the installation test as a normal user then fails as it tries to write into the directory it was installed in. It became clear that GeNN is not actually designed to be installed in the conventional sense, but to be used is situ wherever it is unpacked, and that that will need to be done separately by each user on a machine.

At the very least the so-called installation instructions at http://genn-team.github.io/genn/documentation/3/html/Installation.html are misleadingly named, and contain misleading advice.

The better fix would be to create a proper install target in the makefile such that the software can be installed using the traditional `make; sudo make install` steps, together with fixing the test framework so that it does not necessarily try to put its output where the source is.

**Comment by neworderofjamie** [comment]
This is definitely an issue other people have found and is something we're looking into improving. GeNN is indeed currently intended to used in situ and ``/usr/local/GeNN`` is indeed a terrible 'example' of a 'convenient location' (I will change that now)
