### ISSUE TITLE
When invoked as documented under Testing Your Installation, testprojects.sh produces an error

### ISSUE THREAD

**Issue by amwhatley** [genn-team/genn#228]
Under **Testing Your Installation** at the bottom of http://genn-team.github.io/genn/documentation/3/html/Installation.html, the user is instructed to invoke testprojects.sh as follows: 

> cd $GENN_PATH/userproject && ./testprojects.sh

i.e. without the `2>&1|tee -a outputtestscript` that is described in the comments at the head of testprojects.sh itself. Thus, at the very end of the script, the `cp outputtestscript $FILE` fails and emits the error

> cp: cannot stat 'outputtestscript': No such file or directory

**Comment by neworderofjamie** [comment]
I have removed those instructions entirely - I've never run that script before and I don't think it's really helpful for other end users to do so either.

**Comment by neworderofjamie** [comment]
Glad to hear you have run the tests successfully though - I look forward to being annoyed by your feedback on actually using GeNN!

**Comment by neworderofjamie** [comment]
Instructions removed in #224, will be properly addressed in future by #226
