### ISSUE TITLE
Read the docs

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/genn#230]
GeNN's doxygen-based documentation is currently deployed to a github page whenever there's a release. However this means:
1. We only have online documentation for the latest release of each major version (i.e. currently 3.2.0 and 2.2.3)
2. Documentation for master isn't currently available pre-built.

The best solution to this would be to use a service like [Read the Docs](https://readthedocs.org/) to automatically build documentation using a github webhook. However read the docs is designed for Sphinx (Python documentation tool) so a process like https://breathe.readthedocs.io/en/latest/readthedocs.html would be required.

**Comment by tmnnt** [comment]
I am solving trying to solve this

**Comment by neworderofjamie** [comment]
I guess the first step would be to register with https://readthedocs.org/ and figure out how the service works (I've never actually used it before). Then fork the GeNN repository and figure out how to apply the process described in that link to GeNN's doxygen configuration (currently triggered with the ``makedoc`` script).

**Comment by tmnnt** [comment]
Awesome! I'll try exploring Read the docs.
Thanks for that input.

**Comment by Vigneswaran-Chandrasekaran** [comment]
Hi all, I went through the links mentioned above. I figured how the process works and it looks quite handy. It would be great if I know the steps to proceed further to complete this work.

**Comment by neworderofjamie** [comment]
Great! What exactly do you need to do?

**Comment by Vigneswaran-Chandrasekaran** [comment]
> Great! What exactly do you need to know?

I am really sorry for the late reply, summer holidays carried away. As you mentioned, the usage of `breathe` is pretty elegant here. The process involve `Sphinx quickstart` to create the empty project tree with all neccessary files along with `conf.py`, which configures the way `Sphinx` reads the project. Then we need to generate `doxygen xml` files,  which will be added to the `Sphinx_build` process using `breate` (thus in `READTHEDOCS`).  Can I start with doing the bare-minimum entities by only adding `doxygen` files to `Sphinx_build`and create a PR? And sequntially  custoize various other things need to be done for `READTHEDOCS`.

**Comment by neworderofjamie** [comment]
No need to apologise - glad you're still interested! That approach sounds sensible and will also allow me to register with readthedocs etc based on the initial setup.
