### ISSUE TITLE
Issue with latest release

### ISSUE THREAD

**Issue by shardulparab97** [genn-team/genn#231]
I just wanted to point out an issue with the latest release:
Facing the following error when when testing the latest release when running:
cd $GENN_PATH/userproject && ./testprojects.sh

```
generate_run.cc: In function ‘int main(int, char**)’:
generate_run.cc:107:43: error: ‘modelName’ was not declared in this scope
   cmd += " && make clean all SIM_CODE=" + modelName + "_CODE";
                                           ^~~~~~~~~
```

**Comment by neworderofjamie** [comment]
Thank you for reporting this. This (#223) has actually recently been fixed in master
