### ISSUE TITLE
Is this the right place to ask questions?

### ISSUE THREAD

**Issue by swami74** [genn-team/genn#240]
I've installed GeNN (by cloning the repository), Brian2 and Brian2Genn according to the instructions, but when I try to run a simple simulation, I get errors in the code generation step. I am a new user, and not nearly knowledgeable enough (yet) to distinguish between user errors and genuine issues with GeNN. So before I post details of the error messages I see, I thought I'd ask if this is the right place to ask "newbie" questions. If it is not, could someone please point me to the right place? 

Thanks.

**Comment by neworderofjamie** [comment]
For Brian2GeNN issues, https://github.com/brian-team/brian2genn is the correct place to ask questions
