### ISSUE TITLE
general index into GeNN variables

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#257]
When we created GeNN, there was a conscious decision to have variables with meaningful names, e.g. V, m, h, n, etc instead of v[0], v[1], v[2], ...
However, at times it would be really nice to just iterate over all variables, e.g. write them all to disk, or initialise them in a loop etc.
Should we just automatically generate a C array of pointers into the variables to help with this?
E.g.
```SET_VARS({{"V", "scalar"},{"m", "scalar"},{"h","scalar"},{"NA","scalar"},{"NB","scalar"}})```
```model.addNeuronPopulation<model>("POP1", ...);```
would currently create
```scalar *VPOP1, *mPOP1, ...```
The suggestion would be to also create
```void *_vPOP1[];```
where ```_vPOP1[0]= VPOP1```, ```_vPOP1[1]= mPOP1``` etc.
@neworderofjamie , does this make any sense at all?

**Comment by tnowotny** [comment]
we can continue discussion offline - I am not entirely sure I understand how the 'shared library model approach' relates to this ... but I don't think I am aware of the details of this approach at all ;-)

**Comment by neworderofjamie** [comment]
Sure! :+1:
