### ISSUE TITLE
Brunel, VA implemenetations

### ISSUE THREAD

**Issue by nkyriazis** [genn-team/genn#264]
While trying to understand how to implement Brunel and Vogels-Abbott with genn I consulted https://github.com/nasiryahm/SNNSimulatorComparison (e.g. https://github.com/nasiryahm/SNNSimulatorComparison/tree/master/Benchmarks/Brunel/genn).

However, these samples are based on an earlier version of genn (3.3.0). Is there a significant difference in performance between that version and latest to justify porting the samples? I was hoping that a quick look from the devs would quickly point out what needs to change for the port to be successful.

Despite my efforts to port and consult documentation I can't seem to get past the following error in the Brunel model:

`The variables addtoinSyn, updatelinsyn were undefined in code EE : simCode`

**Comment by neworderofjamie** [comment]
I'm sure @nasiryahm would appreciate a pull request with an update! From looking very briefly at the code, things that have changed are:

In model.cc:
1. "$(addtoinSyn) = $(g);\n 
         $(updatelinsyn);\n"
    has been simplified to simply ``"$(addToInSyn, $(g));"``
2. ``initGeNN();`` and ``model.finalize()`` calls are no longer required.
3. Device initialization is now the default - the setting of GENN_PREFERENCES at the beginning is no longer required, nor are the calls to ``setSpikeVarMode``
4. ``BoBRobotics::GeNNModels::LIF`` is now included in GeNN as ``NeuronModels::LIF``
5. ``SynapseMatrixType::RAGGED_INDIVIDUALG`` is now called ``SynapseMatrixType::SPARSE_INDIVIDUALG``

In simulator.cc
1. The second initialize function e.g. ``initva_benchmark`` is now called ``initializeSparse``.
2. ``#ifdef CPU_ONLY`` logic is no longer required - you can just go:
    ```c++
    stepTime();
    if (!fast) pullECurrentSpikesFromDevice();
    ```
    and it will work with all backends.

But there should be no difference in performance between GeNN 3.3.0 and GeNN 4.0.X - just streamlining.

**Comment by nkyriazis** [comment]
Thank you for your prompt and detailed answer. I'll return with feedback.

**Comment by nkyriazis** [comment]
I'm considering this resolved on my side. I could re-open if issues occur.

**Comment by nasiryahm** [comment]
Thanks for the shoutout @neworderofjamie -- pull request on this would indeed be appreciated. Either way, Jamie's instructions are detailed enough that I can make use of them. Cheers.
