### ISSUE TITLE
Dynamically sized network

### ISSUE THREAD

**Issue by nkyriazis** [genn-team/genn#265]
My current understanding is that sizes (and other variables) must be baked in the generated code, which means that for new sizes re-compilation is required.

Does this correctly reflect the situation? Is there a workaround or guideline?

Example: I want to separate the type of network from its size and select size at runtime.

**Comment by neworderofjamie** [comment]
If you mark variables as unintialised in the model description you can then set them from command line arguments/files in the simulation code but, as you say, sizes are always hard-coded into the generated model. If we want to be able to easily deploy models of different sizes, one thing we often do is generate a header file with sizes (using bash, c++, python whatever) which we then include in the model and simulation code. Several of the 'user projects' that come with GeNN do this e.g. https://github.com/genn-team/genn/blob/master/userproject/Izh_sparse_project/generate_run.cc
