### ISSUE TITLE
Number of synapses at simulation time

### ISSUE THREAD

**Issue by nkyriazis** [genn-team/genn#268]
How can one get the total number of synapses at simulation time for a model with automatically initialized synapses?

**Comment by neworderofjamie** [comment]
I'm afraid there's not a trivial way of doing that. Assuming you're using sparse connectivity, what you essentially need to do is:

1. Call ``pulllXXXConnectivityFromDevice()`` for eachy synapse group in your model where ``XXX`` is the name of the synapse group
2. Count the synapses in each population with something like ``std::accumulate(&rowLengthXXX[0], &rowLengthXXX[YYY]``, 0);`` where ``XXX`` is the name of the synapse group and ``YYY`` is the number of neurons in the presynaptic population
3. Add these numbers together.

Hope that's helpful!

**Comment by nkyriazis** [comment]
I understand.

I'm working with version 3.3.0 and I see no length-relevant entries in the definitions file. Do I need to issue a special flag?

**Comment by neworderofjamie** [comment]
Ahh ok, any particular reason not to upgrade?

This functionality wasn't exposed in GeNN 3.3.0 so you need to replace step 1 with your own CUDA code:
```c++
#ifndef CPU_ONLY
 extern unsigned int *d_rowLengthXXX;
CHECK_CUDA_ERRORS(cudaMemcpy(CXXXrowLength, d_rowLengthXXX, YYY * sizeof(unsigned int), cudaMemcpyDeviceToHost));
#endif
```c++
(where, again, ```XXX`` is the name of the synapse group, ``YYY`` is the number of neurons in the presynaptic population and assuming you are using ``RAGGED`` format for your connectivity)

**Comment by nkyriazis** [comment]
I'm too deep into a path to upgrade.

Your solution works as expected! Thanks!
