### ISSUE TITLE
Need to upgrade version of gtest

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/genn#284]
Current version uses pre-c++11 tr1 stuff that deeply pains Visual Studio 2019 unless ``_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING`` is defined everywhere.

**Comment by 9inpachi** [comment]
Hi,I will start looking into this. Seems like something held up by Visual Studio for a long time.

**Comment by neworderofjamie** [comment]
Hah, I'm afraid this one's totally on us. Our Jenkins file currently pulls in an old release of gtest that uses ancient pre-c++11 libraries
