### ISSUE TITLE
If a user tries to use double precision but the device does not support it, the run fails rather than either warning or trying to demote everything

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#29]
We need to have a look at this - maybe it's not that urgent as most devices now do support double precision. See corresponding issue 18 in brian2genn as well.

**Comment by esinyavuz** [comment]
@tnowotny, If sm < 1.3, maybe we can simply make a typedef to redefine double as float? Or we can leave it as it is as old sm versions will not be supported by new CUDA versions.

**Comment by tnowotny** [comment]
I guess throwing a warning and then trying a redefinition might be one way forward - but in a sense it might be more honest and avoiding any confusion on what has actually run to warn and abort. The users can decide to change things to float or find themselves a newer GPU?

**Comment by shailesh210** [comment]
I am a newbie and trying to help fix this bug. Would it be okay to simply give an Error message and exit or do I need to do something else?
Thanks

**Comment by tnowotny** [comment]
Hi shalesh210,
an informative error message and exit may be a good start. Longer term one could think of a warning followed by an automatic demotion of the model precision to single precision floating point; however there would also be downsides to this - users might miss the warning and then take the SP float results as being DP.

**Comment by tnowotny** [comment]
fixed.
