### ISSUE TITLE
padSumSynapseTrgN etc.

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#30]
We define these (sumSynapseTrgN, padSumSynapseTrgN, padSumSynapseKrnl) in what used to be called NNmodel::initDerivedSynapsePara, but is now renamed to NNmodel::registerSynapsePopulation. However, these don't seem to be used anywhere? If they are not necessary any more we should remove them.

**Comment by esinyavuz** [comment]
padSumSynapseKrnl is used but not the other ones. This is fixed in the development branch now.
