### ISSUE TITLE
Colab is crashing when I implemented a small experiment to demonstrate Hebbian Learning Rule

### ISSUE THREAD

**Issue by AdityaKapoor74** [genn-team/genn#309]
I have tried to implement a small piece of code with a population of 40 (pre_synaptic_neurons,post_synaptic_neurons and 2 sets of Poisson population). When I run the last code cell of the notebook, the session restarts. I suspect the error is in synaptic connections between the neuronal population. I am putting the colab link in here so that y'all can have a look at the code. Any kind of help will be appreciated.

Colab link: https://colab.research.google.com/drive/1ftUZKQe5hA5d6JaS1IfGKxQSBsTAceau

**Comment by neworderofjamie** [comment]
Just needed the collab runtime setting to GPU
