### ISSUE TITLE
Behaviour of $(sT_pre) and $(sT_post) is not ideal

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/genn#314]
In some event-driven learning rules, you want to be able to calculate ``$(t) - $(sT_pre)`` in the presynaptic spike-driven sim_code. However, currently ``$(sT_pre)`` gets set in the neuron kernel so essentially refers to the current spike being processed in the sim_code i.e. it'll always be ``$(t) - DT``.  The only current solution is to add an extra per-synapse variable to track the time of the last pre spike but this is very wasteful of memory and innefficient. When these variables **should** get updated needs more thought!

**Comment by neworderofjamie** [comment]
While, if using presynaptic parallelism, updating $(sT_pre) could be added at the end, all other cases probably need an additional kernel. Implementation could be an additional virtual on ``WeightUpdateModel::Base`` like ``isPrevPreSpikeTimeRequired``

**Comment by tnowotny** [comment]
naively (can't fully recollect the order of things) but is this not a case where neurons could register whether they are spiking or not in some flag 'spiking' when the spike is first detected and then update sT only at the beginning of the next time step (resetting the "spiking" flag to false)?

**Comment by neworderofjamie** [comment]
Actually, that's a much better idea, maaaybe a flag isn't even required and the spike arrays from the previous time step can be re-used
