### ISSUE TITLE
Sparse connectivity with networks bigger than the block size is not supported for gpu sm < 2.0

### ISSUE THREAD

**Issue by esinyavuz** [genn-team/genn#33]
This is because atomicadd of floating types is not supported by older gpus.

I think of 3 workarounds:

1: provide an overloaded atomicAdd function for floats if sm < 2.0 (maybe in the longer run, this is not planned at the moment). Users who want this can implement their own methods, for an example see: https://devtalk.nvidia.com/default/topic/458062/atomicadd-float-float-atomicmul-float-float-/

Also considering issue #29, we can do one of the following:
2: warn users that their device may not support certain functionalities (this seems like the best option at the moment)

3: if we have more of this kind of issues, we may considering providing a GeNN functionality table/checklist for each gpu on the computer. Based on this and the user model, we can improve auto device selection.

**Comment by tnowotny** [comment]
We have now an atomicAdd function for floats on devices < 2.0 that do not support it natively. The bug should therefore be fixed, but tests are pending.

**Comment by esinyavuz** [comment]
We tested this on our machine with sm 1.3 and it works for both float and double precision now.
