### ISSUE TITLE
``push_extra_global_param_to_device`` method is counter-intuitive

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/genn#342]
The prototypes of these functions are currently:
```python
push_extra_global_param_to_device(self, egp_name, size=1):

push_extra_global_param_to_device(self, pop_name, egp_name, size=1)
```
in ``Group`` and ``GeNNModel`` respectively. While this matches the underlying C++ API, the default of 1 was a really bad idea as, if you leave out ``size``, the calls _look_ like ``push_var_to_device`` calls but are often incorrect as they only copy the first element of the extra global parameter array. The size is known in Python so either use that or remove the default entirely.

**Comment by tnowotny** [comment]
I would lean towards using the known egp array size as the default, if that is possible; that would do the right thing if users omit the parameter and yet users can still limit to a partial copy by giving an explicit value ...

**Comment by neworderofjamie** [comment]
agreed!
