### ISSUE TITLE
Strange RNG troubles

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#386]
I was defining a (somewhat unusual but I would have thought legal) post-synapse as follows:
```python
pass_postsyn = create_custom_postsynaptic_class(
    "pass_postsyn",
    param_names= ["noise_A"],
    apply_input_code="""
    $(Isyn)+= $(inSyn) + $(noise_A)*$(gennrand_normal);
    $(inSyn)= 0.0;
    """
)
```
and noticed a strange sinusoidal artefact on my post-synaptic neurons.
I then tried to debug and modified the generated code as follows (this is in the update neuron kernel - I commented out the Isyn line and added the printf line)
```c++
 double Isyn = 0;
             {
                // pull inSyn values in a coalesced access
                double linSyn = group->inSynInSyn0[lid];
                
                //Isyn+= linSyn + (1.00000000000000006e-01)*curand_normal_double(&group->rng[lid]);
		printf("%f ", curand_normal_double(&group->rng[lid]));
                linSyn= 0.0;
                
                
                group->inSynInSyn0[lid] = linSyn;
            }
```
and collected the printf output in a file that I then plotted.
It appears, all threads have the same random numbers and the numbers are not random but look like this as a function of time:
![image](https://user-images.githubusercontent.com/5477463/103350257-469acf80-4a97-11eb-9b0e-d8b8e37bd1a5.png)

I suspect it has something to do with lack of seeding/initialisation but cannot really make it out. I could understand that the lack of seeds would cause the numbers to be the same for all threads but I am not sure I understand why the numbers aren't really pseudo-random. How does seeding/initialisation get done normally?

**Comment by neworderofjamie** [comment]
That is an interesting one - I would also suspect a seeding issue due to it not 'noticing' rng calls in postsynaptic models or something. If the RNGs aren't seeded they will all probably be zeroed so in the same (invalid) state. Can you check whether the rngs are bwing seeded in init.cc

**Comment by neworderofjamie** [comment]
Just had a go at reproducing using 
```python
from pygenn import genn_model,genn_groups
pass_postsyn = genn_model.create_custom_postsynaptic_class(
    "pass_postsyn",
    param_names= ["noise_A"],
    apply_input_code="""
    printf("%u:%f\\n", $(id), $(gennrand_normal));
    """
)
model = genn_model.GeNNModel("double", "test")

pop1 = model.add_neuron_population("Pop1", 10, "LIF", {"C":1.0, "TauM": 10.0,"Vrest":-60.0,"Vreset":-60.0, "Vthresh":-50.0, "Ioffset":0.0, "TauRefrac":2.0}, {"V": -60.0, "RefracTime":0.0})
stim = model.add_neuron_population("Stim", 10.0, "SpikeSource", {}, {})

model.add_synapse_population("StimPop1", "SPARSE_GLOBALG", 0,
    stim, pop1,
    "StaticPulse", {}, {"g":1.0}, {}, {},
    pass_postsyn, {"noise_A":0.5}, {},
    genn_model.init_connectivity("OneToOne", {}))
model.build()
model.load()

for i in range(10):
    model.step_time()
```
and it **seems** to work fine (rough scatter plot of values emitted by each thread over 10 timesteps):
![Figure_2](https://user-images.githubusercontent.com/6793242/103369947-5fb97580-4ac3-11eb-9aaa-9af520107b59.png)

**Comment by tnowotny** [comment]
I have just invited you to the repo in question. If you use the check_postsyn_noise branch you should be able to reproduce  ... or if not there is an issue with the install on James T's machine ...

**Comment by tnowotny** [comment]
PS: The problem does not occur for SingleThreadedCPU.

**Comment by neworderofjamie** [comment]
Does the code I pasted work on that machine?

**Comment by tnowotny** [comment]
Yep, that code works fine ... mysterious. Am I doing something else wrong I wonder?
Or, is there a hidden place in your code that triggers rng initialisation that I don't have. I noticed, if the post-synaptic neurons also use an rng, everything is fine. Only when they don't there is a problem.

**Comment by tnowotny** [comment]
does my honeybee ORN code work for you?

**Comment by neworderofjamie** [comment]
It does not! The lack of genn-buildmodel -d in PyGeNN makes this a little trickier to debug than it would be in C++ but I'll have a look tomorrow.

**Comment by tnowotny** [comment]
As commented on the pull request #387 , this indeed seems to solve the problem ;-)
