### ISSUE TITLE
cannot use WeightUpdateModel StaticGraded 

### ISSUE THREAD

**Issue by TongChenGu** [genn-team/genn#397]
Using weightupdatemodels StaticGraded and compiling user code will get an error: synapseUpdate.cc(25): fatal error C1075: "{" : no matching tocken found.
I wonder if there is something wrong, and hope detailed information about examples using StaticGraded, thank u~

**Comment by neworderofjamie** [comment]
Hi @TongChenGu , sorry to hear you're having issues. Which model are you trying to build and using what backend i.e. CUDA or SingleThreadedCPU?

**Comment by TongChenGu** [comment]
> Hi @TongChenGu , sorry to hear you're having issues. Which model are you trying to build and using what backend i.e. CUDA or SingleThreadedCPU?

Thanks for replying to me. I'm trying to build graded synapse, so i tried a weightupdatemodel called StaticGraded, and set params and initialied vars according to user mannual.But when compiling user code, it raised an error.
Finally, sorry i forget to specify the backend i used. I use SingleThreadedCPU.

**Comment by neworderofjamie** [comment]
could you attach your model file?

**Comment by TongChenGu** [comment]
Hi. I find the answer.
I used an empty pre-synaptic neuron which has no membrane potential, where GeNN cannot generate proper code with graded synapse.
Thanks for your tolerance. Wish you all the best.

**Comment by neworderofjamie** [comment]
Ahh yes, that would explain it. Well done on figuring that one out!
