### ISSUE TITLE
Questions regarding PyGeNN

### ISSUE THREAD

**Issue by mariiapopova** [genn-team/genn#398]
Hello! My name is Mariia. I am modelling basal ganglia networks and I am interested in GeNN. I have a few questions regarding pygenn as working with genn through python would be the best for me. I've installed it successfully and looked through the tutorials.
1. Is it true that currently to create new model with new type of neurons I need to modify neuronModels.h object? Will there be a way to do it through pygenn later?
2. Am I right that every time I run pygenn program its C instance is recompiled. Is there any way to use the precompiled parts or versions?
3. Is there any way to run the pygenn code via IDE (like Spyder or VSC) because currently I am running them through Native Tools Command Prompt for Visual Studio.
Thank you a lot!

**Comment by neworderofjamie** [comment]
Hi Mariia, thanks for your interest in PyGeNN and I'm glad you got everything successfully installed. In answer to your questions:

1. You definitely don't need to modify neuronModels.h to add new models, in Python you can do this from your script using the syntax shown in [the documentation](http://genn-team.github.io/genn/documentation/4/html/de/ded/sectNeuronModels.html#sect_own) after you press the little "Python" button at the top
2. When you call ``GeNNModel.build()`` from your PyGeNN script it regenerates and recompiles your model (but not GeNN itself). However, if you haven't changed your model you can just call ``GeNNModel.load()`` to reuse the previously generated code.
3. I'm afraid I haven't used either of those IDEs for Python but it should work fine (you may need to launch them from the Native Tools Command Prompt so the correct tools are available)

**Comment by mariiapopova** [comment]
Thank you a lot! It perfectly answers my questions :)
