### ISSUE TITLE
CUDA Platform is not compiled in my computer

### ISSUE THREAD

**Issue by kroll-software** [genn-team/genn#403]
these steps
make DYNAMIC=1 LIBRARY_DIRECTORY=`pwd`/pygenn/genn_wrapper/
python setup.py develop

do not compile the CUDA platform on my computer:
Ubuntu 18.04.5 LTS, NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1

make and setup run without errors, but then only the OpenCL platform is listed in
/share/genn/backends/

Subsequent tests say, that only the cpu-version is available.

However, installing the latest wheel from your build-server works and tests are run on CUDA gpu
https://gen-ci.inf.sussex.ac.uk/job/GeNN/job/genn/job/master/

Best regards,

**Comment by neworderofjamie** [comment]
I suspect the step you missed is setting the ``CUDA_PATH`` environment variable e.g. to ``/usr/local/cuda`` on a typical Ubuntu install

**Comment by kroll-software** [comment]
is set and checked by echo $CUDA_PATH
/usr/local/cuda
which is valid.

**Comment by neworderofjamie** [comment]
Ok, very interesting. Can you check whether there's a genn_cuda_backend dynamic library in the pygenn/genn_wrapper directory? The share directory is only used for OpenCL so that's not indicative of anything

**Comment by kroll-software** [comment]
libgenn_cuda_backend_dynamic.so 
was created in pygenn/genn_wrapper directory.

I now remember: My problem rather was, that the ml_genn examples couldn't run on GPU.
After installing genn from Wheel, everything worked fine.

Let's see later, I'm happy now with the binary installation.

Best regards
