### ISSUE TITLE
RulkovMap problems and a way to add variable current source

### ISSUE THREAD

**Issue by m2kulkarni** [genn-team/genn#409]
Hi, I was writing a small code to replicate Fig 1 in [Nowotny 2005](https://link.springer.com/article/10.1007/s00422-005-0019-7) but I had some questions. 

1. Is there any way to let the `CurrentSourceModels::DC` have its amplitude uninitialised. This would require `amp` to be a variable instead of a parameter. This would've saved me from defining 5 different populations with different values of current. Another way I thought could be possible was to have a Connectivity Snippet for currents, but I could not find a way to do it. Is there an alternate way to do it that I'm possibly missing. Any help would be appreciated

2. I could not get the plot as per Fig 1 when the current amplitude were negative.

model.cc:
```
#include "modelSpec.h"

void modelDefinition(ModelSpec &model)
{
    model.setDT(0.5);
    model.setName("rulkov");
    NeuronModels::RulkovMap::ParamValues r_params(
        60.0,      //0 - Vspike
        3.0,        //1 - alpha
        -2.468,     //2 - y
        2.64        //3 - beta
    );
    NeuronModels::RulkovMap::VarValues r_ini(     
        -60.0,        //0 - V
        -60.0           //1 - preV
    );

    model.addNeuronPopulation<NeuronModels::RulkovMap>("rpop1", 1, r_params, r_ini);
    model.addNeuronPopulation<NeuronModels::RulkovMap>("rpop2", 1, r_params, r_ini);
    model.addNeuronPopulation<NeuronModels::RulkovMap>("rpop3", 1, r_params, r_ini);
    model.addNeuronPopulation<NeuronModels::RulkovMap>("rpop4", 1, r_params, r_ini);
    model.addNeuronPopulation<NeuronModels::RulkovMap>("rpop5", 1, r_params, r_ini);

    CurrentSourceModels::DC::ParamValues current1(0.1);
    CurrentSourceModels::DC::ParamValues current2(0.2);
    CurrentSourceModels::DC::ParamValues current3(0.3);
    CurrentSourceModels::DC::ParamValues current4(0.4);
    CurrentSourceModels::DC::ParamValues current5(0.5);

    model.addCurrentSource<CurrentSourceModels::DC>("c_source1", "rpop1", current1, {});
    model.addCurrentSource<CurrentSourceModels::DC>("c_source2", "rpop2", current2, {});
    model.addCurrentSource<CurrentSourceModels::DC>("c_source3", "rpop3", current3, {});
    model.addCurrentSource<CurrentSourceModels::DC>("c_source4", "rpop4", current4, {});
    model.addCurrentSource<CurrentSourceModels::DC>("c_source5", "rpop5", current5, {});
} 

```
Rulkov Parameters were taken from `userproject/Model_Schmuker_2014_classifier_project/Model_Schmuker_2014_classifier.cc`

**Comment by neworderofjamie** [comment]
Hello,

Regarding question 1, the solution is simply to define a new current source model where the amplitude IS a variable:
```c++
class DCVariable : public CurrentSourceModels::Base
{
    DECLARE_MODEL(DCVariable, 0 1);

    SET_INJECTION_CODE("$(injectCurrent, $(amp));\n");

    SET_VARS({{"amp", "scalar"}});
};
IMPLEMENT_MODEL(DCVariable);
```

@tnowotny any thoughts on the other question?

**Comment by m2kulkarni** [comment]
![neg_current](https://user-images.githubusercontent.com/56233197/113115283-e8ae8d00-9229-11eb-88af-32c0329b6cc7.png)
The plot looks like this, 'Neuron i' corresponds to -i*0.1nA current

**Comment by tnowotny** [comment]
Oh, I see. This is because you start with -60 as the initial value for V instead of the equilibrium or resting potential which is around -50 or so. In addition you are switching your input currents on from time 0 while for the figure the input current goes on after about 30 ms and off again after another 100ms.

**Comment by m2kulkarni** [comment]
Thanks @tnowotny @neworderofjamie 
![neg_all_dc_var](https://user-images.githubusercontent.com/56233197/113120816-9a9c8800-922f-11eb-96d1-70bae016458f.png) Works well

I did this,
```
class DCVariable : public Base
{
    DECLARE_MODEL(DCVariable, 0, 1);

    SET_INJECTION_CODE(
        "if($(t) > 30.0f && $(t) < 130.0f)\n"
        "{\n"
        "    $(injectCurrent, $(amp));\n"
        "};\n");

    SET_VARS({{"amp", "scalar"}});
};
```

**Comment by m2kulkarni** [comment]
Thanks! 
Also any idea about the parameter values that will get me bursting/silence/tonic spikes similar to the original rulkov paper(https://journals.aps.org/pre/abstract/10.1103/PhysRevE.65.041922), I don't think there is a one-one correspondence between parameters in both the papers

**Comment by m2kulkarni** [comment]
Yes, figured that out later, I tried to do it, looks okay I think
![bursting_1](https://user-images.githubusercontent.com/56233197/113129615-bbb5a680-9238-11eb-8469-a4fd2f3e3f83.png)
```
class RulkovOriginal : public Base
{
public:
    DECLARE_MODEL(NeuronModels::RulkovOriginal, 5, 4);


    SET_SIM_CODE(
        "if ($(V) <= 0) {\n"
        "   $(preV)= $(V);\n"
        "   $(V)= $(ip0)/(($(Vspike)) - $(V) - ($(beta))*$(Isyn)) +($(Vspike)*$(Y));\n"
        "   $(preY) = $(Y);\n"
        "   $(Y) -= $(mu)*($(V)+1) + $(ip2);\n"
        "}\n"
        "else {"
        "   if (($(V) < $(Vspike)*($(alpha)+$(Y))) && ($(preV) <= 0)) {\n"
        "       $(preV)= $(V);\n"
        "       $(V)= $(Vspike)*($(alpha)+$(Y));\n"
        "       $(preY) = $(Y);\n"
        "       $(Y) -= $(mu)*($(V)+1) + $(ip2);\n"
        "   }\n"
        "   else {\n"
        "       $(preV)= $(V);\n"
        "       $(V)= -($(Vspike));\n"
        "       $(preY) = $(Y);\n"
        "       $(Y) -= $(mu)*($(V)+1) + $(ip2);\n"
        "   }\n"
        "}\n");

    // SET_THRESHOLD_CONDITION_CODE("$(V) >= $(ip2)");

    SET_PARAM_NAMES({"Vspike", "alpha", "beta", "mu", "sigma"});
    SET_VARS({{"V","scalar"}, {"preV", "scalar"}, 
            {"Y", "scalar"}, {"preY", "scalar"}});

    SET_DERIVED_PARAMS({
        {"ip0", [](const std::vector<double> &pars, double){ return pars[0] * pars[0] * pars[1]; }},
        {"ip1", [](const std::vector<double> &pars, double){ return pars[0] * pars[1]; }},
        {"ip2", [](const std::vector<double> &pars, double){ return (pars[3] * pars[4]); }}});

};
```

Thanks for the help, may I go on to close the issue?

**Comment by tnowotny** [comment]
Looks good (your initial values are probably a bit off and that's why you are getting the long initial transient behaviour).
Fine to close the issue.
