### ISSUE TITLE
recipe for target 'cuda' failed

### ISSUE THREAD

**Issue by BarryLiu97** [genn-team/genn#411]
Hi, I am trying to run the example [here](https://github.com/neworderofjamie/multi-area-model/blob/6b3d20a9e47ec054ec2299f323f4191dbb942cf2/run_example_downscaled.py), so I followed the  [Installation guide](https://github.com/BrainsOnBoard/procedural_paper). My OS is ubuntu 18.04, gcc7.5.0, CUDA 11.1. nvcc -V works fine. BUt when I run the command ```make DYNAMIC=1 LIBRARY_DIRECTORY=`pwd`/pygenn/genn_wrapper/```, It gives me this error
```
In file included from backend.cc:1:0:
/home/lz/procedural_paper/genn/include/genn/backends/cuda/backend.h:13:10: fatal error: cuda.h: No such file or directory
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
Makefile:49: recipe for target '/home/lz/procedural_paper/genn/obj_dynamic/genn/backends/cuda/backend.o' failed
make[1]: *** [/home/lz/procedural_paper/genn/obj_dynamic/genn/backends/cuda/backend.o] Error 1
make[1]: Leaving directory '/home/lz/procedural_paper/genn/src/genn/backends/cuda'
Makefile:55: recipe for target 'cuda' failed
make: *** [cuda] Error 2
```
I tried GeNN 4.4.0 4.3.3, both have this situation. The machine has 4 RTX 3090.

**Comment by neworderofjamie** [comment]
Hi there, it sounds like you haven't set the CUDA_PATH environment variable. Typically, on Ubuntu, you do this like:
```bash
export CUDA_PATH=/usr/local/cuda
```

**Comment by BarryLiu97** [comment]
> Hi there, it sounds like you haven't set the CUDA_PATH environment variable. Typically, on Ubuntu, you do this like:
> 
> ```shell
> export CUDA_PATH=/usr/local/cuda
> ```
HI, I did this in the terminal. Is this enough? Very odd.

**Comment by neworderofjamie** [comment]
Yeah, it should be. Is CUDA actually installed in that location? ie does ``which nvcc`` show something like ``/usr/local/cuda/bin/nvcc``?

**Comment by BarryLiu97** [comment]
The resulit is
```
/usr/local/cuda/bin/nvcc
```

**Comment by neworderofjamie** [comment]
Very odd.. Is there a cuda.h in ``/usr/local/cuda/include``?

**Comment by BarryLiu97** [comment]
That's what I'm about to say. No, there is not. So I was trying to install another version like CUDA10.1, but I failed for when I run ```sh cuda_10.1.243_418.87.00_linux.run```, I've got  
```
Log file not open.
Segmentation fault (core dumped)
```
which stops me to move on.

**Comment by neworderofjamie** [comment]
Ahh ok, that's definitely the issue then. Personally, I wouldn't bother with the runfile installers and download a deb package instead

**Comment by BarryLiu97** [comment]
I've got no sudo authority, is thst OK?

**Comment by neworderofjamie** [comment]
I'm afraid you definitely need sudo authority to install cuda by any method

**Comment by BarryLiu97** [comment]
I need to install another CUDA but not affect the original CUDA, so I was trying to install it first and then create a soft link to my CUDA10.2

**Comment by BarryLiu97** [comment]
Or can say, there will be multiple CUDA in the cluster, and switch to the version that we need.

**Comment by neworderofjamie** [comment]
Ahh, I didn't realise you were using a cluster. In that case you can typically load a suitable CUDA version with something like ``module load CUDA/11.0``

**Comment by BarryLiu97** [comment]
Sorry, I don't know how to do this. Where should I put ```module load CUDA/11.0```?

**Comment by neworderofjamie** [comment]
Typically on the command line, but it depends on your cluster so you'll need to ask the administrator / read the documentation

**Comment by BarryLiu97** [comment]
So theoretically if I type something like ```module load CUDA/11.0```, and then run ```make DYNAMIC=1 LIBRARY_DIRECTORY=`pwd`/pygenn/genn_wrapper/``` may work fine?

**Comment by neworderofjamie** [comment]
Maybe but, on a cluster, the CUDA_PATH is likely not to be the standard ``/usr/local/cuda`` location

**Comment by BarryLiu97** [comment]
I've checked it, there are a Cuda file and a Cuda-11.1 in usr/local/

**Comment by neworderofjamie** [comment]
in that case, as long as the header files are installed, it should be fine. If not, you'll need to talk to your administrator

**Comment by BarryLiu97** [comment]
All right, thank you.
