### ISSUE TITLE
invalid error tag in diagnostic control option: extern_entity_treated_as_static

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/genn#412]
Hi, I was running the [example](https://github.com/neworderofjamie/multi-area-model/blob/6b3d20a9e47ec054ec2299f323f4191dbb942cf2/run_example_downscaled.py), and I've got this error
```
make: Entering directory '/home/lz/procedural_paper/models/multi-area-model/multi_area_model_CODE'
Command-line error: invalid error tag in diagnostic control option: extern_entity_treated_as_static
1 catastrophic error detected in this compilation.
Compilation terminated.
Command-line error: invalid error tag in diagnostic control option: extern_entity_treated_as_static
1 catastrophic error detected in this compilation.
Compilation terminated.
Makefile:22: recipe for target 'synapseUpdate.o' failed
Makefile:22: recipe for target 'customUpdate.o' failed
make: *** [synapseUpdate.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [customUpdate.o] Error 1
Command-line error: invalid error tag in diagnostic control option: extern_entity_treated_as_static
1 catastrophic error detected in this compilation.
Compilation terminated.
Command-line error: invalid error tag in diagnostic control option: extern_entity_treated_as_static
1 catastrophic error detected in this compilation.
Compilation terminated.
Makefile:22: recipe for target 'neuronUpdate.o' failed
Makefile:22: recipe for target 'init.o' failed
make: *** [neuronUpdate.o] Error 1
make: *** [init.o] Error 1
Command-line error: invalid error tag in diagnostic control option: extern_entity_treated_as_static
1 catastrophic error detected in this compilation.
Compilation terminated.
make: *** [runner.o] Error 1
Makefile:22: recipe for target 'runner.o' failed
make: Leaving directory '/home/lz/procedural_paper/models/multi-area-model/multi_area_model_CODE'
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/lz/pycharm/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/lz/pycharm/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/lz/procedural_paper/models/multi-area-model/run_example_downscaled.py", line 40, in <module>
    M.simulation.simulate()
  File "/home/lz/procedural_paper/models/multi-area-model/multiarea_model/simulation.py", line 308, in simulate
    self.model.build()
  File "/home/lz/procedural_paper/genn/pygenn/genn_model.py", line 579, in build
    check_call(["make", "-j", str(cpu_count(logical=False)), "-C", output_path])
  File "/home/lz/anaconda3/envs/pcl/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '36', '-C', './multi_area_model_CODE']' returned non-zero exit status 2.
```
The OS is Ubuntu with CUDA9.0.

**Comment by neworderofjamie** [comment]
@BarryLiu97, this is actually a bug! Can you try changing the check [here](https://github.com/genn-team/genn/blob/master/src/genn/backends/cuda/backend.cc#L1680-L1682) to ``m_RuntimeVersion > 9000`` and rebuilding PyGeNN? These command line arguments aren't documented at all and, I'm afraid, we didn't actually test on CUDA 9.0, only 9.2 (where it works).

**Comment by BarryLiu97** [comment]
Hi
I will. But its middle night for me so I will do it after about nine hours. Hope this is fine.

**Comment by BarryLiu97** [comment]
Hi, I've just tried your solution and seems works. And I just found the [repo](https://github.com/neworderofjamie/multi-area-model) you guys forked is old. And I've encountered an [issue](https://github.com/INM-6/multi-area-model/issues/27)  about plotting. And as to the developer, it comes from [here](https://github.com/neworderofjamie/multi-area-model/blob/master/multiarea_model/default_params.py#L132), so could you guys update the repo please?

**Comment by neworderofjamie** [comment]
That's great - I'm going to test on CUDA 9.1 today and will then make a fix. I don't really expect the plotting scripts to work with our simulations as we don't use the same output format as the originals ([our readme](https://github.com/BrainsOnBoard/procedural_paper) explains how to generate the results shown in our paper but anything further would be up to you. Updating the multi-area model repository is not a priority for us but I've raised issues https://github.com/neworderofjamie/multi-area-model/issues/1 and https://github.com/neworderofjamie/multi-area-model/issues/3 to track these issues and you would be more than welcome to submit a PR that fixes either

**Comment by BarryLiu97** [comment]
That's nice! I noticed that the output is different and in my opinion, your output format seems more concise. Thank you!
