### ISSUE TITLE
Provide more modern alternatives for addNeuronPopulation etc

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#42]
This is a suggestion only, but may be something to consider: Should we have overloaded functions where users use C++ vectors rather than C arrays for all parameters and initial values? For these we could then check that the number of provided paras is correct. Whereas with the current low-tech versions the users are on their own?

**Comment by jamesturner246** [comment]
Vectors are implemented, and parameter vector sizes are checked for neuron populations only. Still need to add checks for synapse parameter list sizes.

**Comment by jamesturner246** [comment]
Fixed in 70b1726, in separate_genn_obj_compile branch. Will merge into development branch when the genn object compilation feature is done.
