### ISSUE TITLE
genn-buildmodel.sh appears to fail when spaces in file path

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#424]
It appears that genn-buildmodel.sh fails when the model source is in a location with a path name that contains spaces.

**Comment by neworderofjamie** [comment]
What platform's this on?

**Comment by tnowotny** [comment]
macbook pro

**Comment by tnowotny** [comment]
```
m900050:neurotechTutorial tn41$ genn-buildmodel.sh LIFRing
/Users/tn41/localdisk_projects/develop/genn/bin/genn-buildmodel.sh: line 52: pushd: /Users/tn41/Box: No such file or directory
genn-buildmodel.sh:52: error 50: command failure
```
where the working directory is
```
/Users/tn41/Box Sync/workshops/2021/06-Neurotech/demo/neurotechTutorial
```

**Comment by tnowotny** [comment]
the error occurs here
https://github.com/genn-team/genn/blob/7cd8c549f45a6c6a3840e6aaa51c8ae6e849c20d/bin/genn-buildmodel.sh#L52
but to be honest I am not sure what this pushd / popd logic is trying to achieve to begin with? git blame says it was introduced by you, @jamesturner246, 5 years ago?

**Comment by neworderofjamie** [comment]
This seems to be the result of several different escaping issues:
1. In ``genn-buildmodel.sh``, some quotes are required (namely for that ``pushd``)
2. GNU make itself has very limited support for spaces in filenames (https://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them) and somewhere between bash and make ``OUT_PATH`` gets totally mangled. Escaping with ``\\`` (which can be done in bash on Linux and Mac with something like ``${OUT_PATH// /\\ }``) as suggested by https://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them) might help

However, my quick attempts at fixing 1 and 2 have not succeeded.
