### ISSUE TITLE
Before running the simulation, check if necessary arrays are copied to GPU

### ISSUE THREAD

**Issue by esinyavuz** [genn-team/genn#44]
Silent errors occur when we forget to copy a variable to the GPU. It would be useful to warn the user if:
- the values in the GPU are not meaningful (in general arrays contain only zeros if allocated but not initialized)
- necessary GeNN functions are not called

**Comment by esinyavuz** [comment]
One way of doing this could be to add a "sanity check" function in `runner.cc` which would go through the list of all the neuron and synapse groups, copy their variables from the device, print the first values, and sum of absolute values, and return a warning if this sum is zero. Users can then call this function before calling the kernels if they wish. It should be easy enough to implement.

**Comment by tnowotny** [comment]
This has been overtaken by history.
