### ISSUE TITLE
Run model several trials

### ISSUE THREAD

**Issue by mohamad-qodosi** [genn-team/genn#453]
Hi. thanks for your great work.
I need to build my SNN and then run it for several times (for example something about 2k runs). each run is separated from other runs but they all use same network. I'm not sure what is the best way to do it.

i tried to call model.reinitialise() each time but surprisingly, model had better performance on CPU (for CPU it took about 1.4 second per run but in CUDA mode it took more than 2 seconds per run)

my CPU: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
my GPU: GeForce RTX 2060 with CUDA 11.4
my OS: Ubuntu 20.04

also after building model, my codes looks like this:

```
for i in tqdm(range(100)):
    model.reinitialise()
    model.t = 0
    while model.t < run_time:
        model.step_time()
```
is there a better way to do this?

**Comment by neworderofjamie** [comment]
Thank you! So I think there are likely to be two issues here:
1. ``GeNNmodel.reinitialise`` reinitialises **everything** which includes some potentially slow stuff like re-creating all the connectivity. It's often faster to reset only the variables required - e.g. just membrane voltages
2. Small models (less than a few thousand neurons) are likely to be faster on CPU. However, is the latest release, there is a solution!  If your runs are entirely independent, GeNN can automatically be configured to run multiple instances of the same model in parallel on GPU by setting ``GeNNModel.batch_size``. Everything should then work as before but when you access spikes/variables there is an extra dimension i.e. the views of model variables become 2D and ``NeuronGroup.current_spikes`` returns a list containing the spikes for each parallel model.

**Comment by mohamad-qodosi** [comment]
thank you so much. you have helped me a lot.
