### ISSUE TITLE
ModuleNotFoundError: No module named '_CUDABackend'

### ISSUE THREAD

**Issue by ChenLumen** [genn-team/genn#459]
Hi, this bug happend when I was running my code:

    from pygenn.genn_wrapper.CUDABackend import BlockSizeSelect_MANUAL, DeviceSelect_MANUAL
  File "/home/lmc/anaconda3/envs/my_pygenn/lib/python3.6/site-packages/pygenn/genn_wrapper/CUDABackend.py", line 17, in <module>
    _CUDABackend = swig_import_helper()
  File "/home/lmc/anaconda3/envs/my_pygenn/lib/python3.6/site-packages/pygenn/genn_wrapper/CUDABackend.py", line 16, in swig_import_helper
    return importlib.import_module('_CUDABackend')
  File "/home/lmc/anaconda3/envs/my_pygenn/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_CUDABackend'

My GPU is RTX3090, and cuda is 11.1

This problem occurs when I stop the currently running program and try to run it again. It was normal before.
Some one can help me?

**Comment by neworderofjamie** [comment]
That is very strange. How exactly do you 
> stop the currently running program and try to run it again.

? One thing you can do to get some further information is edit and change lines 13-16 of /home/lmc/anaconda3/envs/my_pygenn/lib/python3.6/site-packages/pygenn/genn_wrapper/CUDABackend.py to read:

```python
try:
    return importlib.import_module(mname)
except ImportError as ex:
    print(ex)
    return importlib.import_module('_CUDABackend')
```
And tell me what error it gives.

**Comment by ChenLumen** [comment]
> That is very strange. How exactly do you
> 
> > stop the currently running program and try to run it again.
> 
> ? One thing you can do to get some further information is edit and change lines 13-16 of /home/lmc/anaconda3/envs/my_pygenn/lib/python3.6/site-packages/pygenn/genn_wrapper/CUDABackend.py to read:
> 
> ```python
> try:
>     return importlib.import_module(mname)
> except ImportError as ex:
>     print(ex)
>     return importlib.import_module('_CUDABackend')
> ```
> 
> And tell me what error it gives.
Oh, sorry. I solved this problem. Because I'm running it on a server, and somebody changed the file of cuda. So, we lost some files in the path: cuda/lib64/. And I get it again in the path: cuda/targets/x86_64-linux/lib/. So, it's normal now.

Thank you very much!
