### ISSUE TITLE
Adding synapse to neurons problem 

### ISSUE THREAD

**Issue by Mehmet5353** [genn-team/genn#467]
I  just started to PyGeNN one week ago. I am tryting to replicate Python tutorial1 and 2. Succesfully replicate tutorial 1 for my purposes bu when i am trying to connect to neurons like in Tutorial 2, i get same messeage below. I could not understand, i run first tutorial 1 easily, but second tutorial i got this error. Can you help me, thank you very much ?

make: Entering directory '/run/media/hilmi/flash/pygenn_CODE'
init.cc: 'void initialize()' işlevinde:
init.cc:87:47: hata: unable to find numeric literal operator 'operator""f'
   87 |                     group->inSynInSyn0[i] = 0,000000f;
      |                                               ^~~~~~~
init.cc:87:47: bilgi: use '-fext-numeric-literals' to enable more built-in suffixes
make: *** [Makefile:18: init.o] Error 1
make: *** Bitmemiş işler için bekliyor....
make: Leaving directory '/run/media/hilmi/flash/pygenn_CODE'
Traceback (most recent call last):
  File "/run/media/hilmi/flash/New_synapse.py", line 60, in <module>
    model1.build()
  File "/home/hilmi/.local/lib/python3.9/site-packages/pygenn/genn_model.py", line 526, in build
    check_call(["make", "-j", str(cpu_count(logical=False)), "-C", output_path])
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '6', '-C', './pygenn_CODE']' returned non-zero exit status 2.

**Comment by jamesturner246** [comment]
Looks like there is a comma in a floating-point number somewhere: 

` 87 | group->inSynInSyn0[i] = 0,000000f;`.

Have a look and make sure you don't have any commas in your fp number literals.

**Comment by neworderofjamie** [comment]
This looks like a locale bug in GeNN. Can you try the "locale" branch I just made?

**Comment by Mehmet5353** [comment]
I do not want to sound dummy but i am. I found the "locale" branch you just made. Thank you very much.  I install PyGeNN form .whl for Linux. Where can i find the script i should change ?

**Comment by neworderofjamie** [comment]
The wheel has been produced

**Comment by Mehmet5353** [comment]
Thank you james,no i have to switch to python 3.6 :D
