### ISSUE TITLE
Libpugixml.a not being bundled with GeNN

### ISSUE THREAD

**Issue by alexdewar** [genn-team/genn#477]
I was trying to get this example to build as part of my CMake tidy-up: https://github.com/BrainsOnBoard/bob_robotics/tree/master/examples/spineml_braitenberg

I have GeNN installed systemwide on my machine and it seems to be working ok, but when I get linking errors when trying to use the SpineML integration, seemingly because libpugixml.a isn't included. I'm not sure if it's just not built at all or if it's not being copied over during ``make install``.

**Comment by neworderofjamie** [comment]
System wide install doesn't install SpineML but if you make spineml_simulator (https://github.com/genn-team/genn/tree/master/src/spineml/simulator) and spineml_common (https://github.com/genn-team/genn/tree/master/src/spineml/common), they are what you need to link (pugixml is included in spineml_common)

**Comment by alexdewar** [comment]
Ha, solved. I *did* have the libraries and I was linking against them, but the order matters: spineml_simulator needs to come first because it needs the pugixml symbols that are in spineml_common.
