### ISSUE TITLE
Not able to use Cuda feature of PyGenn

### ISSUE THREAD

**Issue by Mehmet5353** [genn-team/genn#483]
![Ekran görüntüsü 2021-11-18 12-13-06](https://user-images.githubusercontent.com/44751934/142386205-1f57e0b3-2299-4825-b556-c11ece1fd860.png)

I am getting this error, when i want to use my GPU, Can you help me ? What is my mistake ?

**Comment by neworderofjamie** [comment]
I'm pretty sure this is not related to GeNN. Could you see if it happens when building CUDA samples as it sounds like [this](https://forums.developer.nvidia.com/t/cuda-11-5-samples-throw-multiple-error-attribute-malloc-does-not-take-arguments/192750/13) CUDA bug

**Comment by Mehmet5353** [comment]
Problem is related to CUDA. Cuda is not compatible with gcc++11. Thank you
