### ISSUE TITLE
Simplification of user interaction with circular spike queues when delays are used

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#49]
I think we should provide macros that translate something simple like "SpikePN[0]" ... "SpikePN[SpikeCountPN]" into the apropriate expressions of the form "glbSpkPN[spkQuePtr*...+...]" etc.

**Comment by tnowotny** [comment]
PS: These macros would have to be code-generated I believe.

**Comment by jamesturner246** [comment]
Are these macros implemented now?

**Comment by tnowotny** [comment]
Most of these are done now believe.
