### ISSUE TITLE
When simulating millions of neurons 32 bit integers are sometimes too small for memory allocation

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#52]
I suspect we should migrate everything to 64 bit integers to make sure that things work smoothly even if everything is scaled up (a lot). At the moment the point of failure coincides with where we run out of memory but with the next devices this may well change.

**Comment by neworderofjamie** [comment]
The microcircuit/massive STDP network hit some of these limits and I have switched these calculations to ``size_t``
