### ISSUE TITLE
Small DT and single precision floating point

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#53]
If DT is small (e.g. 0.01) and single precision floating point is used I have observed that
int riT= (int) (runtime/DT);
resulted in riT== 0 for runtime= 0.01 and hence no time stepping.
I suggest to amend all user projects that do a similar step to use:
int riT= (int) (runtime/DT+1e-6);

**Comment by shailesh210** [comment]
Does this mean that all one need to do is change the above part of code in all the user projects?

**Comment by tnowotny** [comment]
yes, agreed. However, it might not always be called the same name, i.e. some searching and checking will be required (I suspect because it normally doesn't cause any problems, we haven't found the time to fix it so far).

**Comment by esinyavuz** [comment]
This does not really apply to all the user projects, it is only meaningful for those that use single precision and a small time step. In general if you need such a small time step you would want double precision anyway. I think that among the user projects in GeNN, only the mushroom body models and the HHVclampGA model would be affected by this, and they should have already been corrected. If not yes, we need to fix these examples.

**Comment by tnowotny** [comment]
It might be a more common problem for small time steps and single precision floating point (numerical error in the division of effectively DT/DT blows up more) but in principle it could accidentally happen in all time step sizes that DT/DT is converted down to 0 in the integer conversion. So a safeguard against that may be in order for all examples.

**Comment by jamesturner246** [comment]
Changes merged to development branch in #66.

James.
