### ISSUE TITLE
Sudden large difference in PyGeNN voltage compared to equivalent voltage equation in python

### ISSUE THREAD

**Issue by williamsnider** [genn-team/genn#536]
I'm running into an issue where the voltage that PyGeNN calculates starts off exactly matching the voltage calculated in pure python, but after a small number of timesteps (29 with my sample data), there is a sudden and large deviation (1e-5 mV difference). This is at the very start of a simulation; no spikes have occurred. To illustrate this I made a simplified script, where inside the model stepping loop I also calculate the voltage using straight python:

```python
import numpy as np
from pygenn.genn_model import (
    create_custom_neuron_class,
    GeNNModel,
    create_custom_current_source_class,
)

# GLIF parameters/initial values
C = 0.059741225561272475
G = 0.009007466911287449
El = 0.0
th_inf = 46.17742084129465
V_init = 0.0
dt = 0.005

# Sample stimulus data taken from Teeter et al. 2018 (in nanoamps)
stimulus = [
    0.5472500230752075,
    0.5471250119626347,
    0.547000000850062,
    0.5468749897374892,
    0.5466250230234948,
    0.546500011910922,
    0.5463750007983492,
    0.5461249785732036,
    0.5460000229717821,
    0.5458750118592093,
    0.5457500007466365,
    0.5454999785214909,
    0.5453750229200693,
    0.5452500118074965,
    0.544999989582351,
    0.5448749784697782,
    0.5447500228683566,
    0.5446250117557838,
    0.5443749895306382,
    0.5442499784180654,
    0.5441250228166439,
    0.5438750005914983,
    0.5437499894789255,
    0.5436249783663527,
    0.5435000227649311,
    0.5432500005397856,
    0.5431249894272128,
    0.5427500116006456,
    0.5427500116006456,
    0.5426250004880728,  # 29th current value, causes voltage difference?
    0.5424999893755,
    0.5422500226615057,
    0.5421250115489329,
    0.5420000004363601,
    0.5417499782112145,
    0.541625022609793,
    0.5415000114972202,
    0.5413750003846474,
    0.5411249781595018,
    0.5410000225580802,
    0.5408750114455074,
    0.5406249892203618,
    0.540499978107789,
    0.5403750225063675,
    0.5472500230752075,
    0.5471250119626347,
    0.547000000850062,
    0.5468749897374892,
    0.5466250230234948,
    0.546500011910922,
    0.5463750007983492,
    0.5461249785732036,
    0.5460000229717821,
    0.5458750118592093,
    0.5457500007466365,
    0.5454999785214909,
    0.5453750229200693,
    0.5452500118074965,
    0.544999989582351,
    0.5448749784697782,
    0.5447500228683566,
    0.5446250117557838,
    0.5443749895306382,
    0.5442499784180654,
    0.5441250228166439,
    0.5438750005914983,
    0.5437499894789255,
    0.5436249783663527,
    0.5435000227649311,
    0.5432500005397856,
    0.5431249894272128,
    0.5427500116006456,
    0.5427500116006456,
    0.5426250004880728,
    0.5424999893755,
    0.5422500226615057,
    0.5421250115489329,
    0.5420000004363601,
    0.5417499782112145,
    0.541625022609793,
    0.5415000114972202,
    0.5413750003846474,
    0.5411249781595018,
    0.5410000225580802,
    0.5408750114455074,
    0.5406249892203618,
    0.540499978107789,
    0.5403750225063675,
]

# Create simplified neuron class
test_neuron = create_custom_neuron_class(
    "test_neuron",
    param_names=["C", "G", "El", "th_inf"],
    var_name_types=[("V", "double")],
    sim_code="$(V) += ($(Isyn)-$(G)*($(V)-$(El)))*DT/$(C);",
    threshold_condition_code="$(V) >= $(th_inf)",
    reset_code="$(V) = $(El);",
)

# Create model
model = GeNNModel("double", "test_neuron")
model.dT = dt
pop1 = model.add_neuron_population(
    pop_name="pop1",
    num_neurons=1,
    neuron=test_neuron,
    param_space={"C": C, "G": G, "El": El, "th_inf": th_inf},
    var_space={"V": V_init},
)

# Add current source as input of stimulus
external_current_source = create_custom_current_source_class(
    class_name="external_current",
    var_name_types=[("current", "double")],
    injection_code="""
    $(current)=$(Ie)[int($(t) / DT)];
    $(injectCurrent,$(current) );
    """,
    extra_global_params=[("Ie", "double*")],
)
cs = model.add_current_source(
    cs_name="external_current_source",
    current_source_model=external_current_source,
    pop=pop1,
    param_space={},
    var_space={"current": 0.0},
)
cs.set_extra_global_param("Ie", stimulus)

# Build and load model
model.build()
model.load()

# Define initial values for calculating voltage outside of GeNN
V_prev = V_init
V = V_init

# Step through model
num_steps = len(stimulus)
for i in range(num_steps):

    # Voltage calculated inside GeNN
    model.step_time()
    pop1.pull_var_from_device("V")
    V_GeNN = pop1.vars["V"].view[:]

    # Voltage calculated outside GeNN using python (same equation)
    inj = stimulus[i]
    V += (inj - G * (V_prev - El)) * dt / C
    V_prev = V

    # Difference
    diff = np.abs(V - V_GeNN[0])
    print("-" * 10)
    print("i = ", i)
    print("V_outside_GeNN: ", V)
    print("V_inside_GeNN : ", V_GeNN[0])
    print("Difference    : ", diff)
    if diff > 1e-10:
        print("Large voltage difference at timestep {i}".format(i=i))
        raise ValueError("Raising error as breakpoint.")
```

The output that I get is:
```bash
----------
i =  0
V_outside_GeNN:  0.045801707107090625
V_inside_GeNN :  0.045801707107090625
Difference    :  0.0
----------
i =  1
V_outside_GeNN:  0.09155842279755314
V_inside_GeNN :  0.09155842279755314
Difference    :  0.0
----------
i =  2
V_outside_GeNN:  0.13727018098923008
V_inside_GeNN :  0.13727018098923008
Difference    :  0.0
----------
i =  3
V_outside_GeNN:  0.18293701557439423
V_inside_GeNN :  0.18293701557439423
Difference    :  0.0
----------
i =  4
V_outside_GeNN:  0.22854850234828983
V_inside_GeNN :  0.22854850234828983
Difference    :  0.0
----------
i =  5
V_outside_GeNN:  0.27411514110765034
V_inside_GeNN :  0.27411514110765034
Difference    :  0.0
----------
i =  6
V_outside_GeNN:  0.3196369656622113
V_inside_GeNN :  0.3196369656622113
Difference    :  0.0
----------
i =  7
V_outside_GeNN:  0.36510354707877485
V_inside_GeNN :  0.36510354707877485
Difference    :  0.0
----------
i =  8
V_outside_GeNN:  0.41052539436709795
V_inside_GeNN :  0.41052539436709795
Difference    :  0.0
----------
i =  9
V_outside_GeNN:  0.4559025366050933
V_inside_GeNN :  0.4559025366050933
Difference    :  0.0
----------
i =  10
V_outside_GeNN:  0.5012350074947194
V_inside_GeNN :  0.5012350074947194
Difference    :  0.0
----------
i =  11
V_outside_GeNN:  0.5465123779950828
V_inside_GeNN :  0.5465123779950828
Difference    :  0.0
----------
i =  12
V_outside_GeNN:  0.5917451570083259
V_inside_GeNN :  0.5917451570083259
Difference    :  0.0
----------
i =  13
V_outside_GeNN:  0.636933373504828
V_inside_GeNN :  0.636933373504828
Difference    :  0.0
----------
i =  14
V_outside_GeNN:  0.6820665983616505
V_inside_GeNN :  0.6820665983616505
Difference    :  0.0
----------
i =  15
V_outside_GeNN:  0.7271553357529852
V_inside_GeNN :  0.7271553357529852
Difference    :  0.0
----------
i =  16
V_outside_GeNN:  0.7721996238627261
V_inside_GeNN :  0.7721996238627261
Difference    :  0.0
----------
i =  17
V_outside_GeNN:  0.8171994915540477
V_inside_GeNN :  0.8171994915540477
Difference    :  0.0
----------
i =  18
V_outside_GeNN:  0.8621445095968869
V_inside_GeNN :  0.8621445095968869
Difference    :  0.0
----------
i =  19
V_outside_GeNN:  0.9070451820583925
V_inside_GeNN :  0.9070451820583925
Difference    :  0.0
----------
i =  20
V_outside_GeNN:  0.9519015470154955
V_inside_GeNN :  0.9519015470154955
Difference    :  0.0
----------
i =  21
V_outside_GeNN:  0.9967031705070433
V_inside_GeNN :  0.9967031705070433
Difference    :  0.0
----------
i =  22
V_outside_GeNN:  1.0414605565186283
V_inside_GeNN :  1.0414605565186283
Difference    :  0.0
----------
i =  23
V_outside_GeNN:  1.08617373839972
V_inside_GeNN :  1.08617373839972
Difference    :  0.0
----------
i =  24
V_outside_GeNN:  1.1308427541206136
V_inside_GeNN :  1.1308427541206136
Difference    :  0.0
----------
i =  25
V_outside_GeNN:  1.1754571696136007
V_inside_GeNN :  1.1754571696136007
Difference    :  0.0
----------
i =  26
V_outside_GeNN:  1.2200274887577984
V_inside_GeNN :  1.2200274887577984
Difference    :  0.0
----------
i =  27
V_outside_GeNN:  1.2645328240073581
V_inside_GeNN :  1.2645328240073581
Difference    :  0.0
----------
i =  28
V_outside_GeNN:  1.3090046078582922
V_inside_GeNN :  1.3090046078582922
Difference    :  0.0
----------
i =  29
V_outside_GeNN:  1.3534324028866707
V_inside_GeNN :  1.3534428656041155
Difference    :  1.0462717444870151e-05
Large voltage difference at timestep 29
```

My observations
- Before timestep i=29, there is an exact match between the voltage calculated using GeNN and the voltage calculated using python. This is evidence that the equations, parameters, current input, etc. between the two are the same.
- At timestep i=29, there is a large difference in the two voltages (1e-05 mV). I'm not sure why?
- If I replace the stimulus value at that timestep (e.g. ```stimulus[29] = stimulus[28]```), this results in no difference between the two voltages. However, there will now be a large voltage difference at timestep i=58. I notice that 2 * 29 = 58, but maybe that is just a coincidence.
- Thinking maybe this is something weird with the current source class, I removed that and instead added the input current `Ie` as an extra_global_param. I got the same result - exact match up to timestep i=29, then the large voltage difference.

@neworderofjamie @tnowotny Does the same occur when you run this script on your machine? Any ideas as to how to approach this?

**Comment by tnowotny** [comment]
Hi William,
Could you print out/ check the value of (int) ( $(t)/DT) ? It is conceivable that rounding errors on t could cause a slip by one time step. It generally would be more robust to use round()
Best,
Thomas

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: William Snider ***@***.***>
Sent: Monday, July 25, 2022 8:39:39 AM
To: genn-team/genn ***@***.***>
Cc: Thomas Nowotny ***@***.***>; Mention ***@***.***>
Subject: [genn-team/genn] Sudden large difference in PyGeNN voltage compared to equivalent voltage equation in python (Issue #536)


I'm running into an issue where the voltage that PyGeNN calculates starts off exactly matching the voltage calculated in pure python, but after a small number of timesteps (29 with my sample data), there is a sudden and large deviation (1e-5 mV difference). To illustrate this I made a simplified script, where inside the model stepping loop I also calculate the voltage using straight python:

import numpy as np
from pygenn.genn_model import (
    create_custom_neuron_class,
    GeNNModel,
    create_custom_current_source_class,
)

# GLIF parameters/initial values
C = 0.059741225561272475
G = 0.009007466911287449
El = 0.0
th_inf = 46.17742084129465
V_init = 0.0
dt = 0.005

# Sample stimulus data taken from Teeter et al. 2018 (in nanoamps)
stimulus = [
    0.5472500230752075,
    0.5471250119626347,
    0.547000000850062,
    0.5468749897374892,
    0.5466250230234948,
    0.546500011910922,
    0.5463750007983492,
    0.5461249785732036,
    0.5460000229717821,
    0.5458750118592093,
    0.5457500007466365,
    0.5454999785214909,
    0.5453750229200693,
    0.5452500118074965,
    0.544999989582351,
    0.5448749784697782,
    0.5447500228683566,
    0.5446250117557838,
    0.5443749895306382,
    0.5442499784180654,
    0.5441250228166439,
    0.5438750005914983,
    0.5437499894789255,
    0.5436249783663527,
    0.5435000227649311,
    0.5432500005397856,
    0.5431249894272128,
    0.5427500116006456,
    0.5427500116006456,
    0.5426250004880728,  # 29th current value, causes voltage difference?
    0.5424999893755,
    0.5422500226615057,
    0.5421250115489329,
    0.5420000004363601,
    0.5417499782112145,
    0.541625022609793,
    0.5415000114972202,
    0.5413750003846474,
    0.5411249781595018,
    0.5410000225580802,
    0.5408750114455074,
    0.5406249892203618,
    0.540499978107789,
    0.5403750225063675,
    0.5472500230752075,
    0.5471250119626347,
    0.547000000850062,
    0.5468749897374892,
    0.5466250230234948,
    0.546500011910922,
    0.5463750007983492,
    0.5461249785732036,
    0.5460000229717821,
    0.5458750118592093,
    0.5457500007466365,
    0.5454999785214909,
    0.5453750229200693,
    0.5452500118074965,
    0.544999989582351,
    0.5448749784697782,
    0.5447500228683566,
    0.5446250117557838,
    0.5443749895306382,
    0.5442499784180654,
    0.5441250228166439,
    0.5438750005914983,
    0.5437499894789255,
    0.5436249783663527,
    0.5435000227649311,
    0.5432500005397856,
    0.5431249894272128,
    0.5427500116006456,
    0.5427500116006456,
    0.5426250004880728,
    0.5424999893755,
    0.5422500226615057,
    0.5421250115489329,
    0.5420000004363601,
    0.5417499782112145,
    0.541625022609793,
    0.5415000114972202,
    0.5413750003846474,
    0.5411249781595018,
    0.5410000225580802,
    0.5408750114455074,
    0.5406249892203618,
    0.540499978107789,
    0.5403750225063675,
]

# Create simplified neuron class
test_neuron = create_custom_neuron_class(
    "test_neuron",
    param_names=["C", "G", "El", "th_inf"],
    var_name_types=[("V", "double")],
    sim_code="$(V) += ($(Isyn)-$(G)*($(V)-$(El)))*DT/$(C);",
    threshold_condition_code="$(V) >= $(th_inf)",
    reset_code="$(V) = $(El);",
)

# Create model
model = GeNNModel("double", "test_neuron")
model.dT = dt
pop1 = model.add_neuron_population(
    pop_name="pop1",
    num_neurons=1,
    neuron=test_neuron,
    param_space={"C": C, "G": G, "El": El, "th_inf": th_inf},
    var_space={"V": V_init},
)

# Add current source as input of stimulus
external_current_source = create_custom_current_source_class(
    class_name="external_current",
    var_name_types=[("current", "double")],
    injection_code="""
    $(current)=$(Ie)[int($(t) / DT)];
    $(injectCurrent,$(current) );
    """,
    extra_global_params=[("Ie", "double*")],
)
cs = model.add_current_source(
    cs_name="external_current_source",
    current_source_model=external_current_source,
    pop=pop1,
    param_space={},
    var_space={"current": 0.0},
)
cs.set_extra_global_param("Ie", stimulus)

# Build and load model
model.build()
model.load()

# Define initial values for calculating voltage outside of GeNN
V_prev = V_init
V = V_init

# Step through model
num_steps = len(stimulus)
for i in range(num_steps):

    # Voltage calculated inside GeNN
    model.step_time()
    pop1.pull_var_from_device("V")
    V_GeNN = pop1.vars["V"].view[:]

    # Voltage calculated outside GeNN using python (same equation)
    inj = stimulus[i]
    V += (inj - G * (V_prev - El)) * dt / C
    V_prev = V

    # Difference
    diff = np.abs(V - V_GeNN[0])
    print("-" * 10)
    print("i = ", i)
    print("V_outside_GeNN: ", V)
    print("V_inside_GeNN : ", V_GeNN[0])
    print("Difference    : ", diff)
    if diff > 1e-10:
        print("Large voltage difference at timestep {i}".format(i=i))
        raise ValueError("Raising error as breakpoint.")

The output that I get is:

----------
i =  0
V_outside_GeNN:  0.045801707107090625
V_inside_GeNN :  0.045801707107090625
Difference    :  0.0
----------
i =  1
V_outside_GeNN:  0.09155842279755314
V_inside_GeNN :  0.09155842279755314
Difference    :  0.0
----------
i =  2
V_outside_GeNN:  0.13727018098923008
V_inside_GeNN :  0.13727018098923008
Difference    :  0.0
----------
i =  3
V_outside_GeNN:  0.18293701557439423
V_inside_GeNN :  0.18293701557439423
Difference    :  0.0
----------
i =  4
V_outside_GeNN:  0.22854850234828983
V_inside_GeNN :  0.22854850234828983
Difference    :  0.0
----------
i =  5
V_outside_GeNN:  0.27411514110765034
V_inside_GeNN :  0.27411514110765034
Difference    :  0.0
----------
i =  6
V_outside_GeNN:  0.3196369656622113
V_inside_GeNN :  0.3196369656622113
Difference    :  0.0
----------
i =  7
V_outside_GeNN:  0.36510354707877485
V_inside_GeNN :  0.36510354707877485
Difference    :  0.0
----------
i =  8
V_outside_GeNN:  0.41052539436709795
V_inside_GeNN :  0.41052539436709795
Difference    :  0.0
----------
i =  9
V_outside_GeNN:  0.4559025366050933
V_inside_GeNN :  0.4559025366050933
Difference    :  0.0
----------
i =  10
V_outside_GeNN:  0.5012350074947194
V_inside_GeNN :  0.5012350074947194
Difference    :  0.0
----------
i =  11
V_outside_GeNN:  0.5465123779950828
V_inside_GeNN :  0.5465123779950828
Difference    :  0.0
----------
i =  12
V_outside_GeNN:  0.5917451570083259
V_inside_GeNN :  0.5917451570083259
Difference    :  0.0
----------
i =  13
V_outside_GeNN:  0.636933373504828
V_inside_GeNN :  0.636933373504828
Difference    :  0.0
----------
i =  14
V_outside_GeNN:  0.6820665983616505
V_inside_GeNN :  0.6820665983616505
Difference    :  0.0
----------
i =  15
V_outside_GeNN:  0.7271553357529852
V_inside_GeNN :  0.7271553357529852
Difference    :  0.0
----------
i =  16
V_outside_GeNN:  0.7721996238627261
V_inside_GeNN :  0.7721996238627261
Difference    :  0.0
----------
i =  17
V_outside_GeNN:  0.8171994915540477
V_inside_GeNN :  0.8171994915540477
Difference    :  0.0
----------
i =  18
V_outside_GeNN:  0.8621445095968869
V_inside_GeNN :  0.8621445095968869
Difference    :  0.0
----------
i =  19
V_outside_GeNN:  0.9070451820583925
V_inside_GeNN :  0.9070451820583925
Difference    :  0.0
----------
i =  20
V_outside_GeNN:  0.9519015470154955
V_inside_GeNN :  0.9519015470154955
Difference    :  0.0
----------
i =  21
V_outside_GeNN:  0.9967031705070433
V_inside_GeNN :  0.9967031705070433
Difference    :  0.0
----------
i =  22
V_outside_GeNN:  1.0414605565186283
V_inside_GeNN :  1.0414605565186283
Difference    :  0.0
----------
i =  23
V_outside_GeNN:  1.08617373839972
V_inside_GeNN :  1.08617373839972
Difference    :  0.0
----------
i =  24
V_outside_GeNN:  1.1308427541206136
V_inside_GeNN :  1.1308427541206136
Difference    :  0.0
----------
i =  25
V_outside_GeNN:  1.1754571696136007
V_inside_GeNN :  1.1754571696136007
Difference    :  0.0
----------
i =  26
V_outside_GeNN:  1.2200274887577984
V_inside_GeNN :  1.2200274887577984
Difference    :  0.0
----------
i =  27
V_outside_GeNN:  1.2645328240073581
V_inside_GeNN :  1.2645328240073581
Difference    :  0.0
----------
i =  28
V_outside_GeNN:  1.3090046078582922
V_inside_GeNN :  1.3090046078582922
Difference    :  0.0
----------
i =  29
V_outside_GeNN:  1.3534324028866707
V_inside_GeNN :  1.3534428656041155
Difference    :  1.0462717444870151e-05
Large voltage difference at timestep 29

My observations

  *   Before timestep i=29, there is an exact match between the voltage calculated using GeNN and the voltage calculated using python. This is evidence that the equations, parameters, current input, etc. between the two are the same.
  *   At timestep i=29, there is a large difference in the two voltages (1e-05 mV). I'm not sure why?
  *   If I replace the stimulus value at that timestep (e.g. stimulus[29] = stimulus[28]), this results in no difference between the two voltages. However, there will now be a large voltage difference at timestep i=58. I notice that 2 * 29 = 58, but maybe that is just a coincidence.
  *   Thinking maybe this is something weird with the current source class, I removed that and instead added the input current Ie as an extra_global_param. I got the same result - exact match up to timestep i=29, then the large voltage difference.

@neworderofjamie<https://github.com/neworderofjamie> @tnowotny<https://github.com/tnowotny> Does the same occur when you run this script on your machine? Any ideas as to how to approach this?

**Comment by williamsnider** [comment]
That was it! Thanks for catching that :smile:
