### ISSUE TITLE
Docker install of GeNN

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/genn#546]
It would be great to be able to run GeNN models from a docker image. One of our users (@russelljjarvis) kindly started creating the following:

```dockerfile
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04
WORKDIR /usr/local/cuda-11.8/
ENV CUDA_PATH=/usr/local/cuda-11.8 
RUN cuda-memcheck ./has_cuda ; exit 0
RUN nvcc; exit 0
RUN apt update; 
RUN apt install git build-essential lcov wget -y --no-install-recommends 
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda

ENV PATH=$CONDA_DIR/bin:$PATH
WORKDIR $HOME/jovyan
RUN $(which conda) install -c miniconda swig numpy -y
RUN git clone https://github.com/genn-team/genn.git
RUN mv genn GeNN
WORKDIR GeNN
ENV PATH=$PATH:$HOME/jovyan/GeNN/bin
RUN make DYNAMIC=1 LIBRARY_DIRECTORY=`pwd`/pygenn/genn_wrapper/
RUN python setup.py develop
WORKDIR $HOME/jovyan/GeNN/userproject/PotjansMicrocircuit_project
RUN make
RUN ./generate_run test 
WORKDIR $HOME/jovyan/GeNN/
RUN bash tests/run_tests.sh; exit 0
ENTRYPOINT ["/bin/bash"]
```

It fails at the step
```RUN ./generate_run test ```
but I think it is close.

Maybe I need a different Docker command for building with access to system cuda?

_Originally posted by @russelljjarvis in https://github.com/genn-team/genn/discussions/545#discussioncomment-3911329_

Personally I would like to see:
- [ ] A more flexible entry point that can also launch a jupyter notebook
- [ ] System Python rather than Anaconda (unless someone can convince me why conda improves anything)
- [ ] Figure out where the dockerfile should live (seperate genn-docker repository or in the genn repository) and get this building from Jenkins

**Comment by russelljjarvis** [comment]
>  A more flexible entry point that can also launch a jupyter notebook
>  System Python rather than Anaconda (unless someone can convince me why conda improves anything)
>  Figure out where the dockerfile should live (seperate genn-docker repository or in the genn repository) and get this building from Jenkins
> 

With a dedicated `genn-docker` repository, you might be able to provide docker layers with different levels of bloat. 
For instance, in some projects, I have used `neo` (maybe an INCF standard?). 

Adding jupyter notebooks and a jupyter notebook entry point might also increase the container size quite a bit, and it is likely completely useless for HPC use cases. If we can get Docker onto HPC perhaps via the singularity, I think a barebones/minimall CUDA version would be great, as I don't want to spend a lot of time uploading large images with stuff I don't need onto HPC.

Another thing is if you wanted to do unit testing via Docker+Jenkins (I don't know if Jenkin CI servers time out). You might want the dockerbuild to be fast, so tests have more time.

>System Python rather than Anaconda (unless someone can convince me why conda improves anything)
I thought that conda, is like a cross betweenn `apt-get` and `pip`, it can get the right C libraries for your system, whereas is pip is not that sophisticated about non Python dependencies for Python code. I always try to use conda over pip.

**Comment by russelljjarvis** [comment]
```
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04
ENV CUDA_PATH=/usr/local/cuda-11.8 
# RUN cuda-memcheck ./has_cuda; exit 0
# RUN nvcc; exit 0
RUN apt update; 
RUN apt install git build-essential lcov wget -y --no-install-recommends 
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda

ENV PATH=$CONDA_DIR/bin:$PATH
WORKDIR $HOME/workdir
RUN conda install -c miniconda swig numpy -y
RUN git clone https://github.com/genn-team/genn.git
RUN mv genn GeNN
WORKDIR GeNN
ENV PATH=$PATH:$HOME/workdir/GeNN/bin
RUN make DYNAMIC=1 LIBRARY_DIRECTORY=`pwd`/pygenn/genn_wrapper/
RUN python setup.py develop
WORKDIR $HOME/workdir/GeNN/userproject/PotjansMicrocircuit_project
RUN make
RUN ./generate_run test 
WORKDIR $HOME/workdir/GeNN/
RUN bash tests/run_tests.sh; exit 0 # This will fail because some tests will naturally fail. The build should not be contingent 
# on test running success.

#
# Uncomment to experiment with multistage build:
#
# FROM docker-registry.ebrains.eu/nest/nest-simulator:3.3
ENTRYPOINT ["/bin/bash"]
```
