### ISSUE TITLE
Support code should be usable by sparse connectivity initialisation

### ISSUE THREAD

**Issue by jhnnsnk** [genn-team/genn#560]
Several `genn_model.create_custom_*_class()` functions have the keyword argument `support_code` which I find very useful, for instance, for defining functions used by `sim_code`.
However, this feature is currently not available for all functions of this type.
In particular, I would appreciate if it could be added to `genn_model.create_custom_sparse_connect_init_snippet_class()`.

**Comment by neworderofjamie** [comment]
Support code has been removed in GeNN 5
