### ISSUE TITLE
Not able to install pygenn in Tutorial's notebooks: is not a supported wheel on this platform

### ISSUE THREAD

**Issue by formozov** [genn-team/genn#561]
Hello!

I was trying to run your notebooks in 

https://genn-team.github.io/tutorials.html

, yet it was not possible due to the errror when I run 

!pip install pygenn-4.7.1-cp37-cp37m-linux_x86_64.whl

the result is

ERROR: pygenn-4.7.1-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform

Is there quick fix for that?

**Comment by neworderofjamie** [comment]
Thanks for reporting this - it seems collab upgrading their standard image from Python 3.7 to 3.8. I've rebuilt the wheel files and updated all the notebooks. If you could confirm this fixes your issue, I will close the bug

**Comment by formozov** [comment]
That worked, many thanks!

**Comment by neworderofjamie** [comment]
Wonderful!
