### ISSUE TITLE
NVRTC

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/genn#562]
The NVRTC (https://docs.nvidia.com/cuda/nvrtc/index.html) runtime CUDA compiler is a relatively new thing which could solve a couple of issues:

1. Improve performance of CUDA block size optimization and reduce temporary file crud
2. More drastically, GeNN could use NVRTC backend to build kernels at runtime rather than generating files full of code. This would solve a number of issues:
    -  You wouldn't need to have a CUDA development environment installed (especially good on Windows where this involves a Visual Studio install)
    -  There would no longer be a "runner" (as allocations would also be made at runtime so all the various runner-size issues would disappear)
    - This would correspond to a much less weird way of using OpenCL
    - Opens the way for long-standing switching out of e.g. synapse kernels based on runtime performance

**Comment by tnowotny** [comment]
Very interesting. A full refactoring as in 2. might take quite some work?

**Comment by neworderofjamie** [comment]
I am going to replace the runner with a runtime **but**, having investigated further, NVRTC is sadly not the answer because it cannot compile host code at all. This would break host initialisation (e.g. sampling row lengths from the binomial distribution), custom connectivity host code and NVCC multi-GPU reductions.
