### ISSUE TITLE
Debugging on Mac

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#57]
On Mac, debugging doesn't necessarily work as gdb is not automatically on the path. So far GeNN is just aborting when trying to debug - is there somethign more clean that we can do?

**Comment by jamesturner246** [comment]
We could allow the user to specify the path to GDB via a genn-buildmodel.sh option, like -gnupath <path>. Otherwise the script currently fails with a "command failure" message.

**Comment by esinyavuz** [comment]
Apparently gdb has been replaced by lldb some time ago. On the same line as @jamesturner246 suggested, we could choose a debugger or specify its path. 

Maybe it is time to provide such an option, as we are alse using something else than gdb on Windows as well.

**Comment by tnowotny** [comment]
``lldb -f THING_TO_DEBUG arg0 arg1``
