### ISSUE TITLE
nvcc doesn't work with XCode 7

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#58]
For mac users, I just noticed that nvcc does not work with XCode 7, offering the enigmatic error message:
nvcc fatal   : The version ('70000') of the host compiler ('Apple clang') is not supported

For now the best solution appears to be to use an older XCode version (I am using 6.4).

**Comment by jamesturner246** [comment]
The version of clang you're using isn't yet supported by the CUDA toolkit. This is a recurring problem on Fedora as well, where CUDA doesn't keep up with GCC releases. You can either hack the CUDA header which checks compiler versions - cuda/include/host_config.h - or just use an older XCode version.

**Comment by tnowotny** [comment]
We will also add a comment in the user manual about this.
