### ISSUE TITLE
Improve shared library discovery during setup.py

### ISSUE THREAD

**Issue by erolm-a** [genn-team/genn#590]
Note: this should rather be a PR, but since I made a `.patch` for a pipeline of mine, I preferred not to fork this repo. However, as it was sitting for a while I chose to make this upstream.

In short, this is the kind of "scratch-your-itch" patch that should help normalise pygenn and possibly enable a Pypi release. The patch changes the order extensions are loaded so that setup.py's module discovery is performed after swig's glue modules are generated. This way one does not need to perform `python setup.py develop` before `python setup.py build/install` to generate an egg file.

My main motivation was to enable a nix version of this package, especially to generate custom trimmed-down docker images. The builder scripts are very hard to change without breaking something along the pipeline, thus a double setup.py invocation was troublesome and frankly unnecessary.

The patch: https://github.com/giacThePhantom/genn-network-model/blob/nix-docker/genn-setup.patch

**Comment by neworderofjamie** [comment]
Thank you so much! this fixes #310 which has also been annoying me for a long time (but clearly not enough to delve into setuptools/distutils)
