### ISSUE TITLE
support for GPUs with device major == 5?

### ISSUE THREAD

**Issue by lebedov** [genn-team/genn#60]
Would it be possible to add support to [lib/src/generateALL.cc](https://github.com/genn-team/genn/blob/master/lib/src/generateALL.cc) for GPUs with device major greater than 3? If so, I would be happy to submit a pull request.

**Comment by tnowotny** [comment]
Yes, that certainly should be done now. Have you prepared a solution? Happy to consider your pull request.

**Comment by tnowotny** [comment]
Lev added the magic numbers for devices with major version 5 (thanks); James: what about major version 4?

**Comment by lebedov** [comment]
NVIDIA seems to have skipped 4 when assigning [compute capabilities](http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compute-capabilities).

**Comment by tnowotny** [comment]
Good point - now that you pointed me to it, I remember James mentioned it earlier. All good (for now)
