### ISSUE TITLE
32 bit versus 64 bit OS detection fails for linux on ARM architecture

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#62]
Just ran an example on NVIDIA Jetson TK1. It initially fails to work as it's trying to detect whether the OS is 32 bit or 64 bit (and hence /usr/local/cuda/lib or /usr/local/cuda/lib64 should be used as library path for cudart) and it fails to do so.
Underlying the failure is 
<code> uname -m / sed -e "s/i.86/32/" -e "s/x86_64/64" </code>
renders simply armv7l
<code> uname -m / sed -e "s/i.86/32/" -e "s/x86_64/64" -e "s/armv7l/32/" </code>
renders 32
and so fixes the problem for the Jetson TK1 but it's a very limited solution.
Is there a more robust way how the library path decision for -lcudart is made?

PS: Otherwise MBody1 runs straight out of the box for Jetson.

**Comment by jamesturner246** [comment]
That's cool! Looking forward to seeing it.

I can't find any env. variables containing either just "32" or just "64",
hence why uname was used. Besides adding the ARM arch, and hoping that our
users don't use Sun / other systems, I'm stumped for now. I will look
tomorrow again.
