### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by rhajizadeh** [genn-team/genn#63]
When we are trying to build an example in windows we will get a linkage error, here is the output:

d:\genn-2.1\userproject\Izh_sparse_project>generate_run.exe 1 10000 1000 1 outdi
r Izh_sparse 0 FLOAT 0
# call was: d:\genn-2.1\/userproject/tools/gen_syns_sparse_izhModel 10000 1000 0
.5 -1 inputfiles/gIzh_sparse
ee vect.size: 6399967
ee ind size: 6399967
ee count size: 8001
ei vect.size: 1600033
ei ind size: 1600033
ei count size: 8001
ie vect.size: 1600053
ie ind size: 1600053
ie count size: 2001
ii vect.size: 399947
ii ind size: 399947
ii count size: 2001

 maximum postsynaptic connection per neuron in the 1st group is 850 , fread retu
rned 1 values

 maximum postsynaptic connection per neuron in the 1st group is 311 , fread retu
rned 1 values

 maximum postsynaptic connection per neuron in the 1st group is 838 , fread retu
rned 1 values

 maximum postsynaptic connection per neuron in the 1st group is 239 , fread retu
rned 1 values
model path: d:\genn-2.1\userproject\Izh_sparse_project\model
model name: Izh_sparse
        del obj\*.obj bin\generateALL.exe 2>nul
        cl  /nologo /EHsc /DNVCC="\"C:/Program Files/NVIDIA GPU Computing Toolki
t/CUDA/v7.5/bin/nvcc.exe\"" /FI"d:\genn-2.1\userproject\Izh_sparse_project\model
\Izh_sparse.cc" /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\inclu
de" /I"d:\genn-2.1\\lib\include" /I"d:\genn-2.1\\userproject\include" src\genera
teALL.cc /Foobj\generateALL.obj /c
generateALL.cc
        cl  /nologo /EHsc /DNVCC="\"C:/Program Files/NVIDIA GPU Computing Toolki
t/CUDA/v7.5/bin/nvcc.exe\"" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\
v7.5\lib\x64\cudart.lib" obj\generateALL.obj /Febin\generateALL.exe
generateALL.obj : error LNK2019: unresolved external symbol _cudaGetErrorString@
4 referenced in function "public: void __thiscall NNmodel::setGPUDevice(int)" (?
setGPUDevice@NNmodel@@QAEXH@Z)
generateALL.obj : error LNK2019: unresolved external symbol _cudaGetDeviceCount@
4 referenced in function "public: void __thiscall NNmodel::setGPUDevice(int)" (?
setGPUDevice@NNmodel@@QAEXH@Z)
generateALL.obj : error LNK2019: unresolved external symbol _cudaGetDeviceProper
ties@8 referenced in function "int __cdecl chooseDevice(class std::basic_ostream
<char,struct std::char_traits<char> > &,class NNmodel * &,class std::basic_strin
g<char,struct std::char_traits<char>,class std::allocator<char> >)" (?chooseDevi
ce@@YAHAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AAPAVNNmodel@@V?$basic_st
ring@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z)
generateALL.obj : error LNK2019: unresolved external symbol _cudaSetDevice@4 ref
erenced in function "int __cdecl chooseDevice(class std::basic_ostream<char,stru
ct std::char_traits<char> > &,class NNmodel * &,class std::basic_string<char,str
uct std::char_traits<char>,class std::allocator<char> >)" (?chooseDevice@@YAHAAV
?$basic_ostream@DU?$char_traits@D@std@@@std@@AAPAVNNmodel@@V?$basic_string@DU?$c
har_traits@D@std@@V?$allocator@D@2@@2@@Z)
bin\generateALL.exe : fatal error LNK1120: 4 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0
\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
'bin\generateALL.exe' is not recognized as an internal or external command,
operable program or batch file.
Model build complete ...
d:\genn-2.1\\userproject\include\makefile_common_win.mk(34) : fatal error U1052:
 file 'sm_version.mk' not found
Stop.
ERROR: Following call failed with status 2:
cd model && buildmodel.bat Izh_sparse 0 && nmake /nologo /f WINmakefile clean &&
 nmake /nologo /f WINmakefile
Exiting...

**Comment by shailesh210** [comment]
This error occurs when "cudart.lib" file is not linked correctly. 
Check if your PATH to CUDA is correct and CUDA install is functional.
If all the above is correct and you are still getting the error, it might be due to the conflict in the architecture. If you have a 64-bit architecture make  sure you are using the 64-bit command prompt.
