### ISSUE TITLE
Currents of a single neuron inside a given population

### ISSUE THREAD

**Issue by Crypto1993** [genn-team/genn#71]
Good morning,
as the title of this post says I would know if it is possible (and possibly how) to change the input current of a single neuron picked from a population of N neurons, in order to simulate input noise. I know doing something like VPop1[k] allows me to access to the k-th position of the membrane potentials vector of population Pop1... does exist a similar solution for the Isyn variable?

**Comment by jamesturner246** [comment]
You can't access the Isyn accumulation variable, but you can access the inSyn<synapse group> variables for each presynaptic neuron group, which are part of the Isyn sum. See the push<synapse group>State[To|From]Device funcions in <project>_CODE/runnerGPU.cc.

There is a neater method of adding random noise to neurons at each time step, using neuron variables and extra kernel parameters. Perhaps Thomas or Esin can better explain this?

**Comment by tnowotny** [comment]
if you want an additional input current that you can manipulate, I would suggest to make a new neuron model which has an additional variable I_ext (or so) that you then can manipulate any way you like. It would probably be more efficient though if noise was generated on the GPU within the neuron code.

**Comment by Crypto1993** [comment]
Ok, but if I set the input current as a parameter of a personalized model, functions like activateDirectInput or setConstInp are useless; moreover, how can I modify a parameter for a single neuron I select in my simulation code? Is the procedure similar to the one for setting state variables by using vectors like VPop1? For example, considering an Izhikevich neuron belonging to the population Pop1, does exist a vector aPop1 or something like this for referring to the a values of my neurons?

**Comment by tnowotny** [comment]
We have deprecated activateDirectInput etc. 
As you said, whenever you introduce a variable "a" in a neuron model and have a population "Pop1" of that type, an array "aPop1" will be available.
You can set any or all element of that array and copy it to the device.

**Comment by Crypto1993** [comment]
Ok, thank you for your answer.
Another question: does the change of a single input current affect the use of STDP synapses among my personalized population?

**Comment by Crypto1993** [comment]
Are you sure that I can use a vector for picking the parameters of a single neuron?
I've created a new neuron model in which I can define the input current as a parameter, in order to have the possibility to change it whenever I prefer, but when I try to access to the i-th neuron input current by using IPop1[i] (I: name of the parameter, Pop1: name of the population), I cannot compile the project and run the simulation, because "IPop1 is undefined".

Here, there's the code:
`// Last update: 01/04/2016

#include "AL.cc"
#include "Antennal_Lobes_CODE/runner.cc"
#include "C:\genn-team-genn-8cacb78\lib\include\hr_time.cpp"
#include <stdlib.h>

int main()
{
	CStopWatch timer;
	// I pick randomly (for example) two neurons of the population.
	// Therefore, I apply to the first neuron a constant input current for a sufficient time,
	// then I wait about 4tau (synapse tau) and finally I apply the same current but for the
	// second neuron. Hence, I repeat the process for the entire simulation time: thanks to
	// STDP connection between the two neurons, the synaptic weight must increase.
	int indexFirstNeuron, indexSecondNeuron, indexSynapse;
	int indexPeriods = 0;
	// The following doubles indicate when the first (second) impulse starts (ends).
	// We impose a time constraint: timeStartSecondImpulse-(timeStartFirstImpulse+impulseDuration) = 4:5 tau.
	// Variable period is used to repeat the application of the inputs within the simulation time.
	const double current = 10.0;
	double impulseDuration = 0.010;
	double timeStartFirstImpulse = 0.0;
	double timeStartSecondImpulse = timeStartFirstImpulse + impulseDuration; //+ tau of synapse
	double period;
	
	timer.startTimer();
	allocateMem();
	initialize();
	
	ofstream output_g("output.G.dat");
	ofstream output_Isyn("output.Isyn.dat");
	ofstream output_V("output.V.dat");
	
	srand(time(NULL));
	
	system("cls");
	cout << "ANTENNAL LOBE SIMULATION" << endl;
	cout << "- No. of neurons: 10" << endl;
	cout << "- Size of synapses array: 100" << endl << endl;
	
	// REMEMBER: if pre-synaptic neurons are N and post-synaptic neurons are M, then
	// i-th synapse links (i/M)-th neuron to (i mod M)-th neuron.
		
	indexFirstNeuron = rand() % 500;
	do {
		indexSecondNeuron = rand() % 500;
	} while(indexSecondNeuron == indexFirstNeuron);
	
	indexSynapse = indexFirstNeuron * 500 + indexSecondNeuron;
	

	for (double t = 0.0; t < 100; t += 0.1) {
		stepTimeGPU(0.1);
		
		// Qui faccio agire delle correnti non nulle su due neuroni scelti dalla popolazione.
		if(t >= (indexPeriods * period + timeStartFirstImpulse) && t <= (indexPeriods * period + (timeStartFirstImpulse + impulseDuration))){
			// Impulse applied to the indexFirstNeuron-th neuron.
			IPop1[indexFirstNeuron] = current;
		}
		else{
			if(t >= (indexPeriods * period + timeStartSecondImpulse) && t <= (indexPeriods * period + (timeStartSecondImpulse + impulseDuration))){
				// Impulse applied to the indexSecondNeuron-th neuron.
				IPop1[indexSecondNeuron] = current;
			}
			else{
				// Reset input currents for both selected neurons to 0.
				IPop1[indexFirstNeuron] = 0.0;
				IPop1[indexSecondNeuron] = 0.0;
			}
		}
				
		pullPop1StateFromDevice();
		
		output_Isyn << t << "\t";
		for (int j = 0; j < 10; j++) output_Isyn << IPop1[j] << "\t";
		output_Isyn << endl;
		
		output_V << t << "\t";
		for (int j = 0; j < 10; j++) output_V << VPop1[j] << "\t";
		output_V << endl;
		
		output_g << t << "\t";
		for (int j = 0; j < 100; j++) output_g << gPop1self[j] << "\t";
		output_g << endl;
		
		indexPeriods++;
	}
	
	output_Isyn.close();
	output_V.close();
	output_g.close();
	timer.stopTimer();
	
	cout << endl << "The simulation time is: " << timer.getElapsedTime() << " seconds " << endl;
	cout << "----------------------" << endl;
	return 0;
}`

**Comment by tnowotny** [comment]
Hi Angelo,
You need to define “I” as a variable, not a parameter.
Also, don’t forget to copy it to the GPU when you change its value.
Best,
Thomas

--
Prof. Thomas Nowotny
CCNR, Sussex Neuroscience                   Phone: +44-1273-678593
Engineering and Informatics                  Fax:   +44-1273-877873
University of Sussex
Falmer, Brighton BN1 9QJ http://sussex.ac.uk/informatics/tnowotny

**Comment by Crypto1993** [comment]
ERRATA CORRIGE: Thanks for your reply, prof. Nowotny. I had already deleted my previous post because it was just a trivial mistake I made.

**Comment by Crypto1993** [comment]
There's only one problem I cannot solve, as I wrote in my previous post.
Since I'm using a model in which the input current is a variable, how can this choice work well when I use STDP synapses? I mean, if I would to apply a square wave to two neurons picked randomly from my population, since they are strongly stimulated respect the others I should obtain a stronger STDP connection between them, but it seems no g value is changed respect my initial conditions.

I report here my code if it can help:

`// Last update: 07/04/2016

#include "AL.cc"
#include "Antennal_Lobes_CODE/runner.cc"
#include "C:\genn-team-genn-8cacb78\lib\include\hr_time.cpp"
#include <stdlib.h>

int main()
{
	CStopWatch timer;
	// I pick randomly (for example) two neurons of the population.
	// Therefore, I apply to the first neuron a constant input current for a sufficient time,
	// then I wait about 4tau (synapse tau) and finally I apply the same current but for the
	// second neuron. Hence, I repeat the process for the entire simulation time: thanks to
	// STDP connection between the two neurons, the synaptic weight must increase.
	int indexFirstNeuron, indexSecondNeuron, indexSynapse;
	// The following doubles indicate when the first (second) impulse starts (ends).
	// We impose a time constrain: timeStartSecondImpulse-(timeStartFirstImpulse+impulseDuration) = 4:5 tau.
	const double current = 20.0;
	double impulseDuration = 0.5;
	double timeStartFirstImpulse = 0.0;
	double timeStartSecondImpulse = timeStartFirstImpulse + impulseDuration; //+ tau of synapse
	
	timer.startTimer();
	allocateMem();
	initialize();
	
	ofstream output_g("output.G.dat");
	ofstream output_I("output.I.dat");
	ofstream output_V("output.V.dat");
	
	srand(time(NULL));
	
	system("cls");
	cout << "ANTENNAL LOBE SIMULATION" << endl;
	cout << "- No. of neurons: 10" << endl;
	cout << "- Size of synapses array: 100" << endl << endl;
	
	// REMEMBER: if pre-synaptic neurons are N and post-synaptic neurons are M, then
	// i-th synapse links (i/M)-th neuron to (i mod M)-th neuron.
		
	indexFirstNeuron = rand() % 10;
	do {
		indexSecondNeuron = rand() % 10;
	} while(indexSecondNeuron == indexFirstNeuron);
	
	indexSynapse = indexFirstNeuron * 10 + indexSecondNeuron;
	cout << "Selected neurons: " << indexFirstNeuron << " - " << indexSecondNeuron << endl;
	cout << "Synapsis index: " << indexSynapse << endl;
	

	for (double t = 0.0; t < 10; t += 0.01) {
		stepTimeGPU(0.01);
		
		// Qui faccio agire delle correnti non nulle su due neuroni scelti dalla popolazione.
		if(t >= timeStartFirstImpulse && t <= (timeStartFirstImpulse + impulseDuration)){
			// Impulse applied to the indexFirstNeuron-th neuron.
			IPop1[indexFirstNeuron] = current;
		}
		else{
			if(t >= timeStartSecondImpulse && t <= (timeStartSecondImpulse + impulseDuration)){
				// Impulse applied to the indexSecondNeuron-th neuron.
				IPop1[indexSecondNeuron] = current;
			}
			else{
				// Reset input currents for both selected neurons to 0.
				IPop1[indexFirstNeuron] = 0.0;
				IPop1[indexSecondNeuron] = 0.0;
				timeStartFirstImpulse = timeStartSecondImpulse + impulseDuration;
				timeStartSecondImpulse = timeStartFirstImpulse + impulseDuration;
			}
		}
		
		pushPop1StateToDevice();
		
		pullPop1StateFromDevice();
		
		output_I << t << "\t";
		for (int j = 0; j < 10; j++) output_I << IPop1[j] << "\t";
		output_I << endl;
		
		output_V << t << "\t";
		for (int j = 0; j < 10; j++) output_V << VPop1[j] << "\t";
		output_V << endl;
		
		output_g << t << "\t";
		for (int j = 0; j < 100; j++) output_g << gPop1self[j] << "\t";
		output_g << endl;
		
	}
	
	output_I.close();
	output_V.close();
	output_g.close();
	timer.stopTimer();
	
	cout << endl << "The simulation time is: " << timer.getElapsedTime() << " seconds " << endl;
	cout << "----------------------" << endl;
	return 0;
}`

**Comment by tnowotny** [comment]
Hi Angelo,
The code looks alright except that you don’t seem to pull the synapse state from the device. So the g output will be the initial value …
Best,
Thomas

--
Prof. Thomas Nowotny
CCNR, Sussex Neuroscience                   Phone: +44-1273-678593
Engineering and Informatics                  Fax:   +44-1273-877873
University of Sussex
Falmer, Brighton BN1 9QJ http://sussex.ac.uk/informatics/tnowotny

**Comment by Crypto1993** [comment]
You are right! Thank you.
