### ISSUE TITLE
New parallelisation in synapse kernel omits event threshold re-check

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#73]
I noticed that when the new parallelization method along pre-synaptic neurons is used, the event threshold is not checked again in the synapse kernel. Is this on purpose? It would lead to inconsistencies between the result between both parallelization methods if two synaptic groups were to define different events for the same pre-synaptic neuron population.

**Comment by esinyavuz** [comment]
Not sure if I can say that it is "on purpose", it was kind of a forced choice for the type of synapses we have. It wouldn't make sense to use that connectivity for models that rely on presynaptic neuron variables. As with the new method parallelisation is done at the postsynaptic neurons, we cannot copy a presynaptic neuron variable in the shared memory as we do in the classical method. But you are right about possible inconsistencies. An alternative would be to read the values directly from the device memory, but it would probably be costly in execution time as the memory copy of these values will most likely not be concurrent. Do we have an example which uses sparsely connected synapses that make use of events? If we do I can try.

**Comment by tnowotny** [comment]
I have created the feature test that can detect this problem. In order to fix, the re-check in the synapse kernel needs to be reinstated; however, to avoid unnecessary overheads, the recheck should only be performed if it is necessary. When is it necessary? There need to be at least two synapse populations with the same pre-synaptic neuron population and both need to define events. Furthermore, a check is only necessary if 
a) the events are different
b) for the less frequent event, if one event implies the other
How much we want to descend into this analysis I am not sure but I think we should test at least for the condition of 2 or more event definitions.

**Comment by tnowotny** [comment]
The main problem is fixed and the feature test preVarsInSimCodeEvnt_sparseInv does now pass. I think the check for when it is actually necessary to re-check the spike event condition is still on the TODO list.
