### ISSUE TITLE
extraGlobalPostSynapseParameters

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#74]
Do we want to allow for extraGlobalPostSynapseParameters?

**Comment by tnowotny** [comment]
Maybe overkill as this is pretty much equivalent to having an appropriate neuronKernelParameter? But what about multiple post-synapse populations onto the same neuron population?

**Comment by esinyavuz** [comment]
I guess what you suggest is a solution. It wouldn't be a problem for multiple post-synapse populations onto the same neuron, as these parameters are only used if mentioned, right? So in case we need different post-synapse rules used by a neuron population, each requiring a different  extraGlobalPostSynapseParameter-like parameter, one can define two different postsynapse groups for each of these, and two distinct extraGlobalNeuronKernelParameters which are read byeither of these postsynapse rules. In short I think that we don't need anything extra for this.
