### ISSUE TITLE
problem with testprojects.sh upon first run

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#77]
Unless I am mistaken the testprojects.sh script by default tries to reuse input files e.g. in the MBody* projects. If it's run for the very first time and the projects weren't run previously or were run previously but with the wrong sizes then the testprojects script will lead to failed runs (plain old segmentation faults).

**Comment by esinyavuz** [comment]
There is one global flag `firstrun  = false` which can be manually set, but there are also individual flags for every project which should be set if the benchmarking directory does not exist. What is possible is that you have called the script and stopped it before it could generate results (or the project failed before generating results). 

I'm not sure whether there is a straightforward solution to this, and to the possible problem of running with different sizes. The idea behind is to run the same model each time to compare it to a previous version that we know to work.

**Comment by jamesturner246** [comment]
Issue resolved in commit 10a4fde.
