### ISSUE TITLE
Spiking activity tracing

### ISSUE THREAD

**Issue by Crypto1993** [genn-team/genn#79]
Good morning,
I would to save in a file the information related to the spiking activity of my own population. In particular, this file should contain both the spiking neuron index and the time instant at which the spike occurs. I've given a look to the MBody1_project but I can't understand which variables are involved in this kind of operation.

Thanks for your answers.

**Comment by jamesturner246** [comment]
The variable glbSpk<group name> holds the indexes of the neurons which spiked in the current time step (after the neuron kernel executes). glbSpkCnt<group name> is an unsigned integer which records how many neurons have spiked in this time step. So to get the indexes of all the currently spiking neurons in group 'MyGroup', I would write:

for (int i = 0; i < glbSpkCntMyGroup; i++) {
    unsigned int spikingNrn = glbSpkMyGroup[i];
}

Don't forget to 'pull<group name>SpikesFromDevice();' beforehand, though!

All the best,
James.

**Comment by esinyavuz** [comment]
There is a function called `output_spikes` in `MBody1_project/model/map_classol.cc`. If you look at what it does and how it is called in `MBody1_project/model/classol_sim.cu` (along with copying the spikes from the device as James pointed out), it can give you an idea.
