### ISSUE TITLE
STDP learning issues

### ISSUE THREAD

**Issue by Crypto1993** [genn-team/genn#80]
I'm still trying to understand why the situation I'm going to describe you happens.

I have two simple neurons connected all together via LEARN1SYNAPSE with the same parameters of the Mbody1_project. The neuron 0 (the first) is characterized by a variable input current that describes a square wave, while the neuron 1 (the second) has no current. Therefore, this last neuron cannot have a meaningful membrane potential variation (it must be constant). This sounds correct, of course... but why does the conductance g of the synapse from 0 to 1 increase even if the second neuron has not any post-synaptic activity?

This is the .cc file:
`// Last update: 15/04/2016

#define DT	0.1

#include "C:\genn-team-genn-8cacb78\lib\include\modelSpec.cc"
#include "C:\genn-team-genn-8cacb78\lib\include\modelSpec.h"
			
void modelDefinition(NNmodel &model){
		initGeNN();
		model.setName("Antennal_Lobes");
		
		double _InitNeuron[3]{
			-65.0,							// 0 - V(0): initial value of membrane potential
			-14.0,							// 1 - U(0): initial value of recovery variable
			0.0								// 2 - I: applied current
		};
		
		double _NeuronParameters[5]{
			0.0,							// 0 - paramater 'a' of Izhikevich neuron
			-0.1,							// 1 - parameter 'b' of Izhikevich neuron
			-55.0,							// 2 - parameter 'c' of Izhikevich neuron
			0.0,							// 3 - parameter 'd' of Izhikevich neuron
		};
			
		double _InitSynapse[2]{
			0.01,           				// 0 - g: synaptic conductance
			0.01,		  					// 1 - graw: raw synaptic conductance
		};
			
		double _SynapseParameters[11]{
			50.0,               			// 0 - TLRN: time scale of learning changes
			50.0,               			// 1 - TCHNG: width of learning window
			50000.0,            			// 2 - TDECAY: time scale of synaptic strength decay
			100000.0,           			// 3 - TPUNISH10: Time window of suppression in response to 1/0
			200.0,              			// 4 - TPUNISH01: Time window of suppression in response to 0/1
			0.015,              			// 5 - GMAX: Maximal conductance achievable
			0.0075,             			// 6 - GMID: Midpoint of sigmoid g filter curve
			33.33,              			// 7 - GSLOPE: slope of sigmoid g filter curve
			10.0,               			// 8 - TAUSHIFT: shift of learning curve
			0.00006             			// 9 - GSYN0: value of syn conductance g decays to
		};
		
		double * _InitPostSynaptic = NULL;
		
		double _PostSynapticVariables[2]{
			5.0,            				// 0 - tau_S: decay time constant for S [ms]
			0.0		  						// 1 - Erev: Reversal potential
		};
		
		model.addNeuronPopulation("AL",2,IZHIKEVICH_VARIABLE_INPUT,_NeuronParameters,_InitNeuron);
		model.addSynapsePopulation("AL_SELF",LEARN1SYNAPSE,ALLTOALL,INDIVIDUALG,NO_DELAY,EXPDECAY,"AL","AL",_InitSynapse,_SynapseParameters,_InitPostSynaptic,_PostSynapticVariables);
		
		model.finalize();
		
}`

and this is the .cu file:
`// Last update: 15/04/2016

#include "AL.cc"
#include "Antennal_Lobes_CODE/runner.cc"
#include "C:\genn-team-genn-8cacb78\lib\include\hr_time.cpp"
#include <stdlib.h>

#define NEURONS 2
#define SYNAPSIS NEURONS*NEURONS
#define DURATION_TIME 30
#define STEP_TIME 0.01

int main()
{
	CStopWatch timer;
	// I apply to a first neuron a constant input current for a sufficient time,
	// then I wait about 4tau (synapse tau) and finally I apply the same current for a
	// second neuron. Hence, I repeat the process for the entire simulation time: thanks to
	// STDP connection between the two neurons, the synaptic weight must increase.
	int indexFirstNeuron, indexSecondNeuron, indexSynapse;
	int checkTime = 0;
	
	const double currentFirstNeuron = 20.0;
	const double currentSecondNeuron = 0.0;
	const double startDelay = 0.1;
	const double deltaTime = 4; // 4 times higher the variable "tau" of the post-synaptic model ?
	
	// The following doubles indicate when the first (second) impulse starts (ends).
	const double impulseDuration = 1.0;
	double timeStartFirstImpulse = startDelay;
	double timeStartSecondImpulse = timeStartFirstImpulse + impulseDuration + startDelay; //+ tau of synapse
	
	timer.startTimer();
	allocateMem();
	initialize();
	
	ofstream output_g("output.G.dat");
	ofstream output_I("output.I.dat");
	ofstream output_U("output.U.dat");
	ofstream output_V("output.V.dat");
	
	srand(time(NULL));
	
	system("cls");
	cout << "ANTENNAL LOBE SIMULATION" << endl;
	cout << "- No. of neurons: " << NEURONS << endl;
	cout << "- Size of synapses array: " << SYNAPSIS << endl;
	cout << "--------------------------------" << endl;
	
	// REMEMBER: if pre-synaptic neurons are N and post-synaptic neurons are M, then
	// i-th synapse links (i/M)-th neuron to (i mod M)-th neuron.
		
	indexFirstNeuron = 0;
	indexSecondNeuron = 1;
	
	indexSynapse = indexFirstNeuron * NEURONS + indexSecondNeuron;
	cout << "Selected neurons: " << indexFirstNeuron << " - " << indexSecondNeuron << endl;
	cout << "Synapsis index: " << indexSynapse << endl;
		
	// Adding some noise to the initial conditions of the neurons
	srand(time(NULL));
	for (int i = 0; i < NEURONS; i++){
		// Old school solution.
		VAL[i] += 5*((double)rand() / (double)RAND_MAX);
		UAL[i] += 5*((double)rand() / (double)RAND_MAX);
	}
	pushALStateToDevice();
	
	// Square wave input currents for each neuron: when the first is firing, the second is at rest and viceversa.	
	for (double t = 0.0; t < DURATION_TIME; t += STEP_TIME) {
		stepTimeGPU(STEP_TIME);
				
		pullALStateFromDevice();
		pullAL_SELFStateFromDevice();
		
		// Removing synaptic connections whose influence must be neglected.
		// In this case, because my connection is estabilished from neuron 0 to neuron 1, the
		// only synapse I'm interested in is the 0*2+1=1st synapse.
		gAL_SELF[0] = 0.0;
		gAL_SELF[2] = 0.0;
		gAL_SELF[3] = 0.0;
		pushAL_SELFToDevice();
		
		if(t <= DURATION_TIME){
			if(t >= timeStartFirstImpulse && t <= (timeStartFirstImpulse + impulseDuration)){
				// Impulse applied to the indexFirstNeuron-th neuron.
				IAL[indexFirstNeuron] = currentFirstNeuron;
			}
			else{
				if(t >= timeStartSecondImpulse && t <= (timeStartSecondImpulse + impulseDuration)){
					// Impulse applied to the indexSecondNeuron-th neuron.
					IAL[indexSecondNeuron] = currentSecondNeuron;
					checkTime = 1;																							// Comment if you don't want periodic square waves.
				}
				else{
					// Reset input currents for both selected neurons to 0.
					IAL[indexFirstNeuron] = 0.0;
					IAL[indexSecondNeuron] = 0.0;
					if(checkTime == 1){
						// If the previous condition is verified, I'm entering in a new period.
						timeStartFirstImpulse = timeStartFirstImpulse + impulseDuration + deltaTime;
						timeStartSecondImpulse = timeStartFirstImpulse + impulseDuration + startDelay;
						checkTime = 0;
					}
				}
			}
		}
		else{
			IAL[indexFirstNeuron] = 0.0;
			IAL[indexSecondNeuron] = 0.0;
		}
		
		pushALStateToDevice();
		pushAL_SELFStateToDevice();
		
		// Writing on files.		
		output_I << t << "\t";
		for (int j = 0; j < NEURONS; j++) output_I << IAL[j] << "\t";
		output_I << endl;
		
		output_U << t << "\t";
		for (int j = 0; j < NEURONS; j++) output_U << UAL[j] << "\t";
		output_U << endl;
		
		output_V << t << "\t";
		for (int j = 0; j < NEURONS; j++) output_V << VAL[j] << "\t";
		output_V << endl;
		
		output_g << t << "\t";
		for (int j = 0; j < SYNAPSIS; j++) output_g << gAL_SELF[j] << "\t";
		output_g << endl;	
		
	}
	
	output_I.close();
	output_V.close();
	output_U.close();
	output_g.close();
	
	cout << endl;
	
	timer.stopTimer();
	
	cout << "The simulation time is: " << timer.getElapsedTime() << " seconds " << endl;
	cout << "---------------------------------------" << endl;
	return 0;
}`

When I plot the content of each file I create during the simulation, the results are the following:
![vi](https://cloud.githubusercontent.com/assets/11614831/14558602/9f65a15c-0303-11e6-8e92-1d44c9523d4b.png)

![g](https://cloud.githubusercontent.com/assets/11614831/14558603/9f66f1a6-0303-11e6-9a18-7d840830b4f1.png)

**NOTE**: I've noticed that ALL the conductances of my set of synapses increase, therefore I've fixed conductances of synapse from 0 to 0, from 1 to 0 and from 1 to 1 equal to 0. In any case, I cannot explain why even without a post-synaptic spiking activity g values increase.

**Comment by tnowotny** [comment]
Hi - there are a couple of issues with this. The LEARN1SYNAPSE is not a simple STDP model and many find it confusing. 
a) It follows an STDP curve like in the attached, where unpaired pre- and post-synaptic spikes incur a negative increment in g. But also, the time of the last spike in each neuron, "sTAL" in your case, is (somewhat arbitrarily) initialised to -10.0 ms. That's something to bear in mind - if neurons never spike, these spike times are used.
b) The raw synaptic conductance graw is subject to the STDP rule. The resulting synaptic conductance is a sigmoid filter of graw. Furthermore, if you set g but not graw, the synapse will revert to the value that corresponds to graw.
I am not sure why you are getting increases in g on your synapse but it's probably a good idea to fix the problems first (setting graw correctly) and then saving and plotting g and graw. 
From map_classol.cc (MBody1 userproject):
`    for (int i= 0; i < model.neuronN[1]*model.neuronN[3]; i++) {
	if (gKCDN[i] < 2.0*SCALAR_MIN){
	    cnt++;
	    fprintf(stdout, "Too low conductance value %e detected and set to 2*SCALAR_MIN= %e, at index %d \n", gKCDN[i], 2*SCALAR_MIN, i);
	    gKCDN[i] = 2.0*SCALAR_MIN; //to avoid log(0)/0 below
	}
	scalar tmp = gKCDN[i] / myKCDN_p[5]*2.0 ;
	gRawKCDN[i]=  0.5 * log( tmp / (2.0 - tmp)) /myKCDN_p[7] + myKCDN_p[6];
    }
    cerr << "Total number of low value corrections: " << cnt << endl;`
Plotting g and graw then should make everything a lot easier to understand. By the way - you can't set these fully to 0, as this leads to graw= -infinity and as far as I remember we didn't support this as an exceptional case. Therefore, g needs to be some nominal value > 0 (but can be extremely small of course so that it acts like it's 0).

Finally, if you want a more straightforward STDP rule I would suggest implementing a new one.

![learn1synapse_explain](https://cloud.githubusercontent.com/assets/5477463/14613187/2534202e-0593-11e6-9ef8-48762d2a8d4a.png)

PS: I did these drawings from memory - I hope I remembered all parameter bindings correctly.

**Comment by tnowotny** [comment]
will add some of this into the documentation.
