### ISSUE TITLE
Depreciated add population functions

### ISSUE THREAD

**Issue by jamesturner246** [genn-team/genn#81]
We seem to have a lot of redundant addSynapse (5) and addNeuron (4) functions lying about now. Which ones are realistically still being used?

**Comment by esinyavuz** [comment]
There is one accepting vectors and one using pointer arrays as arguments for each. The others are wrappers, one of them gives a "deprecated" warning for `addSynapsePopulation`. I think all are useful except for this last. Maybe we can change this one to give an error before exiting and remove completely in the next release.

**Comment by jamesturner246** [comment]
Done in aec3fb2.
