### ISSUE TITLE
Are delayed synapses and sparse connectivity tested together?

### ISSUE THREAD

**Issue by esinyavuz** [genn-team/genn#82]
I suspect that delayed synapses are not functional when sparse connectivity is used. Has anyone tried to run a model which uses both in the same synapse population?

Do we want to add a feature test on that?

**Comment by tnowotny** [comment]
I believe testPreVarsInSimCode_sparse is testing exactly that.

**Comment by esinyavuz** [comment]
Indeed it does, thanks! I guess that things are working fine if it is there and we haven't noticed any problems earlier, but I'll check out and update here in any case.

**Comment by esinyavuz** [comment]
Yes it is functional, sorry my bad. I didn't realise that it was hidden in `offsetPre`.
