### ISSUE TITLE
Support code not implemented for inverse synapse Span

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#84]
I think there may be some code missing for defining the namespace for support code if the "inverse span" for sparse synapses in the synapse kernel is used. Let's make sure it's correct.

**Comment by tnowotny** [comment]
We probably need to have a feature test on this.

**Comment by tnowotny** [comment]
I think it's all good but would feel better with feature tests on support codes.

**Comment by neworderofjamie** [comment]
``synapse_support_code_post_learn`` feature test now covers this - gosh I think that was one of my first additions!
