### ISSUE TITLE
Automatic code formatting

### ISSUE THREAD

**Issue by jamesturner246** [genn-team/genn#86]
We may have a solution to our messy code output; The `astyle` command. It's already present on my Fedora 23 install, but not sure about Ubuntu / Debian / Mac. Can you test this on Mac, Thomas, and on Ubuntu, Esin?

It takes a C or C++ input and makes it nice and pretty. There's also a MS Visual Studio extension, for Windows users: 

https://visualstudiogallery.msdn.microsoft.com/2f3f04cd-2866-4e47-a671-d1cc9cc3fb02

We could have a tiny post-processing stage where this is run on all the output files.

**Comment by esinyavuz** [comment]
I could install it using apt on ubuntu. But how does it work? Will people need to install it to run GeNN? If it will not impose any dependencies I'm happy to try.

**Comment by jamesturner246** [comment]
It would be an optional thing then, I guess. There's also `clang-format` for clang users - i.e. Mac users. It can be run if either exist.

**Comment by neworderofjamie** [comment]
As I was attempting to read some auto-generated code I was thinking - we have most of what we need for improving this (I am especially thinking of the indentation) already in``CodeHelper``. Rather than writing directly to the ``ostream`` we could change ``CodeHelper`` to own the ``ostream`` of the file being generated and add a ``writeLine`` method to it which strips off any existing leading whitespace and adds back in the correct amount.

**Comment by tnowotny** [comment]
I would be happy with such a solution. At times we probably need to tidy up some of the generator code to no write lines incrementally but collect the content in a string incrementally and then write it using this ...?

**Comment by neworderofjamie** [comment]
I think one of the good things about ``std::ofstream`` is that it does buffering for you so there shouldn't be any particular problem

**Comment by tnowotny** [comment]
I am not sure we are talking about the same thing: I meant that you cannot pass half a code line into your new ```<<```, have it formatted and then pass another bit of the same line in the same way, as it would be formatted as if it was a new line (i.e. extra space) ... or am I missing something? I guess you could detect ```endl``` in the overloaded ```<<``` to safeguard against it and leave the original code generation code alone ... is that what you had in mind?

**Comment by neworderofjamie** [comment]
I was thinking you would probably detect ``endl`` in the code as that would also mean this approach would be able to format user code strings.

**Comment by tnowotny** [comment]
that would work ... shall we call it a "codestream" ;-)

**Comment by neworderofjamie** [comment]
I think you mean CodeStream :tm: :smile:

**Comment by neworderofjamie** [comment]
Implemented in #150
