### ISSUE TITLE
README.txt -- is it obsolete?

### ISSUE THREAD

**Issue by esinyavuz** [genn-team/genn#87]
README.txt used to be the only documentation in the first releases and therefore it contained things that we now explain more in details in the user manual/documentation. Moreover, many things in there are outdated.

Should we remove all the details and point the users to online documentation, or keep the same file but fix the mistakes? It also goes on the front page of the github project directory so we should keep it up-to-date.

**Comment by tnowotny** [comment]
I would update and keep it. It's often the first place people look.

**Comment by jamesturner246** [comment]
It's also used by github to generate the instructions on the main genn repo page: 

https://github.com/genn-team/genn

(scroll down)

**Comment by esinyavuz** [comment]
I agree with @jamesturner246. We could also make it markdown or rst and link relevant pages in the documentation. I can do it if noone else started to work on this already.

**Comment by tnowotny** [comment]
I think it's all yours if you want to do it.

**Comment by esinyavuz** [comment]
I have now updated the README for the latest version. We now have it both in .md and .txt. I think .md looks really nice on the front page, and markdown is almost plain text so we can get rid of README.txt. Let me know what you think and then we can close the issue.

@jamesturner246 , adding `DT` in the model.cc is mentioned in the README, and I think it will be obsolete after the changes that you have been working on. I leave it to you to update to the final version when it is ready.

**Comment by jamesturner246** [comment]
OK, no problem. I've actually just added some code to set the model DT from a DT macro, if it exists, for backward compatibility. I'll update it when I'm done.

The README looks nice! We can delete the README.txt, but should be add a symlink to README.md called README.txt for Windows users? The ".txt" was because my Windows box didn't know how to open it by default.

**Comment by esinyavuz** [comment]
Ah I didn't know that. Yes, symlink to .md from .txt could be an option.

Thanks for dealing with the backwards compatibility of the DT stuff!
