### ISSUE TITLE
Redaclaration of modelDefinition vars when linking independently compiled objects

### ISSUE THREAD

**Issue by jamesturner246** [genn-team/genn#88]
I'm having some problems separating out the model.cc file containing `modelDefinition()` for separation. DT is either included via model.cc into generateALL.cc, and not accessible to other files requiring DT, or is included everywhere, giving multiple redeclaration errors. 

I suggest, rather than passing it as a macro, setting it via a call to a `NNmodel` function inside `modelDefinition()`, if not setting DT via GENN_PREFERENCES, or similar. What are our preferences?

**Comment by tnowotny** [comment]
James, after some more thinking I think you may still get into trouble even if you move the DT  definition as we discussed. The user projects that include the model definition file to have access to the model will also likely have the problem with multiple instances of the variables defined in it, won't they?

**Comment by jamesturner246** [comment]
If we have DT in model, and if `#define DT 0.5` (or `const scalar DT = 0.5`), then they will be in different namespaces, so it's OK. Then we have `DT` or `model.DT`, which wont conflict.

I've had a look at modelSpec and this change means that the `initDerived*Para` functions will have to be called *after* the model is finalised - i.e. after DT is chosen definitely - since these functions all depend on DT. I can just change these functions to loop over all populations and initialise params in the `model.finalize()` function, kind of like I did with the padSum size calculation code.

**Comment by tnowotny** [comment]
But be careful, the derived parameters have to be fixed BEFORE the new combined even threshold condition is processed in initLearnGrps.
My comment above related to other variables than DT which could conflict if the model definition is included several times (independent of the DT issue).

**Comment by jamesturner246** [comment]
I see it. I'll make sure that initLearn is called after the derived parameters are done.

As for the model definition variables, I just tried it and the compiler doesn't seem to mind, for some reason... I'm investigating it further.

**Comment by jamesturner246** [comment]
OK, `modelDefinition` and its files are not included into the user's project unless the user explicitly includes it. `modelDefinition` won't be included in with libgenn.a, since that is compiled separately from generateALL. 

The only time an issue occurs is if the user explicitly includes the model file more than once in the project.
