### ISSUE TITLE
Define new Synapse Model

### ISSUE THREAD

**Issue by emurgano** [genn-team/genn#90]
Hi to everybody. I have some issues to define a new synapse with the STDP rule.
I have to implement the following equations: 
![legge_dw](https://cloud.githubusercontent.com/assets/19346774/15249072/0379ad20-191e-11e6-8409-9618f1d1fde4.png) (1)
![legge_e](https://cloud.githubusercontent.com/assets/19346774/15249071/037978aa-191e-11e6-8102-2b1a0bb9c240.png) (2)
![legge_i](https://cloud.githubusercontent.com/assets/19346774/15249074/037b229a-191e-11e6-816b-35b9c0849007.png) (3)
![legge_w](https://cloud.githubusercontent.com/assets/19346774/15249073/0379ae74-191e-11e6-9470-f691f777d781.png) (4)

where Δt=t_pre-t_post (in (1)), t_i= time when the i-th neuron fire a spike (in (3)) and w(i,j) is the synaptic weight between a generic i-th neuron pre-synaptic and the j-th post-synaptic neuron.

I don't find much in your wiki, so the definition of the model isn't corrent: in the function "prepareWeightUpdateModels()" in utils.h, I have defined, with a weightUpdateModel object, the laws (1) and (4), with this following code: 

`wuS.varNames.clear();
    wuS.varTypes.clear();
	wuS.pNames.clear();
	wuS.dpNames.clear();
	wuS.varNames.push_back(tS("w"));
	wuS.varTypes.push_back(tS("float"));
	// il parametro deltaW è dipendente da i parametri A+, A-, deltat, tau+, tau-
	// La corrente Isyn è definita dal modello post-synaptic
	wuS.pNames.push_back(tS("A+"));
	wuS.pNames.push_back(tS("A-")); 
	wuS.pNames.push_back(tS("tau+"));
	wuS.pNames.push_back(tS("tau-"));

	wuS.simCode= tS("$(addtoinSyn)=$(w); \n\
	$(updatelinsyn); \n\
	scalar dt=($(sT_pre)-($(sT_post))); \n\
	scalar dw=0.0; \n\
	if (dt<0.0) dw=$(A+)*exp(dt/($(tau+))) ; \n\
	else dw=$(A-)*exp(-(dt/($(tau-)))); \n\
	if (t%3000==0) $(w)=(0.95*($(w))+(dw)); \n\
	else ($(w))=$(w)+dw; \n\
	if (($(w))>= 8) $(w)=8; \n\
	else if (($(w))<=-8) $(w)=-8;"); // resta da fare l'implementazione della legge di w 
	
	wuS.simLearnPost=tS("scalar dt=($(sT_pre)-($(sT_post))); \n\
	scalar dw=0.0; \n\
	if (dt<0.0) dw=$(A+)*exp(dt/($(tau+))) ; \n\
	else dw=$(A-)*exp(-(dt/($(tau-)))); \n\
	if (t%3000==0) $(w)=(0.95*($(w))+(dw)); \n\
	else ($(w))=$(w)+dw; \n\
	if (($(w))>=8) $(w)=8.0; \n\
	else if (($(w))<=-8) $(w)=-8.0;");
	 wuS.needPreSt= TRUE;
	 wuS.needPostSt= TRUE;
	weightUpdateModels.push_back(wuS);
	STDP=weightUpdateModels.size()-1;`

Instead, for the equations related to the synaptic current, (laws (2) and (3)), I define a new postSynModel object in the function "preparePostSynModels()" in utils.h, with this code: 

`ps.varNames.clear();
  ps.varTypes.clear();
  ps.pNames.clear();
  ps.dpNames.clear();
  
  ps.postSynDecay=tS("");
  ps.postSyntoCurrent=tS("$(inSyn)");
  
  postSynModels.push_back(ps);
  STDP_I = postSynModels.size() -1;`

and, in the file "extra_postsynapses.h", this code: 

`ps.varNames.clear();
  ps.varTypes.clear();
  ps.pNames.clear();
  ps.dpNames.clear();
  
  //la corrente sinaptica I è funzione del peso sinaptico w e della funzione e
  
  ps.varNames.push_back(tS("w_PS"));
  ps.varTypes.push_back(tS("float"));
  
  ps.varNames.push_back(tS("e"));
  ps.varTypes.push_back(tS("float"));
  
  ps.pNames.push_back(tS("tau")); 

  ps.postSyntoCurrent=tS("\n\
  0; \n\
  if ((t-($(sT_pre)))>=0) \n\
  $(e)=((t-($(sT_pre)))/$(tau)*exp(1-((t-($(sT_pre)))/($(tau))));  \n\
  else $(e)=0; \n\
  float Isyn_NB=0; \n\
  { \n\
  float w_ini_PS=$(inSyn); \n\
  $(w_PS)=$(w_PS)+($(w_ini_PS)); \n\
  Isyn_NB+=$(e)*($(w_PS));} \n\
  ");
  
  ps.postSynDecay = tS("0");
  
  postSynModels.push_back(ps);`

I have defined the postSynDecay method equals to 0, bacause the decay of the synaptic current is implemented in (2); but I'm a little confused to this code because I don't know exactly how this part works. 

So I hope you can help me to define a new synapse model! 

Last question: in this simulator, the synaptic weight is equal to the conductance synaptic, or they are different? In this case, what is the relationship among them?

**Comment by tnowotny** [comment]
Hi,
there is a lot going on in your model and not all of it is easily implemented in GeNN (or other simulators I'm afraid). Here are some initial points/questions:
1. Is (3) supposed to be applied every time step (I assume it is)?
2. Is the sum in (3) over all previous spike times t_i? This is a serious issue as it would, in combination with (2) imply that one would need to keep and loop over the entire spiking history at every time step.

Regarding your code, 
a) it is important to keep in mind that simCode (and simLearnPost) are only used whenever a pre-synaptic (or post-synaptic) spike occurs. Therefore,
 ```C++
if (t%3000==0) $(w)=(0.95*($(w))+(dw)); \n\
```
is bound to fail unless there is a spike exactly at t == 3000.
(Besides, as t is floating point, you may want to do 
```C++
if (fmod(t,3000.0) < 1e-4) $(w)=0.95*$(w); \n\
```
b) I note that you are using "A+" as a parameter name; this is going to fail as it is not a valid variable name in C/C++. Please use Ap or A_p or something similar.
c) As the simCode only is executed when spikes occur and the postSyntoCurrent snippet acts on the already summed inputs from all incoming synapses,  you probably want to try to use the mechanism of events to implement your current equation (3). Note that this is extremely inefficient but as your model can unlike exponential decay of PSPs not be reformulated as a common decay on a summed PSP, this may be the only option. Here is some rough code that might do the job:
(note that you are still only considering the latest spike when doing this, i.e. the sum in (3) is only across all presynaptic neurons and not across all pre-synaptic spikes in each of the neurons.)
DISCLAIMER: I didn't test this but believe it should be fairly accurate.
```C++
/*--------------------------------------------------------------------------
   Author: Thomas Nowotny
  
   Institute: Center for Computational Neuroscience and Robotics
              University of Sussex
	      Falmer, Brighton BN1 9QJ, UK 
  
   email to:  T.Nowotny@sussex.ac.uk
  
   initial version: 2016-05-13
  
--------------------------------------------------------------------------*/

//--------------------------------------------------------------------------
/*! \file myModel.cc

\brief This file contains the model definition 
*/
//--------------------------------------------------------------------------

#define DT 0.1  //!< This defines the global time step at which the simulation will run
#include "modelSpec.h"
#include "modelSpec.cc"


// put global variables, e.g. for initial values etc, here

//--------------------------------------------------------------------------
/*! \brief This function defines a model with novel synapses
 */
//--------------------------------------------------------------------------

void modelDefinition(NNmodel &model) 
{	
    // initialize standard models
    initGeNN();
 /******************************************************************/		
  // define a user-defined synapse
  model.setPrecision(float);

  postSynModel ps;
  ps.varNames.clear();
  ps.varTypes.clear();

  ps.varNames.push_back(tS("EEEE")); 
  ps.varTypes.push_back(tS("scalar"));  

  ps.pNames.clear();
  ps.dpNames.clear(); 
  
  ps.pNames.push_back(tS("tau")); 
  ps.dpNames.push_back(tS("expDecay"));

  ps.postSynDecay=tS("");
  ps.postSyntoCurrent=tS("$(inSyn)");
  postSynModels.push_back(pstest);
  unsigned int POSTSYN1=postSynModels.size()-1; //this index to be used in addSynapsePopulation*/

  weightUpdateModel wuS;
  //no need to clear anything if using a new object like this
  wuS.varNames.push_back(tS("w"));
  wuS.varTypes.push_back(tS("scalar"));
  // code for presynaptic spike:
  wuS.simCode= tS("scalar dt=($(sT_pre)-($(sT_post))); \n\
     scalar dw=0.0; \n\
     if (dt<0.0) dw=$(A+)*exp(dt/($(tau+))) ; \n\
     else dw=$(A-)*exp(-(dt/($(tau-)))); \n\
     ($(w))=$(w)+dw; \n\
     if (($(w))>= 8) $(w)=8; \n\
     else if (($(w))<=-8) $(w)=-8;"); 
  wuS.evntThreshold= tS("1"); // do this all the time
  wuS.simCodeEvnt= tS("scalar eps; \n\
     if ((t-($(sT_pre))) >= 0) \n\
     eps=((t-$(sT_pre))/$(tau)*exp(1.0-(t-$(sT_pre))/$(tau)); \n\
     else eps=0; \n\
     $(addtoinSyn)=$(w)*eps; \n\
     $(updatelinsyn); \n\
     if (fmod(t,3000.0) < 1e-4) $(w)= 0.95*$(w);");
  wuS.simLearnPost=tS("scalar dt= $(sT_pre)-$(sT_post); \n\
     scalar dw= 0.0; \n\
     if (dt < 0.0) dw= $(Ap)*exp(dt/$(taup)); \n\
     else dw= $(Am)*exp(-(dt/$(taum))); \n\
     $(w)=$(w)+dw; \n\
     if ($(w)>=8.0) $(w)=8.0; \n\
     else if ($(w)<=-8.0) $(w)=-8.0;");
  wuS.needPreSt= TRUE;
  wuS.needPostSt= TRUE;
  weightUpdateModels.push_back(wuS);
  unsigned int STDP=weightUpdateModels.size()-1;`

  // define the actual network model here
  model.setName("someModel");
  // add neuron and synapse populations ... 
  model.finalize();
}
```

**Comment by emurgano** [comment]
The answers at your initial questions are both yes.
I've tried to use your code to implement this synapse, but when I try to build the model, this doesn't work. The code is:
```
#define DT 0.1  //!< This defines the global time step at which the simulation will run
#include "C:\genn-team-genn-7e7c239\lib\include\modelSpec.h"
#include "C:\genn-team-genn-7e7c239\lib\include\modelSpec.cc"

double par[4] = {
		
	0.02,	// 0 - a
	0.2, 	// 1 - b
	-65, 	// 2 - c
	6 	// 3 - d
		
	};
	
	double ini[2] = {
	-65,	//0 - V
	-20	//1 - U
		
	};
	
	double cond_ini[1] = {0.05} ; // excitatory syn.
	
	double par_syn[4] = {
		0.02,		//1: A+
		-0.02,		//2: A-
		20,			//3: tau+
		10			//4: tau-
		
	};
	
	double ps_param[1] = {5.0} ; //tau, 

//--------------------------------------------------------------------------
/*! \brief This function defines a model with novel synapses
 */
//--------------------------------------------------------------------------

void modelDefinition(NNmodel &model) 
{   
    // initialize standard models
    initGeNN();
 /******************************************************************/       
  // define a user-defined synapse

  postSynModel ps;
  ps.varNames.clear();
  ps.varTypes.clear();

  ps.varNames.push_back(tS("EEEE")); 
  ps.varTypes.push_back(tS("scalar"));  

  ps.pNames.clear();
  ps.dpNames.clear(); 

  ps.pNames.push_back(tS("tau")); 
  ps.dpNames.push_back(tS("expDecay"));

  ps.postSynDecay=tS("");
  ps.postSyntoCurrent=tS("$(inSyn)");
  postSynModels.push_back(ps);
  unsigned int POSTSYN1=postSynModels.size()-1; //this index to be used in addSynapsePopulation*/

  weightUpdateModel wuS; 
  
  //no need to clear anything if using a new object like this
  wuS.varNames.push_back(tS("w"));
  wuS.varTypes.push_back(tS("scalar"));
  
  wuS.pNames.push_back(tS("A_p"));
  wuS.pNames.push_back(tS("A_m"));
  wuS.pNames.push_back(tS("tau_p"));
  wuS.pNames.push_back(tS("tau_m"));
  
  // code for presynaptic spike:
  wuS.simCode= tS("scalar dt=($(sT_pre)-($(sT_post))); \n\
     scalar dw=0.0; \n\
     if (dt<0.0) dw=($(A_p))*exp(dt/($(tau_p))) ; \n\
     else dw=($(A_m))*exp(-(dt/($(tau_m)))); \n\
     ($(w))=$(w)+dw; \n\
     if (($(w))>= 8) $(w)=8; \n\
     else if (($(w))<=-8) $(w)=-8;"); 
  wuS.evntThreshold= tS("1"); // do this all the time
  wuS.simCodeEvnt= tS("scalar eps; \n\
     if ((t-($(sT_pre))) >= 0) \n\
     eps=((t-($(sT_pre)))/$(tau))*exp(1.0-(t-($(sT_pre)))/$(tau)); \n\
     else eps=0; \n\
     $(addtoinSyn)=$(w)*eps; \n\
     $(updatelinsyn); \n\
     if (fmod(t,3000.0) < 1e-4) $(w)= 0.95*($(w));");
  wuS.simLearnPost=tS("scalar dt= $(sT_pre)-$(sT_post); \n\
     scalar dw= 0.0; \n\
     if (dt<0.0) dw=($(A_p))*exp(dt/$(tau_p)); \n\
     else dw=($(A_m))*exp(-(dt/$(tau_m))); \n\
     $(w)=$(w)+dw; \n\
     if ($(w)>=8.0) $(w)=8.0; \n\
     else if ($(w)<=-8.0) $(w)=-8.0;");
  wuS.needPreSt=TRUE;
  wuS.needPostSt=TRUE;
  weightUpdateModels.push_back(wuS);
  unsigned int STDP=weightUpdateModels.size()-1;`

  // define the actual network model here
  model.setName("someModel");
  // add neuron and synapse populations ...

	model.addNeuronPopulation("Pop1", 1, IZHIKEVICH, par, ini); 
	model.addNeuronPopulation("Pop2", 1, IZHIKEVICH, par, ini);
	model.addSynapsePopulation("PopSyn", STDP, ALLTOALL, INDIVIDUALG, NO_DELAY, POSTSYN1, "Pop1", "Pop2", cond_ini, par_syn, NULL, ps_param);  
  model.finalize();
}
```

In the code, I've added the parameters of the synapse (<code>A_p</code>, <code>A_m</code>, <code>tau_p</code>, <code>tau_m</code>) with <code>wuS.pNames.push_back(tS("A_p"));</code> and so on.. 
The error given by the compilator is: <code>error C2018: unknown character '0x60'</code> in the line <code>unsigned int STDP=weightUpdateModels.size()-1;</code>.
Probably the definition of the model isn't exactly correct, but I can't find the problem. Can you help me? Thank you so much!

**Comment by jamesturner246** [comment]
There's a ` character on the end of the offending line. delete that and try again.

**Comment by emurgano** [comment]
Ops... I hadn't really see it, thank you!
I've tried to execute the code again, but this still doesn't work. I've noticed that the issue is in the <code>addSynapsePopulation</code> method (because if I comment that line, the code works: so, I think, the synaptic model is correctly defined but the simulator can't create a new synapse population). Besides, I have deleted some lines in the definition of the postSynModel object, in particular the lines which describe the variable and the dependent parameters of the object, because they brought the simulator to crash (in particular the variable of postSynModel isn't used). 
When I compile the code, the simulator returns this error in the <code>synapseKrnl.cc</code> file: <code>error: identifier "ShSpk" is undefined</code>, and it refers to the line: <code> float dt=dd_sTPop1[id]-(dd_sTPop2[ShSpk[j]]);</code> but I can't understand why this happens. Any suggestions?

The new code is:
```
 #define DT 0.1  //!< This defines the global time step at which the simulation will run
#include "C:\genn-team-genn-7e7c239\lib\include\modelSpec.h"
#include "C:\genn-team-genn-7e7c239\lib\include\modelSpec.cc"


// put global variables, e.g. for initial values etc, here

double par[4] = {
		
	0.02,	// 0 - a
	0.2, 	// 1 - b
	-65, 	// 2 - c
	6 	// 3 - d
		
	};
	
	double ini[2] = {
	-65,	//0 - V
	-20	    //1 - U
		
	};
	
	double cond_ini[1] = {0.05}; // excitatory syn., w(ini)
	
	double par_syn[5] = {
		0.02,		//1: A+
		-0.02,		//2: A-
		20.0,		//3: tau+
		10.0,		//4: tau-
		5.0         //5: tau
	};
	
	double *ps_ini=NULL;
	
	double ps_param[1] = {5.0}; //tau, 

//--------------------------------------------------------------------------
/*! \brief This function defines a model with novel synapses
 */
//--------------------------------------------------------------------------

void modelDefinition(NNmodel &model) 
{   
    // initialize standard models
    initGeNN();
 /******************************************************************/       
  // define a user-defined synapse
  //model.setPrecision("float");

  postSynModel ps;
  ps.varNames.clear();
  ps.varTypes.clear();

//  ps.varNames.push_back(tS("EEEE")); 
//  ps.varTypes.push_back(tS("scalar"));  

  ps.pNames.clear();
  ps.dpNames.clear(); 

  ps.pNames.push_back(tS("tau")); 
//  ps.dpNames.push_back(tS("expDecay"));

  ps.postSynDecay=tS("");
  ps.postSyntoCurrent=tS("$(inSyn)");
  postSynModels.push_back(ps);
  unsigned int POSTSYN1=postSynModels.size()-1; //this index to be used in addSynapsePopulation*/

  weightUpdateModel wuS; 
  
  //no need to clear anything if using a new object like this
  wuS.varNames.push_back(tS("w"));
  wuS.varTypes.push_back(tS("scalar"));
  
  wuS.pNames.push_back(tS("A_p"));
  wuS.pNames.push_back(tS("A_m"));
  wuS.pNames.push_back(tS("tau_p"));
  wuS.pNames.push_back(tS("tau_m"));
  wuS.pNames.push_back(tS("tau"));
  
  // code for presynaptic spike:
  wuS.simCode= tS("scalar dt=$(sT_pre)-($(sT_post)); \n\
     scalar dw=0.0; \n\
     if (dt<0.0) dw=$(A_p)*exp(dt/($(tau_p))) ; \n\
     else dw=$(A_m)*exp(-(dt/($(tau_m)))); \n\
     ($(w))=$(w)+dw; \n\
     if (($(w))>= 8) $(w)=8.0; \n\
     else if (($(w))<=-8) $(w)=-8;"); 
  wuS.evntThreshold= tS("1"); // do this all the time
  wuS.simCodeEvnt= tS("scalar eps; \n\
     if ((t-($(sT_pre))) >= 0) \n\
     eps=((t-$(sT_pre))/$(tau))*exp(1.0-(t-$(sT_pre))/$(tau)); \n\
     else eps=0; \n\
     $(addtoinSyn)=$(w)*eps; \n\
     $(updatelinsyn); \n\
     if (fmod(t,3000.0) < 1e-4) $(w)= 0.95*$(w);");
  wuS.simLearnPost=tS("scalar dt=$(sT_pre)-($(sT_post)); \n\
     scalar dw=0.0; \n\
     if (dt<0.0) dw= $(A_p)*exp(dt/$(tau_p)); \n\
     else dw=$(A_m)*exp(-(dt/$(tau_m))); \n\
     $(w)=$(w)+dw; \n\
     if ($(w)>=8.0) $(w)=8.0; \n\
     else if ($(w)<=-8.0) $(w)=-8.0;");
  wuS.needPreSt= TRUE;
  wuS.needPostSt= TRUE;
  weightUpdateModels.push_back(wuS);
  unsigned int STDP=weightUpdateModels.size()-1;

  // define the actual network model here
  model.setName("someModel");
  // add neuron and synapse populations ...

	model.addNeuronPopulation("Pop1", 1, IZHIKEVICH, par, ini); 
	model.addNeuronPopulation("Pop2", 1, IZHIKEVICH, par, ini);
	model.addSynapsePopulation("PopSyn", STDP, ALLTOALL, INDIVIDUALG, NO_DELAY, POSTSYN1, "Pop1", "Pop2", cond_ini, par_syn, ps_ini, ps_param);  
  model.finalize();
}
```

**Comment by tnowotny** [comment]
For some reason there is a "backtick" or other strange character at the end of that particular line ... it doesn't show here, but in my email version it did:
unsigned int STDP=weightUpdateModels.size()-1;`
Please remove it.

**Comment by tnowotny** [comment]
Which branch are you using? I just made a mock project with your code in the development branch and it compiles fine.

**Comment by emurgano** [comment]
I'm using the <code>7e7c239</code> version, but I've changed the code and now it compiles fine. 
But, now, I've another problem in the <code>simCodeEvnt</code> method; I was forced to change the definition of the variable <code>epsilon</code> in order to describe in a more realistic way its behaviour, like a dynamic system when there are more presynaptic close spikes between them.
In particular, the code is: 

```
#define DT 0.1  //!< This defines the global time step at which the simulation will run
#include "C:\genn-team-genn-7e7c239\lib\include\modelSpec.h"
#include "C:\genn-team-genn-7e7c239\lib\include\modelSpec.cc"


// put global variables, e.g. for initial values etc, here

double par[4] = {
		
	0.02,	// 0 - a
	0.2, 	// 1 - b
	-65, 	// 2 - c
	6 	// 3 - d
		
	};
	
	double ini[2] = {
	-65,	//0 - V
	-20	    //1 - U
		
	};
	
	double cond_ini[13] = {0.05,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0}; // excitatory syn., w(ini)
	
	double par_syn[5] = {
		0.02,		//1: A+
		-0.02,		//2: A-
		20.0,		//3: tau+
		10.0,		//4: tau-
		5.0         //5: tau
	};
	
	double *ps_ini=NULL;
	
	double ps_param[1] = {5.0}; //tau, 

//--------------------------------------------------------------------------
/*! \brief This function defines a model with novel synapses
 */
//--------------------------------------------------------------------------

void modelDefinition(NNmodel &model) 
{   
    // initialize standard models
    initGeNN();
 /******************************************************************/       
  // define a user-defined synapse
  //model.setPrecision("float");

  postSynModel ps;
  ps.varNames.clear();
  ps.varTypes.clear();

//  ps.varNames.push_back(tS("EEEE")); 
//  ps.varTypes.push_back(tS("scalar"));  

  ps.pNames.clear();
  ps.dpNames.clear(); 

//  ps.pNames.push_back(tS("tau")); 
//  ps.dpNames.push_back(tS("expDecay"));

  ps.postSynDecay=tS("");
  ps.postSyntoCurrent=tS("$(inSyn)");
  postSynModels.push_back(ps);
  unsigned int POSTSYN1=postSynModels.size()-1; //this index to be used in addSynapsePopulation*/

  weightUpdateModel wuS; 
  
  //no need to clear anything if using a new object like this
  wuS.varNames.push_back(tS("w")); // peso sinaptico
  wuS.varTypes.push_back(tS("scalar"));
  wuS.varNames.push_back(tS("epsilon_p")); // contiene il valore precedente di epsilon
  wuS.varTypes.push_back(tS("scalar"));
  wuS.varNames.push_back(tS("epsilon")); // contiene il valore attuale di epsilon
  wuS.varTypes.push_back(tS("scalar"));
  wuS.varNames.push_back(tS("epsilon_1")); // contiene il valore precedente di epsilon_1t
  wuS.varTypes.push_back(tS("scalar"));
  wuS.varNames.push_back(tS("epsilon_2")); // contiene il valore precedente di epsilon_2t
  wuS.varTypes.push_back(tS("scalar"));
  wuS.varNames.push_back(tS("epsilon_1t")); // contiene il valore attuale di epsilon_1t
  wuS.varTypes.push_back(tS("scalar"));
  wuS.varNames.push_back(tS("epsilon_2t")); // contiene il valore attuale di epsilon_2t
  wuS.varTypes.push_back(tS("scalar"));
  wuS.varNames.push_back(tS("spike_1t")); // contiene il tempo di spike
  wuS.varTypes.push_back(tS("scalar"));  
  wuS.varNames.push_back(tS("spike_2t"));	// contiene il tempo di spike
  wuS.varTypes.push_back(tS("scalar"));
  wuS.varNames.push_back(tS("flag_1")); // abilita epsilon_1t
  wuS.varTypes.push_back(tS("scalar"));
  wuS.varNames.push_back(tS("flag_2")); // abilita epsilon_2t
  wuS.varTypes.push_back(tS("scalar"));
  
  wuS.varNames.push_back(tS("debug_y"));
  wuS.varTypes.push_back(tS("scalar"));
  wuS.varNames.push_back(tS("debug_x"));
  wuS.varTypes.push_back(tS("scalar"));
  
  wuS.pNames.push_back(tS("A_p"));
  wuS.pNames.push_back(tS("A_m"));
  wuS.pNames.push_back(tS("tau_p"));
  wuS.pNames.push_back(tS("tau_m"));
  wuS.pNames.push_back(tS("tau"));
  
  // code for presynaptic spike:
  wuS.simCode= tS("scalar dt=t-($(sT_post)); \n\
     scalar dw=0.0; \n\
     if (dt<0.0) dw=$(A_p)*exp(dt/($(tau_p))) ; \n\
     else dw=$(A_m)*exp(-(dt/($(tau_m)))); \n\
     ($(w))=$(w)+dw; \n\
     if (($(w))>= 8) $(w)=8.0; \n\
     else if (($(w))<=-8) $(w)=-8;"); 
  wuS.evntThreshold= tS("1"); // do this all the time
  wuS.simCodeEvnt= tS("scalar eps; \n\
	 if (t==0) {\n\
		 $(epsilon_p)=0;\n\
		 $(epsilon)=0;\n\
		 $(epsilon_2)=0;\n\
		 $(flag_1)=0;\n\
		 $(flag_2)=0;\n\
		 $(spike_1t)=-100;\n\
		 $(spike_2t)=10;\n\
		 $(epsilon_1t)=100;\n\
		 $(epsilon_2t)=0;\n\
	 }\n\
	 if ($(epsilon_1t) == $(spike_2t))  $(epsilon_1t)= 50;\n\
	 else $(epsilon_1t)= 30;\n\
	 if ( $(sT_pre)== t ) $(epsilon_1t)= $(epsilon_1t) - 10; \n\
	 $(debug_y)=$(spike_1t);\n\
	 $(debug_x)=$(epsilon_1t);\n\
     if ((t-($(sT_pre))) >= 0) \n\
     eps=((t-$(sT_pre))/$(tau))*exp(1.0-(t-$(sT_pre))/$(tau)); \n\
     else eps=0; \n\
     $(addtoinSyn)=$(w)*eps; \n\
     $(updatelinsyn); \n\
     if (fmod(t,3000.0) < 1e-4) $(w)= 0.95*$(w);");
  wuS.simLearnPost=tS("scalar dt=$(sT_pre)-t; \n\
     scalar dw=0.0; \n\
     if (dt<0.0) dw= $(A_p)*exp(dt/$(tau_p)); \n\
     else dw=$(A_m)*exp(-(dt/$(tau_m))); \n\
     $(w)=$(w)+dw; \n\
     if ($(w)>=8.0) $(w)=8.0; \n\
     else if ($(w)<=-8.0) $(w)=-8.0;");
  wuS.needPreSt= TRUE;
  wuS.needPostSt= TRUE;
  weightUpdateModels.push_back(wuS);
  unsigned int STDP=weightUpdateModels.size()-1;

  // define the actual network model here
  model.setName("someModel");
  // add neuron and synapse populations ...

	model.addNeuronPopulation("Pop1", 1, IZHIKEVICH, par, ini); 
	model.addNeuronPopulation("Pop2", 1, IZHIKEVICH, par, ini);
	model.addSynapsePopulation("PopSyn", STDP, ALLTOALL, INDIVIDUALG, NO_DELAY, POSTSYN1, "Pop1", "Pop2", cond_ini, par_syn, ps_ini, NULL);  
  model.finalize();
}
```
N.B.: the values of the variables are fictitious, they are used to do debug.

The main code is: 
```
#include "C:\genn-team-genn-7e7c239\userproject\sinapsi\sinapsi.cc"
#include "C:\genn-team-genn-7e7c239\userproject\sinapsi\someMODEL_CODE\runner.cc"
#include "C:\genn-team-genn-7e7c239\lib\include\hr_time.cpp"


int main() {
CStopWatch timer; 
ofstream os("output.V.dat");
int i;
double t= 0;
timer.startTimer();
allocateMem();
initialize();


	wPopSyn[1]=0.001;
	wPopSyn[2]=0.001;
	wPopSyn[3]=0.001;
	pushPopSynToDevice();
	


for(i=0; i< 5000; i++) {
	
	stepTimeGPU(t);
	
	pullPop1StateFromDevice();
	pullPop2StateFromDevice();
	pullPopSynStateFromDevice();
	
	
//	cout << "Time: " << t << endl;
	
	os << t << " "; //1 tempo
	os << VPop1[0] << " " ; //2 neuroni presinaptici
	os << VPop2[0] << " "; // 3 neurone postsinaptico
	os << wPopSyn[0] << " "; //4 - > peso sinaptico
	os << wPopSyn[1] << " "; //5 - > peso sinaptico
	os << wPopSyn[2] << " "; //6 - > peso sinaptico
	os << wPopSyn[3] << " "; //7 - > peso sinaptico
	os << debug_yPopSyn[0] << " "; // 8 -> debug_y -> spike_1t
	os << debug_xPopSyn[0] << " "; // 9 -> debug_x -> epsilon_1t
	os << yPop1[0] << " "; //10 - > corrente sinaptica pre
	os << yPop2[0] << " "; //11 - > corrente sinaptica post
//	os << yPopSyn[0] << " "; //12 // epsilon
	os << endl;
	
	t+=0.2;
	
	
}

os.close();

timer.stopTimer();

cout << "Esecuzione terminata." << endl;
cout << "Durata esecuzione: " << timer.getElapsedTime();



return 0;
}
```
N.B. I've added a new variable, <code>y</code>, in the Izhikevich neuron only to plot the current.

The issues which I've found are these:
1) if I define the initial conditions in <code>cond_ini</code> vector, and in the <code>simCodeEvnt</code> method I wanted that if t =0 the values of some variables have to change, this doesn't happen: the <code>$(spike_1t)</code> variable is always setted to 0, while the <code>$(epsilon_1t)</code> variable for <code>t=0</code> is <code>0</code> (as is defined in the <code>cond_ini</code> vector);
for <code>t=0.2</code> is equal to <code>50</code>, because the inital values of <code>$(epsilon_1t) </code> and <code>$(spike_2t)</code> are the same; 
from <code>t=0.4</code> it changes again and <code>$(epsilon_1t) </code> is setted to <code>30</code>, because the initial <code>if</code> changes the variables (these two last changes are given by 
<code> if ($(epsilon_1t) == $(spike_2t))  $(epsilon_1t)= 50;
	    else $(epsilon_1t)= 30; </code>). 
So, why <code>$(epsilon1)</code> and <code>$(spike_2t)</code> change but <code>$(spike_1t)</code> not? Also, why the change, which should take place at t=0, starts at the third step?
2) if I use this following instruction:
<code>  if ( $(sT_pre)== t ) $(epsilon_1t)= $(epsilon_1t) - 10; </code>
it isn't never executed, while if I change the condition: <code>if ( t - $(sT_pre)>0)</code> the instruction is executed. So, why <code>t</code> is always different from <code>$(sT_pre)</code>?  But this isn't true, because if I write in a file its values, when a presynaptic spike occurs the variable <code>$(sT_pre)</code> has the value of the time step when it happens: so, only for a time step, t=$(sT_pre)!
Would you explain me, in details, how the <code>simCodeEvnt</code> works and how can I fix my problems? Thank you!

P.S: The attached file is the plot of <code>epsilon_1t</code> and <code>spike_1t</code>
![untitled](https://cloud.githubusercontent.com/assets/19346774/15626904/0141e170-24d2-11e6-95a5-8dcb81f01004.png)

**Comment by esinyavuz** [comment]
`t` is the current execution time, and the value for `sT_pre` is set at the end of the execution for one time step. Therefore the maximum value that `sT_pre` can get is t - DT. You may want to check the code generated by GeNN to have an idea (in yourmodelname_CODE/neuronKrnl.cc -- or neuronFnct.cc for CPU code)

By the way I noticed that you defined DT=0.1 in the code that includes `modelDefinition` but your time step for numerical integration in the simulation code is 0.2. This should be set to DT; as you are using the built-in Izhikevich neuron, it will be integrating for the first half of your time step. 

Another small remark: It is not a good idea to compare floats directly like `if (A == B)`. It is safer to do something like `if (abs(A-B) < eps)` where `eps` is a small enough value (more info [here](https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/)).

**Comment by jamesturner246** [comment]
Resolved? - Closing.
