### ISSUE TITLE
Ambiguity in connectivity/conductance schemes

### ISSUE THREAD

**Issue by esinyavuz** [genn-team/genn#92]
I was about to add some stuff in the documentation explaining the different combinations of `GLOBALG` / `INDIVIDUALG` / `INDIVIDUALID` conductance schemes with `ALLTOALL` / `DENSE` / `SPARSE` connectivity schemes, but I am confused myself with the way we have implemented some of these so I write it down here as it can be useful for other users and we can consider simplifying it in future releases.

It looks like we perform some variable substitutions in the `simCode` only if `INDIVIDUALG` is used. We substitute the values of the initial values of the variables without the 'dd_' prefix and the neuron index otherwise. This is because of some historical reasons from the times when we only had the conductance as a variable. On the other hand, it may also make more sense to make the conductance a parameter instead of a variable when `GLOBALG` is used. And it is actually possible to have synapses which have both fixed and variable members, by defining those as parameters or variables.

I will try to explain the current situation and how I thing it can be done:

|  | ALLTOALL | DENSE | SPARSE |
| --- | :-: | :-: | :-: |
| GLOBALG | Fixed values for all synapse members | Fixed values for all synapse members | Fixed values for some synapse members (using sparse indexing) |
| INDIVIDUALG | Variable values for all synapse members | Variable values for all synapse members | Variable values for some synapse members |
| INDIVIDUALID | Fixed variables for some synapse members (using bit shifting) | Fixed variables for some synapse members (using bit shifting) | N/A |

`INDIVIDUALID` was considered to be useful for `DENSE` connectivities, but in practice there is no difference between `ALLTOALL` and `DENSE`. At the end in reality, all we need is to decide whether we have to keep values for all synapse members or for some only, an decide how we do it. Fixed values can be expressed as parameters, index and time dependent ones can be variables. In case of sparse connectivity, we can include a `INDIVIDUALID`-like behaviour for fixed values. Actually this makes code generation much easier, and we can write wrapper functions for existing users.

Also there are still some explicit references to the obsolete hard-coded variable `g` (e.g. [here](https://github.com/genn-team/genn/blob/development/lib/src/generateKernels.cc#L666)). We will get rid of these small mistakes if we simplify the connectivity schemes.

Feel free to edit the table above if I have mistaken anything.

**Comment by jamesturner246** [comment]
I think this is done. Closing.
