### ISSUE TITLE
GeNN and CUDA SDK v8.0

### ISSUE THREAD

**Issue by hdinkelbach** [genn-team/genn#93]
Good evening everybody,

I hopefully found the right place for my comment, if not, feel free to delete/move.

I currently test something with your simulation environment and run into an conflict with the new CUDA SDK v8.0. With the recent SDK, nvidia (finally) added an atomicAdd() for double precision. Running the PoissonInh example leads to the error that atomicAdd() is already defined. When I run into this error, I found an easy solution in the official documentation (section B.12):

```
#if !defined( __CUDA_ARCH__) || __CUDA_ARCH__ >= 600
#else
__device__ double atomicAdd(double* address, double val) {
// ... implementation of atomicAdd for non-pascal
}
#endif
```

Best,
Helge

**Comment by jamesturner246** [comment]
Hi Helge.

Thanks a lot for pointing that one out! It's been fixed, just in time for a merge to master, and a new release. You can try it immediately in the development branch, though.

All the best,
James.

**Comment by jamesturner246** [comment]
Hum.. That is very odd... The code generator knows about the SM version by the time it reaches that point, so it shouldn't be generating the CUDA atomicAdd(double *, double). 

I guess the CUDA double atomicAdd's host declaration must be being temporarily included in the nvcc host code compile phase, where __CUDA_ARCH__ isn't defined, so CUDA is temporarily seeing both atomicAdd declarations when compiling the host code portion, even though the device code .cubin compilation phase only sees the GeNN declaration. Or perhaps I'm completely wrong, and CUDA compilation is even more baffling than ever...

I will include your fix verbatim this time. Cheers again for helping us with this; it's great to have some regular users helping to iron out the bugs!

Regards,
James.

**Comment by jamesturner246** [comment]
Fixed and merged into master. I updated tag 2.2 with this change as well.

**Comment by esinyavuz** [comment]
@jamesturner246 , I have pulled the latest master branch and I get the following error on Tesla C2070 with CUDA Toolkit 6.5:

```

error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
```

  CUDA Driver Version / Runtime Version          6.5 / 6.5
  CUDA Capability Major/Minor version number:    2.0

**Comment by esinyavuz** [comment]
It now works with the fix in the development branch commit e2a976e. We need to test it on other machines before merging with master.

**Comment by jamesturner246** [comment]
Yeah. 

I predict it won't work on @hdinkelbach's machine again, but I think we should wait for the final CUDA 8.0 SDK release before attempting to fix this, just in case they change anything or fix it before then. 

Sorry Helge. I think you'll have to manually patch it in the meantime!
James.

**Comment by hdinkelbach** [comment]
Hi all,

@jamesturner246 good news: I checked out the latest development state and it works nice also on my machines (Tesla C2050, Toolkit 8.0 RC and GTX470, Toolkit 6.5).

Thank you very much again for your efforts and a big sorry for causing trouble, also @esinyavuz.

Best,
Helge

**Comment by jamesturner246** [comment]
Ah, perfect. Then it's resolved. It's no trouble Helge; thanks for pointing out something we likely would not have noticed!

I think this warrants a micro-release 2.2.1, since #97 and #101 have also been fixed. I'm having some problems with SynDelay_project and the `glbSpkSHift<group>` macro I want to fix first, though. @esinyavuz and @tnowotny I'll email after regarding the 2.2.1 release.

Cheers all,
James.
