### ISSUE TITLE
Simulation time + Linked lists usage in synapse definition

### ISSUE THREAD

**Issue by spinang** [genn-team/genn#94]
Good morning,

I'd like to ask you just two questions regarding the functionalities provided by the GeNN.

1. "Silly" question: must the step simulation time DT within both the .cc and .cu files be the same? Which is its unit measure?

2. "Serious" question: I would to define a linked list in which a single item is a struct that comprises some scalar variables. The idea is the following: this list should be a parameter of a weightUpdateModel object. Moreover, when a certain event occurs (for instance, when there's a presynaptic spike), I would to "activate" an add method to create a new struct, filling it and attaching it to the list. Is this procedure achievable?

**Comment by jamesturner246** [comment]
Hi Crypto. Apologies for the delay. 

You should only define DT once, inside your model file, preferably using `model.setDT(0.1);`, else `#define DT 0.1`. If you absolutely must define it twice, then make sure they both define the same value.

Re. serious question: CUDA is currently not quite there, in terms of allowing dynamic memory allocation inside device code. Right now, CUDA allows a limited dynamic allocation, which returns a pointer to a limited subset of global device heap memory (default 8MB, but can be changed with cudaLimitMallocHeapSize). This pointer can only be read/written to in device code, not host code, so it's a pain to copy data to and from dynamically allocated device memory. You would need to first copy the data (in device code) into a host-allocated memory buffer, and then copy from that buffer (in host code) back to the host. It's really messy.

If you are still keen on this idea, then you can use the extraGlobal[Synapse|Neuron]KernelParameters mechanism to store an array of device pointers, pointing to the leading element of each linked list, then allocate new list nodes with malloc (inside device code - *do not forget to free() old nodes!*). Don't forget that you would likely need to change the device heap size from the default 8MB using cudaLimitMallocHeapSize.

I will try to be of assistance with this where I can, but might not be much help if I don't know exactly what your goals are with this. Let me know how you get on.

Cheers,
James.

**Comment by spinang** [comment]
Don't worry for the delay.

I appreciate your help in any case!

**Comment by jamesturner246** [comment]
Resolved? - Closing.
